/* Advanced educational modules. Functional geometry, not production calibre CAD. */
window.createAdvancedWatch=function(T,scene,root,face,S,hooks,toothShape){
 const $=id=>document.getElementById(id),tau=2*Math.PI,state=new WatchAdvancedState();let mode='none',isolated=false,focus=0,wrist=false,wristTime=0,rotorQueue=0,dateShown=0,lastDate=-1,uiTime=0,autoPaused=false,autoSlow=true,clutchTheta=.24,chronoInputAngle=0,lastInputSeconds=0,resetPaused=false,pusherPulse=0;
 const assembly=new T.Group();root.add(assembly);const views={automatic:new T.Group(),calendar:new T.Group(),gmt:new T.Group(),moon:new T.Group(),chronograph:new T.Group()};Object.values(views).forEach(g=>{scene.add(g);g.visible=false;});
 const C={gold:0xc6a35c,blue:0x168ab4,green:0x19896c,red:0xd45451,steel:0x8596aa,pale:0xe4e9ed};
 function mat(c){return new T.MeshStandardMaterial({color:c,metalness:.35,roughness:.38,side:T.DoubleSide});}
 function mesh(geo,g,c){const m=new T.Mesh(geo,mat(c));g.add(m);return m;}
 function disc(r,h,g,c,z=0){const m=mesh(new T.CylinderGeometry(r,r,h,48),g,c);m.rotation.x=Math.PI/2;m.position.z=z;return m;}
 function bar(x1,y1,x2,y2,w,g,c,z=0,h=.06){const m=mesh(new T.BoxGeometry(Math.hypot(x2-x1,y2-y1),w,h),g,c);m.position.set((x1+x2)/2,(y1+y2)/2,z);m.rotation.z=Math.atan2(y2-y1,x2-x1);return m;}
 function ring(ro,ri,g,c,z=0,h=.08,start=0,end=tau){const a=new T.Shape();a.absarc(0,0,ro,start,end,false);a.lineTo(Math.cos(end)*ri,Math.sin(end)*ri);a.absarc(0,0,ri,end,start,true);a.closePath();const m=mesh(new T.ExtrudeGeometry(a,{depth:h,bevelEnabled:false,curveSegments:80}),g,c);m.position.z=z;return m;}
 function at(g,x,y,z=0){const a=new T.Group();a.position.set(x,y,z);g.add(a);return a;}
 function gear(n,r,g,c,z=0){const a=at(g,0,0,z),s=toothShape(n,r);const hole=new T.Path();hole.absarc(0,0,r*.68,0,tau,true);s.holes.push(hole);a.userData.gear={n,r,width:.07};mesh(new T.ExtrudeGeometry(s,{depth:.07,bevelEnabled:false}),a,c);ring(r*.19,r*.12,a,c);for(let i=0;i<4;i++){const t=i*tau/4;bar(Math.cos(t)*r*.15,Math.sin(t)*r*.15,Math.cos(t)*r*.72,Math.sin(t)*r*.72,.045,a,c,.035);}return a;}
 function labelTexture(txt,w=512,h=128){if(/^\d+$/.test(txt))w=128;const cv=document.createElement('canvas');cv.width=w;cv.height=h;const ctx=cv.getContext('2d');ctx.clearRect(0,0,w,h);ctx.fillStyle='#254357';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='600 96px sans-serif';ctx.fillText(txt,w/2,h/2);return new T.CanvasTexture(cv);}
 function text(txt,g,x,y,z,w=1,h=.25){const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:labelTexture(txt),transparent:true,depthWrite:false,side:T.DoubleSide}));m.position.set(x,y,z);g.add(m);return m;}
 function needle(g,len,color,z=0,w=.04){const a=at(g,0,0,z);bar(0,-.15,0,len,w,a,color,0,.035);disc(w*1.7,.045,a,color);return a;}
 function rotor(g,r,z=0){const a=at(g,0,0,z);ring(r,r*.65,a,C.gold,0,.13,Math.PI*.08,Math.PI*.92);bar(-r*.87,0,r*.87,0,.14,a,C.steel,.04);bar(0,0,0,r*.78,.15,a,C.steel,.04);disc(.20,.15,a,C.steel,.08);return a;}
 // Full movement overlays: real energy store is shared with the base watch.
 const installedRotor=rotor(assembly,2.65,2.65);const rotorDrive=gear(16,.30,assembly,C.blue,2.60);
 const mainDate=at(face,2.23,0,.105);mesh(new T.BoxGeometry(.52,.37,.025),mainDate,C.pale);const dateText=text('1',mainDate,0,0,.03,.44,.23);
 const chronoHand=needle(face,2.30,C.red,.40,.024);const counters=[];
 for(const [x,t] of [[-.98,'30 MIN']]){const a=at(face,x,-.68,.075);ring(.45,.42,a,C.steel,0,.015);for(let i=0;i<12;i++){const t=i*tau/12;bar(.37*Math.sin(t),.37*Math.cos(t),.42*Math.sin(t),.42*Math.cos(t),.014,a,C.steel,.025,.01);}text(t,a,0,-.17,.045,.52,.1);counters.push(needle(a,.33,C.gold,.055,.023));}
 // Automatic: two-way input with two one-way clutches, then common reduction/output.
 const au=views.automatic,ar=at(au,-2,0),autoRotor=rotor(ar,1.25,.42);const ai=gear(16,.4,ar,C.blue,.18);
 const branchY=Math.sqrt(.8*.8-.4*.4),revA=at(au,-1.2,0),revB=at(au,-.4,0),out=at(au,-.8,branchY),red=at(au,.5,branchY),barrel=at(au,1.3,branchY);
 const ra=gear(16,.4,revA,C.blue,.18),rb=gear(16,.4,revB,C.green,.18),raOut=gear(12,.3,revA,C.gold,-.18),rbOut=gear(12,.3,revB,C.gold,-.18),og=gear(20,.5,out,C.gold,-.18),rg=gear(32,.8,red,C.gold,-.18),rp=gear(8,.2,red,C.gold,-.53),bg=gear(24,.6,barrel,C.gold,-.53);
 for(const g of [revA,revB])disc(.07,.50,g,C.steel,.06);disc(.07,.43,red,C.steel,-.32);
 const clutchCaps=[];for(const r of [revA,revB]){const cage=at(r,0,0,.31);ring(.28,.19,cage,C.steel,0,.025);const pawl=at(cage,.232,0,.065);bar(0,0,RatchetContact.length*.002,0,.025,pawl,C.red);disc(.022,.04,pawl,C.steel,.02);const rs=new T.Shape();RatchetContact.points.forEach(([x,y],i)=>i?rs.lineTo(x*.002,y*.002):rs.moveTo(x*.002,y*.002));rs.closePath();const bore=new T.Path();bore.absarc(0,0,.075,0,tau,true);rs.holes.push(bore);const core=mesh(new T.ExtrudeGeometry(rs,{depth:.045,bevelEnabled:false}),r,C.gold);core.position.z=.37;clutchCaps.push({cage,pawl,core,contact:RatchetContact.create()});}
 disc(.5,.32,barrel,C.steel,-.78);bar(0,0,.34,0,.05,barrel,C.blue,-.52);
 // Install the same train over the base movement: input is coaxial with the rotor,
 // output is coaxial with the existing barrel arbor.
 const installedTrain=au.clone(true),endVector=[3.3,branchY],bp=S.wheels.barrel.p;
 const installScale=Math.hypot(...bp)/Math.hypot(...endVector),installAngle=Math.atan2(bp[1],bp[0])-Math.atan2(endVector[1],endVector[0]);
 installedTrain.scale.setScalar(installScale);installedTrain.rotation.z=installAngle;installedTrain.position.set(2*installScale*Math.cos(installAngle),2*installScale*Math.sin(installAngle),2.34);assembly.add(installedTrain);
 installedTrain.children[0].children[0].visible=false;const originals=[],copies=[];au.traverse(o=>originals.push(o));installedTrain.traverse(o=>copies.push(o));
 const barrelLink=at(assembly,...bp);disc(.045,.48,barrelLink,C.steel,1.95);const rotorInputShaft=disc(.045,.30,assembly,C.steel,2.53);
 // Date ring: hour wheel drives the 24-hour wheel; finger indexes the 31-position ring.
 const ca=views.calendar,dateRing=at(ca,0,0),dateHour=gear(24,.45,ca,C.blue,.02),dayAxis=at(ca,1.35,0),dayWheel=gear(48,.9,dayAxis,C.gold,.02);
 ring(2.85,2.38,dateRing,C.pale,.15,.07);for(let i=0;i<31;i++){const a=i*tau/31+CalendarMechanics.dateGeometry.toothPhase,b=bar(2.29*Math.cos(a),2.29*Math.sin(a),2.41*Math.cos(a),2.41*Math.sin(a),.08,dateRing,C.gold,.14);const numberAngle=-i*tau/31,t=text(String(i+1),dateRing,2.62*Math.cos(numberAngle),2.62*Math.sin(numberAngle),.24,.27,.23);t.rotation.z=numberAngle;}
 // Keep the printed face opaque; only its reverse is translucent during crown inspection.
 dateRing.children[0].material.side=T.FrontSide;const dateBack=dateRing.children[0].clone();dateBack.material=dateRing.children[0].material.clone();dateBack.material.side=T.BackSide;dateRing.add(dateBack);
 const fingerCarrier=at(dayWheel,0,0);fingerCarrier.rotation.z=Math.PI/48+CalendarMechanics.dateGeometry.end;const finger=bar(.78,0,1.05,0,.075,fingerCarrier,C.red,.15);const jumperAngle=CalendarMechanics.dateGeometry.toothPhase-7.5*tau/31,jumper=at(ca,2.05*Math.cos(jumperAngle),2.05*Math.sin(jumperAngle));jumper.rotation.z=jumperAngle+Math.PI/2;const jumperTip=bar(0,0,0,-.28,.045,jumper,C.green,.15);disc(.065,.07,jumper,C.steel,.15);
 const corrector=at(ca,...CalendarMechanics.dateCorrectionGeometry.pivot),correctorArm=bar(0,0,.60,0,.045,corrector,C.blue,.14);const correctingTip=mesh(new T.BoxGeometry(.08,.08,.10),corrector,C.blue);correctingTip.position.set(.60,0,.14);const dateStem=bar(2.08/.85,-.68/.85,3.65,-1.35,.06,ca,C.steel,.3);const dateCrown=at(ca,3.65,-1.35,.3);mesh(new T.BoxGeometry(.24,.38,.22),dateCrown,C.steel);disc(.10,.07,corrector,C.blue,.10);ring(.37,.29,ca,C.steel,-.03);
 for(const [x1,y1,x2,y2] of [[2.40,-.20,2.84,-.20],[2.40,.20,2.84,.20],[2.40,-.20,2.40,.20],[2.84,-.20,2.84,.20]])bar(x1,y1,x2,y2,.025,ca,C.blue,.30,.025);
 // Chronograph: continuously driven wheel, swinging clutch, column wheel, brake, heart and hammer.
 const ch=views.chronograph,input=at(ch,-2,0),drive=gear(22,.55,input,C.green),clutch=at(ch,-1,0),coupling=gear(18,.45,clutch,C.blue),output=gear(22,.55,ch,C.red);
 const heart=new T.Shape();ChronoGeometry.heart.forEach(([x,y],i)=>i?heart.lineTo(x,y):heart.moveTo(x,y));heart.closePath();const heartMesh=mesh(new T.ExtrudeGeometry(heart,{depth:.08,bevelEnabled:false}),output,C.gold);heartMesh.position.z=.12;const measureHand=needle(output,1.1,C.red,.29,.045);measureHand.visible=false;
 disc(.05,.32,clutch,C.steel,.18);const column=at(ch,-1.5,1.2);disc(.42,.12,column,C.steel,.12);for(let i=0;i<8;i++){const t=i*tau/8,m=mesh(new T.BoxGeometry(.16,.16,.23),column,C.blue);m.position.set(.31*Math.cos(t),.31*Math.sin(t),.28);}
 // Solid plate levers: a coupling carrier and a separate pivoted brake.
 function plateOutline(points,parent,color,z=.02){const shape=new T.Shape();points.forEach(([x,y],i)=>i?shape.lineTo(x,y):shape.moveTo(x,y));shape.closePath();const m=mesh(new T.ExtrudeGeometry(shape,{depth:.055,bevelEnabled:true,bevelSize:.012,bevelThickness:.008,bevelSegments:2}),parent,color);m.position.z=z;return m;}
 const lever=at(ch,-2,0,.27);
 plateOutline([[-.10,-.10],[1.08,-.10],[1.08,.10],[.35,.10],[.60,.80],[.50,.91],[.39,.85],[.16,.24],[-.10,.12]],lever,C.steel);
 disc(.10,.08,lever,C.gold);disc(.075,.10,lever,C.steel).position.x=1;
 const brake=at(ch,.85,.85);
 plateOutline([[-.36,-.85],[-.23,-.85],[.16,-.25],[.10,.09],[-1.98,.45],[-2.04,.33],[-.07,-.04],[.01,-.24]],brake,C.green,.27);
 disc(.08,.12,brake,C.steel,.29);bar(-.30,-.85,-.30,-.73,.07,brake,C.green,.025);
 const hammer=at(ch,0,.72);bar(-.40,.06,.40,.06,.12,hammer,C.steel,.16);bar(.40,.06,1.30,.06,.10,hammer,C.steel,.16);
 const minuteCounter=at(ch,0,-1.65),minuteStar=gear(30,.45,minuteCounter,C.gold,.04),minuteNeedle=needle(minuteCounter,.65,C.gold,.17);minuteNeedle.visible=false;
 const minuteHeart=mesh(new T.ExtrudeGeometry(heart,{depth:.08,bevelEnabled:false}),minuteCounter,C.gold);minuteHeart.position.z=.14;const minuteHammer=at(ch,0,-.93);bar(-.40,.06,.40,.06,.12,minuteHammer,C.steel,.18);bar(.40,.06,1.30,.06,.10,minuteHammer,C.steel,.18);
 minuteNeedle.position.z=.32;minuteStar.position.z=-.14;disc(.055,.33,minuteCounter,C.steel,.01);disc(.055,.34,ch,C.steel,0);
 const minuteIndexAxis=at(ch,-.9,-1.65),minuteIndex=gear(30,.45,minuteIndexAxis,C.gold,-.14);const fingerDirection=Math.atan2(-1.65,-.9)+ChronoGeometry.minuteIndexing.end,fingerLength=Math.hypot(.9,1.65)-.45;const minuteFinger=bar(.20*Math.cos(fingerDirection),.20*Math.sin(fingerDirection),fingerLength*Math.cos(fingerDirection),fingerLength*Math.sin(fingerDirection),.035,output,C.blue,-.14,.035);const fingerTip=at(output,fingerLength*Math.cos(fingerDirection),fingerLength*Math.sin(fingerDirection),-.12);disc(.045,.05,fingerTip,C.blue);

 // Mounted modules retain the very same parts/angles as their enlarged inspection view.
 function mount(source,parent,scale,x,y,z,rotation=0){const g=source.clone(true);g.scale.setScalar(scale);g.position.set(x,y,z);g.rotation.z=rotation;parent.add(g);const a=[],b=[];source.traverse(o=>a.push(o));g.traverse(o=>b.push(o));return {group:g,sync(){for(let i=1;i<a.length;i++){b[i].position.copy(a[i].position);b[i].rotation.copy(a[i].rotation);b[i].scale.copy(a[i].scale);if(a[i].isMesh){b[i].material=a[i].material;for(const k of ['label','advancedPart','focusIndex'])b[i].userData[k]=a[i].userData[k];}}},copy(obj){return b[a.indexOf(obj)];}};}
 const dateMount=mount(ca,root,.85,0,0,-.78);dateMount.group.rotation.x=Math.PI;dateMount.copy(dateCrown).visible=false;dateMount.copy(dateStem).visible=false;
 const hourLink=at(root,0,0);ring(.105,.079,hourLink,C.blue,-.82,.22);
 // Crown-selected vertical arbor and an articulated correcting lever on the dial side.
 const dateInput=at(root,...S.keyless.date.p);disc(.035,2.78,dateInput,C.blue,.67);disc(.035,.23,dateInput,C.blue,-.825);
 const dateInputHead=at(dateInput,0,0,1.86);ring(.305,.225,dateInputHead,C.blue,0,.025);for(let i=0;i<18;i++){const t=i*tau/18,m=mesh(new T.BoxGeometry(.095,Math.PI*.27/18*.80,.09),dateInputHead,C.blue);m.position.set(.27*Math.cos(t),.27*Math.sin(t),.06);m.rotation.z=t;}
 const dateLink=at(root,0,0),dateEnd=CalendarMechanics.dateCorrectionGeometry.pivot.map((v,i)=>v*.85*(i?-1:1)),dateStart=S.keyless.date.p,dateR=Math.hypot(dateEnd[0]-dateStart[0],dateEnd[1]-dateStart[1])/6,dateGears=[];
 for(let i=0;i<4;i++){const ax=at(dateLink,dateStart[0]+(dateEnd[0]-dateStart[0])*i/3,dateStart[1]+(dateEnd[1]-dateStart[1])*i/3,-.72);dateGears.push(gear(18,dateR,ax,C.blue));disc(.035,.18,ax,C.steel,-.06);}
 const dateCam=at(dateLink,...dateEnd,-.84);const eccentric=disc(.085,.06,dateCam,C.red);eccentric.position.x=.075;
 const chronoSpec=S.advanced.chronograph,chronoScale=chronoSpec.scale,chronoAngle=chronoSpec.angle,chronoZ=chronoSpec.z;
 for(const [part,z] of [[hammer,.16],[minuteHammer,.18]]){const pin=disc(.055,.30/chronoScale-z,part,C.steel,(.30/chronoScale+z)/2);pin.position.x=1.30;pin.position.y=.06;}
 const chronoMount=mount(ch,root,chronoScale,2*chronoScale*Math.cos(chronoAngle),2*chronoScale*Math.sin(chronoAngle),chronoZ,chronoAngle);
 const secondsPickup=at(root,0,0);ring(chronoSpec.secondsOuter,chronoSpec.secondsInner,secondsPickup,C.green,-1.33,chronoZ+1.40);
 // Two reversals bring the measured rotation back to a separate concentric tube.
 const measuredReturn=at(root,0,0,chronoZ+.50);measuredReturn.rotation.z=chronoAngle;
 const returnGears=[];for(const x of [2*chronoScale,chronoScale,0]){const axis=at(measuredReturn,x,0);returnGears.push(gear(22,chronoScale/2,axis,C.red));}
 const outputPoint=[2*chronoScale*Math.cos(chronoAngle),2*chronoScale*Math.sin(chronoAngle)];const chronoOutputLink=at(root,...outputPoint);disc(.032,.53,chronoOutputLink,C.red,chronoZ+.25);
 const measuredTube=at(root,0,0);disc(chronoSpec.measuredRadius,chronoZ+1.94,measuredTube,C.red,(chronoZ+.54-1.40)/2);disc(.040,.08,measuredTube,C.red,chronoZ+.51);
 // Place pushers in the mechanism plane, aligned to their own actuating levers.
 const chronoPushers=at(root,0,0,chronoZ),pusherHeads=[];
 for(const [i,xy] of [[0,[2.2,-.4]],[1,[-1.5,2.35]]]){const p=at(chronoPushers,...mountedXY(...xy),.30);p.rotation.z=chronoAngle+(i===1?Math.PI/2:0);mesh(new T.CylinderGeometry(.14,.14,.30,24),p,C.steel).rotation.z=Math.PI/2;pusherHeads.push(p);}
 function mountedXY(x,y){const a=(x+2)*chronoScale,b=y*chronoScale;return [a*Math.cos(chronoAngle)-b*Math.sin(chronoAngle),a*Math.sin(chronoAngle)+b*Math.cos(chronoAngle)];}
 const minutePoint=mountedXY(0,-1.65);counters[0].parent.position.set(minutePoint[0],-minutePoint[1],.075);const counterShaft=at(root,...minutePoint);disc(.025,chronoZ+1.18,counterShaft,C.gold,(chronoZ+.10-1.08)/2);
 // Articulated control links: case pusher -> upper mechanism, with moving joints.
 const controlLinks=at(root,0,0),linkBars=[];
 function linkSegment(){const m=mesh(new T.BoxGeometry(.075,1,.045),controlLinks,C.steel);linkBars.push(m);return m;}
 for(let i=0;i<4;i++)linkSegment();
 function positionLink(m,a,b){const va=new T.Vector3(...a),vb=new T.Vector3(...b),d=vb.clone().sub(va);m.position.copy(va).add(vb).multiplyScalar(.5);m.scale.y=d.length();m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());}
 // An inspection contains the installed module AND its complete input/output paths.
 const chronoInspection=new T.Group();scene.add(chronoInspection);chronoInspection.visible=false;chronoInspection.scale.setScalar(1.20);
 const inspectionPairs=[];
 function inspectCopy(source,parent){const copy=source.clone(true);parent.add(copy);const a=[],b=[];source.traverse(o=>a.push(o));copy.traverse(o=>b.push(o));inspectionPairs.push([a,b]);return copy;}
 for(const obj of [chronoMount.group,secondsPickup,measuredReturn,chronoOutputLink,measuredTube,counterShaft,chronoPushers,controlLinks])inspectCopy(obj,chronoInspection);
 const inspectionFace=new T.Group();chronoInspection.add(inspectionFace);inspectionFace.rotation.x=Math.PI;
 inspectCopy(chronoHand,inspectionFace);inspectCopy(counters[0].parent,inspectionFace);
 ring(2.50,2.48,inspectionFace,C.steel,0,.015);
 for(let i=0;i<12;i++){const a=i*tau/12;bar(2.32*Math.sin(a),2.32*Math.cos(a),2.46*Math.sin(a),2.46*Math.cos(a),.025,inspectionFace,C.steel);}
 const dateInspection=new T.Group();scene.add(dateInspection);dateInspection.visible=false;const correctionCopies=[];
 function copyCorrection(source,parent){const copy=source.clone(true);parent.add(copy);const a=[],b=[];source.traverse(o=>a.push(o));copy.traverse(o=>b.push(o));correctionCopies.push({a,b});}
 for(const source of [dateMount.group,hourLink,dateInput,dateLink,...hooks.correctionSources()])copyCorrection(source,dateInspection);
 for(const key of ['gmt','moon'])for(const source of [dateInput,...hooks.correctionSources()])copyCorrection(source,views[key]);
 for(const [id,a,b] of [['auto input-A',ai,ra],['auto A-B',ra,rb],['auto A-output',raOut,og],['auto B-output',rbOut,og],['auto output-reduction',og,rg],['auto reduction-barrel',rp,bg],['calendar hour-day',dateHour,dayWheel],['chrono input-clutch',drive,coupling],['chrono minute index',minuteIndex,minuteStar],['chrono return 1',returnGears[0],returnGears[1]],['chrono return 2',returnGears[1],returnGears[2]]])mechanismAudit.mesh(id,a,b);mechanismAudit.mesh('chrono clutch-output',coupling,output,()=>clutchTheta<.001);for(let i=1;i<4;i++)mechanismAudit.mesh('date correction '+i,dateGears[i-1],dateGears[i]);
 const calendars=createCalendarComplications(T,root,face,views,{at,gear,disc,ring,bar,needle,text,mesh,C},hooks);
 function tintPart(g,on){g.traverse(m=>{if(!m.isMesh||!m.material?.color)return;if(!m.userData.lessonMaterial){m.material=m.material.clone();m.userData.lessonMaterial=true;m.userData.lessonColor=m.material.color.clone();}m.material.color.copy(m.userData.lessonColor);m.material.emissive?.setHex(on?0x168ab4:0);if(m.material.emissive)m.material.emissiveIntensity=on?.32:0;});}
 const namesForFocus={gmt:['01 · 시침에서 받기','02 · 24시간으로 감속','03 · GMT 독립 조정','04 · 24시간 눈금 읽기'],moon:['01 · 하루에 한 번','02 · 59치 휠과 점퍼','03 · 달판과 표시창','04 · 근사 주기와 보정'],automatic:['01 · 로터가 입력을 만듭니다','02 · 두 클러치가 방향을 고릅니다','03 · 작은 피니언이 다음 큰 휠을 돌립니다','04 · 기존 태엽통의 중심 축을 감습니다'],calendar:['01 · 기존 시침 관과 같은 축','02 · 12시간 → 24시간','03 · 날짜판을 한 칸 밀고 고정','04 · 용두에서 날짜판으로'],chronograph:['01 · 기존 초침축의 회전을 받기','02 · 클러치와 브레이크 전환','03 · 측정 바늘과 누적계로 전달','04 · 하트 캠과 해머']};
 const focusParts={...calendars.parts,automatic:[[autoRotor,ai],[ra,rb,raOut,rbOut],[og,rg,rp],[bg,barrel]],calendar:[[dateHour],[dayWheel],[dateRing,jumper],[corrector,dateCrown]],chronograph:[[input],[clutch,lever,column,brake],[output,minuteCounter,minuteIndexAxis],[hammer,heartMesh,minuteHammer,minuteHeart]]};

 function tag(g,label,chapter,index){g.traverse(m=>{if(m.isMesh)Object.assign(m.userData,{label,advancedPart:chapter,focusIndex:index});});}
 for(const [key,sets] of Object.entries(focusParts))sets.forEach((set,i)=>set.forEach(o=>tag(o,namesForFocus[key][i].replace(/^\d+ · /,''),key,i)));
 for(const [o,label,key,i] of [[installedRotor,'로터 · 손목 움직임을 회전으로','automatic',0],[barrelLink,'태엽 중심으로 내려가는 감기 축','automatic',3],[rotorInputShaft,'로터와 첫 감기 휠의 연결 축','automatic',0],[dateInput,'용두가 선택하는 날짜 조정 축','calendar',3],[dateLink,'날짜 조정 레버','calendar',3],[hourLink,'기존 시침 관과 날짜 입력 휠 연결','calendar',0],[secondsPickup,'일반 초침 관 → 크로노그래프 입력','chronograph',0],[measuredReturn,'측정 회전을 중앙으로 돌려보내는 기어','chronograph',2],[measuredTube,'가장 안쪽의 측정 초침 축','chronograph',2],[counterShaft,'분 누적계로 내려가는 축','chronograph',2],[chronoPushers,'시작·정지 / 리셋 푸셔와 레버','chronograph',1]])tag(o,label,key,i);
 for(const [i,p] of pusherHeads.entries())p.traverse(m=>{if(m.isMesh)Object.assign(m.userData,{chronoAction:i===1?'toggle':'reset',label:i===1?'시작 / 정지 푸셔 · 클릭':'리셋 푸셔 · 정지 후 클릭'});});
 tag(revA,'A 클러치 · 로터의 첫 이웃 · 시계 입력에서 잠김','automatic',1);tag(revB,'B 클러치 · A의 다음 이웃 · 반시계 입력에서 잠김','automatic',1);
 function setFocus(i){focus=i;$('advancedFocusTitle').textContent=namesForFocus[mode]?.[i]||'';for(const [key,sets] of Object.entries(focusParts))sets.forEach((set,j)=>set.forEach(o=>tintPart(o,key===mode&&i===j)));hooks.focus?.(mode,i);}
 function setIsolated(value){isolated=value;Object.entries(views).forEach(([k,g])=>g.visible=isolated&&k===mode&&k!=='chronograph');$('assemblyView').setAttribute('aria-pressed',!isolated);$('inspectionView').setAttribute('aria-pressed',isolated);hooks.presentation?.(mode,isolated);}
 // UI in the same workbench; all views share the same state.
 const panel=document.createElement('section');panel.id='advancedPanel';panel.innerHTML=`<div class="adv-heading"><div><span class="eyebrow">ADVANCED MOVEMENT · 08—12</span><h2>기본 시계에, 한 가지 기능씩.</h2></div><output id="advancedSummary">날짜 1 · 측정 00:00.0</output></div><div class="adv-tabs"><button data-advanced="none">완성 시계</button><button data-advanced="automatic">06 · 오토매틱</button><button data-advanced="calendar">07 · 날짜</button><button data-advanced="chronograph">08 · 크로노그래프</button></div><div class="adv-view-switch"><button id="assemblyView" aria-pressed="true">시계 안에서 연결 보기</button><button id="inspectionView" aria-pressed="false">연결부 확대 보기</button></div><h3 id="advancedFocusTitle"></h3><div id="advancedControls"></div><p id="advancedNote"></p><details><summary>모형의 범위와 원리 자료</summary><p>기본 무브먼트 위에 기능을 더한 교육용 자체 설계입니다. 확대 모형은 연결 원리를 읽기 위해 펼친 배치이며 특정 제조사의 완성 칼리버가 아닙니다. 접촉력·마찰·충돌을 계산하는 제작용 CAD는 아닙니다. 감기량과 관찰 속도는 교육용으로 확대했습니다.</p><a href="https://horopedia.org/automatic/" target="_blank" rel="noopener noreferrer">오토매틱 원리 ↗</a> · <a href="https://horopedia.org/date-2/" target="_blank" rel="noopener noreferrer">날짜 원리 ↗</a> · <a href="https://horopedia.org/chronograph/" target="_blank" rel="noopener noreferrer">크로노그래프 원리 ↗</a></details>`;document.querySelector('.workspace').prepend(panel);
 const autoExplainer=createAutoExplainer(panel),chronoExplainer=createChronoExplainer(panel,()=>{if(state.hammer>0)return;state.running=false;state.elapsed=77;resetPaused=false;state.resetChrono();},action=>{if(action==='pause')resetPaused=!resetPaused;else{resetPaused=true;state.animate(.4);}});
 const stageActions=document.createElement('div');stageActions.id='stageActions';document.querySelector('.stage').append(stageActions);
 const pusherTargets=pusherHeads.map((p,i)=>{const b=document.createElement('button');b.className='chrono-pusher-target';b.setAttribute('aria-label',i===1?'시작 정지 푸셔 · 클릭':'리셋 푸셔 · 클릭');b.title=i===1?'클릭 · 시작 / 정지':'클릭 · 정지 후 리셋';b.onclick=()=>{if(i===1)toggleChrono();else{resetPaused=false;state.resetChrono();}};document.querySelector('.stage').append(b);return b;});
 const notes={gmt:'시침 관 → 같은 크기의 중간 휠 → 같은 축의 작은 피니언 → 중앙 24시간 휠 순서입니다. 두 번 맞물려 원래 방향을 유지하고 절반 속도로 돕니다. 보라색 GMT 바늘은 24시간 눈금을 읽습니다. ±1시간 버튼은 독립 조정 칼라를 한 칸 옮기는 교육용 조작이며 실제 용두 전환 기구는 단순화했습니다. 날짜는 현지 시각을 따릅니다.',moon:'시침에서 24시간 회전을 만든 뒤, 핑거가 59치 달판을 하루 한 칸 넘깁니다. 같은 판에 달 두 개를 그려 놓아 반 바퀴인 29.5일마다 같은 모양이 돌아옵니다. 표시창 덮개를 열어 숨은 달을 보세요. 평균 삭망월 약 29.53059일과 차이가 있어 약 2.6년마다 하루 정도 보정이 필요한 기본형입니다. 천문력을 계산하는 오늘의 달 표시가 아닙니다.',none:'로터는 뒤쪽, 날짜창과 빨간 크로노그래프 바늘·누적계는 다이얼 쪽에 더했습니다. 초록 중앙 초침은 일반 시각, 빨간 중앙 바늘은 측정 시간입니다. 네 바늘을 비교하기 위한 교육 배치입니다.',automatic:'손목 운동 → 로터 → 방향 전환 장치 → 감속 기어 → 태엽 중심. 파란 위층은 입력 방향을 따라 돌고, 금색 아래층은 잠긴 클러치를 통해 한 방향으로만 돕니다. 다른 클러치는 공회전합니다. 완전히 감기면 슬리핑 브라이들이 미끄러지는 상태를 표현합니다. 로터 8회전 → 태엽 중심 1회전입니다. 감김 백분율은 교육용 저장량 표시입니다.',calendar:'파란 시침 휠은 12시간, 금색 구동 휠은 24시간에 한 바퀴입니다. 빨간 탄성 핑거가 날짜판 안쪽 톱니에 닿는 동안에만 판이 한 칸 움직이고, 초록 점퍼가 다음 틈에 들어가 고정합니다. 자정 관찰은 22시부터 01시까지를 느리게 보여줍니다. 핑거의 휨과 점퍼의 탄성 복귀는 접점이 보이도록 단순화했습니다. 단순 날짜이므로 31 다음은 1이며, 짧은 달은 직접 조정합니다.',chronograph:'다이얼 기준 오른쪽 위 푸셔는 시작·정지, 아래 푸셔는 리셋입니다. 3D 푸셔를 직접 클릭할 수 있습니다. 확대에도 반환 기어·축·다이얼 쪽 측정 바늘이 함께 표시됩니다. 드래그로 옆에서 축을 따라 보세요. 일반 시계는 계속 돕니다. 시작하면 컬럼 휠이 레버를 움직여 클러치를 연결하고, 정지하면 클러치를 떼고 브레이크로 측정 바늘을 잡습니다. 정지 후 리셋을 누르면 해머가 하트 캠을 밀어 영점으로 돌립니다. 아래층의 핑거는 측정 휠의 핑거가 한 바퀴마다 왼쪽 30치 인덱스 휠을 한 칸 밀고, 맞물린 오른쪽 휠이 분 누적계 바늘을 돌립니다. 리셋 때는 핑거를 들어 분 누적 휠에서 떼고, 초·분 축의 두 하트 캠을 각각 밀어 0으로 돌립니다. 이 장은 기본 시계에 크로노그래프만 연결합니다. 30분 누적계를 가진 2버튼 방식이며 플라이백은 없습니다.'};
 function controls(){stageActions.replaceChildren();const host=$('advancedControls');host.innerHTML=['gmt','moon'].includes(mode)?calendars.controls(mode):mode==='automatic'?`<button id="rotorLeft">↺ 반시계 한 바퀴</button><button id="rotorRight">↻ 시계 한 바퀴</button><button id="autoStep">접촉 한 단계</button><button id="autoPause">${autoPaused?"계속 관찰":"일시 정지"}</button><button id="autoSlow" aria-pressed="${autoSlow}">${autoSlow?"천천히 · ¼ 속도":"기본 속도"}</button><button id="wristToggle" aria-pressed="${wrist}">손목 운동 ${wrist?'정지':'시작'}</button><output id="autoReadout"></output>`:mode==='calendar'?`<button id="dateMidnight">자정 통과 관찰 · 22→01시</button><button id="dateStop">관찰 멈추기</button><button id="dateSafeTime">06:00으로 이동</button><label>관찰 날짜 <select id="datePreset">${Array.from({length:31},(_,i)=>i+1).map(n=>`<option value="${n}">${n}일</option>`).join('')}</select></label><button id="dateQuick">용두 한 칸 · 날짜 +1</button><output id="dateReadout"></output><output id="datePhase" aria-live="polite"></output>`:mode==='chronograph'?`<button id="chronoWind">태엽 25% 감기</button><button id="chronoToggle">측정 시작</button><button id="chronoReset">영점 복귀</button><button id="chronoSpeed">관찰 1× / 10× / 60×</button><button id="chronoMinuteDemo">58초부터 분 넘김 관찰</button><label><input type="checkbox" id="chronoXray"> 바늘까지 연결 경로 드러내기</label><output id="chronoReadout"></output>`:`<label><input type="checkbox" id="installedRotorToggle" checked> 로터 표시</label><button id="allWrist">손목 운동 ${wrist?'정지':'시작'}</button><button id="fullChrono">측정 시작 / 정지</button><button id="fullReset">영점 복귀</button>`;
 $('advancedNote').textContent=notes[mode];if($('rotorLeft')){const turn=direction=>{wrist=false;autoPaused=false;state.rotorDirection=direction;rotorQueue=direction*tau;};$('rotorLeft').onclick=()=>turn(1);$('rotorRight').onclick=()=>turn(-1);$('autoStep').onclick=()=>{wrist=false;autoPaused=false;rotorQueue=state.rotorDirection*Math.PI/48;};$('autoPause').onclick=()=>autoPaused=!autoPaused;$('autoSlow').onclick=()=>autoSlow=!autoSlow;$('wristToggle').onclick=()=>{wrist=!wrist;autoPaused=false;controls();};}
 if($('dateMidnight')){$('dateMidnight').onclick=()=>{hooks.midnight();state.lastClock=79200;};$('dateStop').onclick=()=>hooks.stopDemo();$('dateSafeTime').onclick=()=>{hooks.safeTime();state.lastClock=21600;};$('datePreset').value=String(state.date);$('datePreset').onchange=e=>state.setDate(+e.target.value);$('dateQuick').onclick=()=>{hooks.crown(1);hooks.turnCrown(1);};}
 calendars.bind(mode);
 if($('chronoToggle')){$('chronoWind').onclick=()=>hooks.wind();$('chronoToggle').onclick=()=>toggleChrono();$('chronoReset').onclick=()=>{resetPaused=false;state.resetChrono();};$('chronoSpeed').onclick=()=>hooks.speed();$('chronoMinuteDemo').onclick=()=>{if(state.hammer>0)return;if(hooks.environment().charge<=0)hooks.addWind(25);state.elapsed=58;if(!state.running)toggleChrono();else hooks.run();};}
 if($('installedRotorToggle')){$('installedRotorToggle').checked=showRotor;$('installedRotorToggle').onchange=e=>showRotor=e.target.checked;$('allWrist').onclick=()=>{wrist=!wrist;autoPaused=false;controls();};$('fullChrono').onclick=toggleChrono;$('fullReset').onclick=()=>state.resetChrono();}for(const source of host.querySelectorAll('button')){if(['chronoSpeed','dateSafeTime','allWrist','fullChrono','fullReset'].includes(source.id)&&mode==='none')continue;const b=document.createElement('button');b.dataset.source=source.id;b.textContent=source.textContent;b.onclick=()=>source.click();stageActions.append(b);}}
 $('assemblyView').onclick=()=>setIsolated(false);$('inspectionView').onclick=()=>setIsolated(true);
 let showRotor=true;function toggleChrono(){pusherPulse=.6;const env=hooks.environment();if(state.toggleChrono(env.charge>0,env.crown===2)&&state.running)hooks.run();}
 panel.querySelectorAll('[data-advanced]').forEach(b=>b.onclick=()=>hooks.view(b.dataset.advanced));
 function setView(v){mode=v;isolated=false;focus=0;Object.values(views).forEach(g=>g.visible=false);$('assemblyView').setAttribute('aria-pressed',true);$('inspectionView').setAttribute('aria-pressed',false);$('inspectionView').disabled=mode==='none';panel.querySelectorAll('[data-advanced]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.advanced===mode));controls();}
 for(const g of Object.values(views))g.children.forEach((o,i)=>{o.userData.restZ=o.position.z;o.userData.lift=(i%6)*.32;});
 function tick(dt,env){for(const [key,g] of Object.entries(views))g.children.forEach(o=>o.position.z=o.userData.restZ+(key==='chronograph'?0:(env.explosion||0)*o.userData.lift));pusherPulse=Math.max(0,pusherPulse-dt);state.animate(resetPaused&&state.hammer>0?0:dt);state.observeClock(env.seconds+env.offset);let delta=0;const autoDt=autoPaused?0:dt*(autoSlow?.25:1);if(wrist&&!env.explosion){const old=Math.sin(wristTime*2)*1.5;wristTime+=autoDt;delta+=Math.sin(wristTime*2)*1.5-old;}if(rotorQueue&&!env.explosion){const da=Math.sign(rotorQueue)*Math.min(Math.abs(rotorQueue),autoDt*tau);rotorQueue-=da;delta+=da;}if(delta){const gained=state.rotorMove(delta,hooks.environment().charge);hooks.addWind(gained);}
 panel.hidden=hooks.environment().chapter<5;assembly.visible=env.step>=4;for(let i=1;i<originals.length;i++){copies[i].rotation.copy(originals[i].rotation);copies[i].position.copy(originals[i].position);if(originals[i].isMesh){copies[i].material=originals[i].material;for(const k of ['label','advancedPart','focusIndex'])copies[i].userData[k]=originals[i].userData[k];}}installedTrain.visible=showRotor;barrelLink.visible=showRotor;installedRotor.visible=showRotor;installedRotor.rotation.z=autoRotor.rotation.z=state.rotor;rotorDrive.rotation.z=state.rotor;ai.rotation.z=state.rotor;ra.rotation.z=-state.rotor-Math.PI/16;rb.rotation.z=state.rotor;raOut.rotation.z=env.windAngle*8+(32*Math.atan2(-branchY,-.4)+11*Math.PI)/12;rbOut.rotation.z=env.windAngle*8+(32*Math.atan2(-branchY,.4)+11*Math.PI)/12;og.rotation.z=-env.windAngle*4.8;rg.rotation.z=env.windAngle*3-Math.PI/32;rp.rotation.z=env.windAngle*3;bg.rotation.z=-env.windAngle-Math.PI/24;
 const activeA=state.rotorDirection<0;const contactPoses=clutchCaps.map((cap,i)=>{const locked=i===0?activeA:!activeA,input=i===0?ra.rotation.z:rb.rotation.z,output=i===0?raOut.rotation.z:rbOut.rotation.z,pose=cap.contact.update(input,output,locked);cap.cage.rotation.z=input;cap.core.rotation.z=input+pose.phase;cap.pawl.rotation.z=pose.angle;cap.pawl.traverse(m=>{if(m.material?.color){m.material.color.setHex(locked?0xdf811d:0xe9ac61);m.material.emissive?.setHex(locked?0x7b3900:0);m.material.emissiveIntensity=locked?.25:0;}});return pose;});
 for(const [obj,on] of [[ra,activeA],[rb,!activeA],[raOut,activeA],[rbOut,!activeA]])obj.traverse(m=>{if(m.material?.emissive){m.material.emissive.setHex(on?0x985010:0);m.material.emissiveIntensity=on?.48:0;}});
 autoExplainer.update({visible:mode==='automatic',direction:state.rotorDirection,moving:Math.abs(delta)>1e-9,paused:autoPaused,rotor:state.rotor,output:env.windAngle,slipping:state.slipping,poses:contactPoses});

 const datePose=CalendarMechanics.datePose(env.seconds+env.offset,state.dateTurns);if(env.crownPosition===1){const p=env.correctionProgress||0;if(env.correctionBusy&&env.correctionDirection>0){dateShown=state.dateTurns-(p>=CalendarMechanics.dateCorrectionGeometry.endProgress?1:0)+CalendarMechanics.dateCorrectionPose(p);}else dateShown=state.dateTurns;}else dateShown=datePose.turns;dateRing.rotation.z=dateShown*tau/31;finger.scale.x=(datePose.length-.78)/.27;finger.position.x=(.78+datePose.length)/2; dateHour.rotation.z=-(env.seconds+env.offset)/43200*tau;dayWheel.rotation.z=(env.seconds+env.offset)/86400*tau-Math.PI/48;corrector.rotation.z=CalendarMechanics.dateCorrectionGeometry.angle-Math.PI-env.dateInputAngle*2/3;correctorArm.scale.x=env.dateReverse?.70:1;correctorArm.position.x=env.dateReverse?.21:.30;correctingTip.position.x=env.dateReverse?.42:.60;dateCrown.rotation.x=state.dateTurns*tau/4;const jumperLength=.28-.10*Math.sin((dateShown%1)*Math.PI);jumperTip.scale.x=jumperLength/.28;jumperTip.position.y=-jumperLength/2;
 if(lastDate!==state.date){lastDate=state.date;dateText.material.map.dispose();dateText.material.map=labelTexture(String(state.date));dateText.material.needsUpdate=true;if($('datePreset'))$('datePreset').value=String(state.date);}
 const secondReset=ChronoGeometry.resetPose((state.resetFrom%60)/60*tau,state.hammer),minuteReset=ChronoGeometry.resetPose(ChronoGeometry.minuteTurns(state.resetFrom)*tau,state.hammer),secondAngle=state.hammer>0?secondReset.angle:state.elapsed/60*tau,minuteAngle=state.hammer>0?minuteReset.angle:ChronoGeometry.minuteTurns(state.elapsed)*tau,shown=secondAngle/tau*60,c=state.counters;chronoHand.rotation.z=-secondAngle;counters[0].rotation.z=-minuteAngle;
 const targetTheta=state.running?0:.24;clutchTheta+=Math.sign(targetTheta-clutchTheta)*Math.min(Math.abs(targetTheta-clutchTheta),dt*1.2);const theta=clutchTheta,cp=ChronoGeometry.clutch(theta);clutch.position.set(...cp,0);lever.rotation.z=theta;
 const inputDelta=(env.seconds-lastInputSeconds)/60*tau;lastInputSeconds=env.seconds;chronoInputAngle+=inputDelta;if(state.running&&theta<.001)chronoInputAngle+=Math.atan2(Math.sin((secondAngle-4*Math.PI/22-chronoInputAngle)*22),Math.cos((secondAngle-4*Math.PI/22-chronoInputAngle)*22))/22;
 drive.rotation.z=chronoInputAngle;coupling.rotation.z=-chronoInputAngle*22/18+17*Math.PI/18+theta*40/18;output.rotation.z=secondAngle;column.rotation.z=-state.column*tau/16;
 brake.rotation.z=state.running||state.hammer>0?.16:0;hammer.position.y=state.hammer>0?secondReset.faceY:.72;minuteHammer.position.y=-1.65+(state.hammer>0?minuteReset.faceY:.72);const minuteIndexPhase=Math.atan2(-1.65,-.9)+Math.PI+Math.PI/30-.04;minuteNeedle.rotation.z=minuteHeart.rotation.z=minuteAngle;minuteIndex.rotation.z=minuteIndexPhase-minuteAngle;minuteStar.rotation.z=Math.PI-Math.PI/30-minuteIndexPhase+minuteAngle;
 minuteFinger.position.z=state.hammer>0?.06:-.14;fingerTip.position.z=state.hammer>0?.08:-.12;const startXY=mountedXY(-1.5,2.35-(pusherPulse>0?.15:0)),resetXY=mountedXY(2.2-(state.hammer>0?.15:0),-.4);pusherHeads[1].position.set(...startXY,.30);pusherHeads[0].position.set(...resetXY,.30);
 chronoExplainer.update({visible:mode==='chronograph',running:state.running,resetting:state.hammer>0,theta,inputAngle:chronoInputAngle,secondAngle,minuteAngle,secondReset,minuteReset,column:state.column,elapsed:state.elapsed,resetPaused});

 const exposeCorrection=env.crownMode||env.crownPosition===1;dateBack.material.transparent=exposeCorrection;dateBack.material.opacity=exposeCorrection?.22:1;dateBack.material.depthWrite=!exposeCorrection;dateMount.sync();dateMount.copy(dateHour).visible=dateMount.copy(dayAxis).visible=!env.crownMode;chronoMount.sync();
 const level=hooks.environment().chapter||0,autoOn=mode==='automatic',dateOn=mode==='calendar',chronoOn=mode==='chronograph';
 assembly.visible=env.step>=4&&autoOn&&!env.crownMode;const showCorrection=dateOn&&env.crownPosition===1||dateOn&&focus===3;dateMount.group.visible=dateOn||showCorrection;hourLink.visible=dateOn||showCorrection;dateLink.visible=showCorrection;dateInput.visible=['calendar','gmt','moon'].includes(mode)&&env.crownPosition===1||showCorrection;
 chronoMount.group.visible=secondsPickup.visible=measuredReturn.visible=chronoOutputLink.visible=measuredTube.visible=chronoPushers.visible=chronoOn;
 mainDate.visible=dateOn||showCorrection;chronoHand.visible=chronoOn;counters[0].parent.visible=chronoOn;counterShaft.visible=chronoOn;counterShaft.rotation.z=minuteAngle;
 installedRotor.visible=showRotor;installedRotor.traverse(m=>{if(m.isMesh){const ghost=mode==='automatic'&&focus>0;m.material.transparent=ghost;m.material.opacity=ghost?.12:1;m.material.depthWrite=!ghost;}});rotorDrive.visible=false;
 installedTrain.position.z=2.34+env.explosion*2;barrelLink.position.z=env.explosion;installedRotor.position.z=(chronoOn?4.05:2.65)+env.explosion*3;
 rotorInputShaft.visible=!chronoOn;rotorInputShaft.scale.y=chronoOn?5.7:1;rotorInputShaft.position.z=chronoOn?3.23:2.53;
 if(chronoOn&&mode==='chronograph')installedRotor.visible=false;
 dateMount.group.position.z=-.78-env.explosion*1.3;dateLink.position.z=-env.explosion*1.3;chronoMount.group.position.z=chronoZ+env.explosion*3;
 returnGears[0].rotation.z=returnGears[2].rotation.z=secondAngle;returnGears[1].rotation.z=-secondAngle-Math.PI/22;
 measuredReturn.position.z=chronoZ+.50+env.explosion*4.5;secondsPickup.position.z=env.explosion;chronoOutputLink.position.z=env.explosion*3;
 secondsPickup.rotation.z=env.seconds/60*tau;measuredTube.rotation.z=shown/60*tau;dateInputHead.rotation.z=-env.dateInputAngle*2/3;const datePhase=Math.atan2(dateEnd[1]-dateStart[1],dateEnd[0]-dateStart[0]);dateGears.forEach((g,i)=>g.rotation.z=(i%2?-1:1)*-env.dateInputAngle*2/3+(i%2?(36*datePhase+17*Math.PI)/18:0));dateCam.rotation.z=env.dateInputAngle*2/3;
 controlLinks.visible=chronoOn;const layerZ=chronoZ+env.explosion*3;
 function spanDisc(m,lo,hi){m.scale.y=(hi-lo)/m.geometry.parameters.height;m.position.z=(lo+hi)/2;}
 const returnZ=chronoZ+.50+env.explosion*4.5;spanDisc(measuredTube.children[0],face.position.z-.40,returnZ+.04);measuredTube.children[1].position.z=returnZ+.01;chronoOutputLink.position.z=0;spanDisc(chronoOutputLink.children[0],layerZ+.07,returnZ+.03);
 spanDisc(counterShaft.children[0],face.position.z-.13,layerZ+.10);
 secondsPickup.scale.z=(layerZ+1.4)/(chronoZ+1.4);secondsPickup.position.z=-1.33*(1-secondsPickup.scale.z);

 chronoPushers.position.z=layerZ;
 const colXY=mountedXY(-1.5,1.62),hp=mountedXY(1.30,hammer.position.y+.06),mp=mountedXY(1.30,minuteHammer.position.y+.06);
 const start=[pusherHeads[1].position.x,pusherHeads[1].position.y,layerZ+.30],reset=[pusherHeads[0].position.x,pusherHeads[0].position.y,layerZ+.30];
 const joint=mountedXY(1.30,-.40),j=[...joint,layerZ+.30];
 [[start,[...colXY,layerZ+.30]],[reset,j],[j,[...hp,layerZ+.30]],[j,[...mp,layerZ+.30]]].forEach(([a,b],i)=>positionLink(linkBars[i],a,b));
 chronoInspection.visible=isolated&&mode==='chronograph';inspectionFace.position.copy(face.position);
 for(const [a,b] of inspectionPairs)for(let i=0;i<a.length;i++){b[i].position.copy(a[i].position);b[i].quaternion.copy(a[i].quaternion);b[i].scale.copy(a[i].scale);b[i].visible=a[i].visible;if(a[i].isMesh){b[i].material=a[i].material;b[i].userData={...a[i].userData};}}
 for(let i=0;i<2;i++){let obj=pusherHeads[i];if(isolated){const pair=inspectionPairs.find(([a])=>a.includes(obj));if(pair)obj=pair[1][pair[0].indexOf(obj)];}const pt=hooks.project(obj),b=pusherTargets[i];b.hidden=!chronoOn||mode!=='chronograph'||!pt.visible;b.style.left=pt.x+'px';b.style.top=pt.y+'px';b.disabled=i===0?(state.running||state.hammer>0):(!state.running&&(hooks.environment().charge<=0||state.hammer>0));}
 dateInspection.visible=isolated&&mode==='calendar';if(mode==='calendar')views.calendar.visible=false;
 for(const {a,b} of correctionCopies)for(let i=0;i<a.length;i++){b[i].position.copy(a[i].position);b[i].quaternion.copy(a[i].quaternion);b[i].scale.copy(a[i].scale);b[i].visible=a[i].visible;if(a[i].isMesh){b[i].material=a[i].material;b[i].userData={...a[i].userData};}}
 calendars.tick(dt,env,mode,isolated,level);
 const correctionStatus=$('correctionStatus');if(correctionStatus){const active=['calendar','gmt','moon'].includes(mode)&&env.crownPosition===1;correctionStatus.hidden=!active;if(active){const p=env.correctionProgress||0,phase=!env.correctionBusy?'위치 선택 완료 · 앞뒤로 돌려 보세요':env.correctionDirection<0&&mode!=='gmt'?'역회전 · 핑거가 물러나 출력은 정지':p<.35?'① 용두와 전달 기어 회전':p<.65?'② 핑거가 출력 휠을 한 칸 이동':'③ 점퍼가 새 위치 고정 · 핑거 복귀';correctionStatus.textContent=phase+' — 용두 → 직각 조정축 → 파란 전달 기어 → '+({calendar:'31칸 날짜판',gmt:'24칸 독립 조정 휠 → GMT 바늘',moon:'59칸 조정 휠 → 달판'})[mode];}}

 panel.dataset.dateContact=JSON.stringify({shown:dateShown,angle:dateRing.rotation.z,engaged:datePose.engaged,progress:datePose.progress,dayAngle:dayWheel.rotation.z,fingerAngle:fingerCarrier.rotation.z,fingerLength:datePose.length,date:state.date});
 if(mechanismAudit.enabled)panel.dataset.copyAudit=JSON.stringify(mechanismAudit.copies([['automatic installed',originals,copies,1],...inspectionPairs.map(([a,b],i)=>['chrono inspection '+i,a,b]),...correctionCopies.map(({a,b},i)=>['correction inspection '+i,a,b])]));
 panel.dataset.chrono=JSON.stringify({isolated,running:state.running,elapsed:state.elapsed,hammer:state.hammer,clutch:theta,mountedAngle:chronoMount.copy(output).rotation.z,hand:chronoHand.rotation.z,returnAngles:returnGears.map(g=>g.rotation.z),minute:minuteAngle});
 if(mode!=='none'&&!env.crownMode)$('status').textContent=(isolated?'연결부 확대 · ':'기존 무브먼트에 장착 · ')+['입력 축','연결 전환','동력 전달','출력 / 복귀'][focus];
 uiTime+=dt;if(uiTime>.1){uiTime=0;stageActions.hidden=mode==='none';for(const b of stageActions.children){const source=$(b.dataset.source);if(source){b.textContent=source.textContent;b.disabled=source.disabled;}}const ms=Math.floor(state.elapsed*10),read=String(Math.floor(ms/600)).padStart(2,'0')+':'+String(Math.floor(ms/10)%60).padStart(2,'0')+'.'+ms%10;$('advancedSummary').textContent=({automatic:'자동 감기 · 태엽 '+Math.round(hooks.environment().charge)+'%',calendar:'날짜 '+state.date,gmt:'GMT · 24시간 바늘',moon:'문페이즈 · 59치 달판',chronograph:'측정 '+read})[mode]||'기본 시계';
 if($('autoPause')){$('autoPause').textContent=autoPaused?'계속 관찰':'일시 정지';$('autoPause').setAttribute('aria-pressed',autoPaused);$('autoSlow').textContent=autoSlow?'천천히 · ¼ 속도':'기본 속도';$('autoSlow').setAttribute('aria-pressed',autoSlow);$('wristToggle').textContent='손목 운동 '+(wrist?'정지':'시작');}if($('autoReadout'))$('autoReadout').textContent=`태엽 ${Math.round(hooks.environment().charge)}% · ${state.slipping?'완충 · 브라이들 미끄러짐':'양방향 입력 → 한 방향 감기'}`;
 if($('datePhase')){$('datePhase').textContent=env.crownPosition===1?'용두 보정 · 별도 핑거가 날짜판을 이동':datePose.engaged?'② 빨간 핑거가 날짜판을 미는 중 · '+Math.round(datePose.progress*100)+'%':'① 하루 휠 회전 · 핑거는 비접촉 / ③ 초록 점퍼가 날짜판 고정';$('dateStop').disabled=hooks.environment().demoRemaining<=0;}if($('dateReadout')){if(document.activeElement!==$('datePreset'))$('datePreset').value=String(state.date);$('dateReadout').textContent=`${state.date}일 · ${state.canQuickset()?'빠른 날짜 조정 가능':'21–03시 · 날짜 조정 잠금'}`;$('dateQuick').disabled=!state.canQuickset();}
 if($('chronoReadout')){const e=hooks.environment();$('chronoReadout').textContent=`${read} · ${state.running?(e.crown===2||e.charge<=0?'동력 정지 · 측정 대기':'클러치 연결 · 측정 중'):'클러치 분리 · 측정 정지'}`;$('chronoToggle').textContent=state.running?'측정 정지':'측정 시작 / 재개';$('chronoToggle').disabled=!state.running&&(e.charge<=0||e.crown===2||state.hammer>0);$('chronoReset').disabled=state.running||state.hammer>0;$('chronoSpeed').textContent='관찰 속도 '+e.rate+'×';}
 if($('fullReset'))$('fullReset').disabled=state.running;for(const b of stageActions.children){const source=$(b.dataset.source);if(source){b.textContent=source.textContent;b.disabled=source.disabled;}}}}
 const labels={automatic:[['손목 운동 · 로터',-2,1.3,.5],['두 방향을 한 방향으로',-.8,-.7,.3],['감속 → 태엽 중심',1.5,-.65,.1]],calendar:[['시침 축 · 12시간',0,-.55,.1],['24시간 바퀴 + 구동 핑거',1.3,.8,.25],['31칸 날짜판',-2.3,1.1,.3],['점퍼 · 한 칸 고정',3,-.5,.3],['용두 → 날짜 조정 레버',2.8,-1.9,.3]],chronograph:[['계속 도는 구동 휠',-2,-.8,.2],['이동하는 클러치',-1,.9,.2],['측정 휠 + 하트 캠',0,-.75,.3],['컬럼 휠 · 순서 제어',1.9,1.6,.3],['리셋 해머',.3,2,.4]]};
 setView('none');return {state,setView,tick,press(action){if(action==='toggle')toggleChrono();else{resetPaused=false;state.resetChrono();}},advance(dt){if(clutchTheta<.001)state.advance(dt);},pauseInput(){wrist=false;rotorQueue=0;autoPaused=false;},get mode(){return mode;},get isolated(){return isolated;},get xray(){return mode==='chronograph'&&!!$('chronoXray')?.checked||['gmt','moon'].includes(mode)&&!!$('calendarXray')?.checked;},setIsolated,setFocus,get labels(){if(isolated)return labels[mode]||[];if(mode==='automatic')return [['로터 중심 → 첫 감기 휠',0,0,2.7],['클러치 → 감속 기어',.2,.8,2.4],['출력축 → 기존 태엽 중심',...S.wheels.barrel.p,1.95]];if(mode==='calendar')return [['기존 시침 관 → 날짜 입력',0,0,-.85],['24시간 휠',1.15,0,-.95],['날짜판과 점퍼',2.2,.3,-1],['용두 선택 → 날짜 조정',2.5,1.15,-1.1]];if(mode==='chronograph')return [['기존 중앙 초침축 → 입력 휠',0,0,2.8],['클러치 → 측정 휠',...outputPoint,3],['위층 반환 기어 → 안쪽 측정 축',0,0,3.3],['컬럼 휠 · 조작 순서',1.1,-1.3,3.0]];return []; },reset(){state.reset();calendars.reset();wrist=false;rotorQueue=0;dateShown=0;autoPaused=false;resetPaused=false;},correctComplication:d=>calendars.correct(mode,d),quickDate:d=>state.quickDate(d)};
};
