/* Advanced educational modules. Functional geometry, not production calibre CAD. */
window.createAdvancedWatch=function(T,scene,root,face,S,hooks,toothShape){
 const $=id=>document.getElementById(id),tau=2*Math.PI,state=new WatchAdvancedState();let mode='none',isolated=false,focus=0,wrist=false,wristTime=0,rotorQueue=0,dateShown=0,lastDate=-1,lastWeekday=-1,uiTime=0,autoPaused=false,autoSlow=true;
 const assembly=new T.Group();root.add(assembly);const views={automatic:new T.Group(),calendar:new T.Group(),gmt:new T.Group(),moon:new T.Group(),chronograph:new T.Group()};Object.values(views).forEach(g=>{scene.add(g);g.visible=false;});
 const C={gold:0xc6a35c,blue:0x168ab4,green:0x19896c,red:0xd45451,steel:0x8596aa,pale:0xe4e9ed};
 function mat(c){return new T.MeshStandardMaterial({color:c,metalness:.35,roughness:.38,side:T.DoubleSide});}
 function mesh(geo,g,c){const m=new T.Mesh(geo,mat(c));g.add(m);return m;}
 function disc(r,h,g,c,z=0){const m=mesh(new T.CylinderGeometry(r,r,h,48),g,c);m.rotation.x=Math.PI/2;m.position.z=z;return m;}
 function bar(x1,y1,x2,y2,w,g,c,z=0,h=.06){const m=mesh(new T.BoxGeometry(Math.hypot(x2-x1,y2-y1),w,h),g,c);m.position.set((x1+x2)/2,(y1+y2)/2,z);m.rotation.z=Math.atan2(y2-y1,x2-x1);return m;}
 function ring(ro,ri,g,c,z=0,h=.08,start=0,end=tau){const a=new T.Shape();a.absarc(0,0,ro,start,end,false);a.lineTo(Math.cos(end)*ri,Math.sin(end)*ri);a.absarc(0,0,ri,end,start,true);a.closePath();const m=mesh(new T.ExtrudeGeometry(a,{depth:h,bevelEnabled:false,curveSegments:80}),g,c);m.position.z=z;return m;}
 function at(g,x,y,z=0){const a=new T.Group();a.position.set(x,y,z);g.add(a);return a;}
 function gear(n,r,g,c,z=0){const a=at(g,0,0,z),s=toothShape(n,r);const hole=new T.Path();hole.absarc(0,0,r*.68,0,tau,true);s.holes.push(hole);a.userData.gear={n,r,width:.07};mesh(new T.ExtrudeGeometry(s,{depth:.07,bevelEnabled:false}),a,c);ring(r*.19,r*.12,a,c);for(let i=0;i<4;i++){const t=i*tau/4;bar(Math.cos(t)*r*.15,Math.sin(t)*r*.15,Math.cos(t)*r*.72,Math.sin(t)*r*.72,.045,a,c,.035);}return a;}
 function labelTexture(txt,w=512,h=128){if(/^\d+$/.test(txt)||txt.length===1)w=128;const cv=document.createElement('canvas');cv.width=w;cv.height=h;const ctx=cv.getContext('2d');ctx.clearRect(0,0,w,h);ctx.fillStyle='#254357';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='600 96px sans-serif';ctx.fillText(txt,w/2,h/2);return new T.CanvasTexture(cv);}
 function text(txt,g,x,y,z,w=1,h=.25){const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map:labelTexture(txt),transparent:true,depthWrite:false,side:T.DoubleSide}));m.position.set(x,y,z);g.add(m);return m;}
 function needle(g,len,color,z=0,w=.04){const a=at(g,0,0,z);bar(0,-.15,0,len,w,a,color,0,.035);disc(w*1.7,.045,a,color);return a;}
 function rotor(g,r,z=0){const a=at(g,0,0,z);ring(r,r*.65,a,C.gold,0,.13,Math.PI*.08,Math.PI*.92);bar(-r*.87,0,r*.87,0,.14,a,C.steel,.04);bar(0,0,0,r*.78,.15,a,C.steel,.04);disc(.20,.15,a,C.steel,.08);return a;}
 // Read actual transformed geometry extents in the mechanism's own axial frame.
 function axialExtent(object,frame){frame.updateWorldMatrix(true,true);let lo=Infinity,hi=-Infinity;object.traverse(m=>{if(!m.geometry)return;if(!m.geometry.boundingBox)m.geometry.computeBoundingBox();const b=m.geometry.boundingBox;if(!b)return;for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z]){const p=frame.worldToLocal(m.localToWorld(new T.Vector3(x,y,z)));lo=Math.min(lo,p.z);hi=Math.max(hi,p.z);}});return [lo,hi];}
 // Full movement overlays: real energy store is shared with the base watch.
 const installedRotor=rotor(assembly,2.65,2.65);const rotorDrive=gear(16,.30,assembly,C.blue,2.60);
 const mainDate=at(face,2.23,0,.105);mesh(new T.BoxGeometry(.52,.37,.025),mainDate,C.pale);const dateText=text('1',mainDate,0,0,.03,.44,.23);
 const mainWeekday=at(face,1.58,0,.105);mesh(new T.BoxGeometry(.68,.37,.025),mainWeekday,C.pale);const weekdayText=text('월',mainWeekday,0,0,.03,.55,.23);
 // Automatic: two-way input with two one-way clutches, then common reduction/output.
 const au=views.automatic,ar=at(au,-2,0),autoRotor=rotor(ar,1.25,.42);const ai=gear(16,.4,ar,C.blue,.18);
 const branchY=Math.sqrt(.8*.8-.4*.4),revA=at(au,-1.2,0),revB=at(au,-.4,0),out=at(au,-.8,branchY),red=at(au,.5,branchY),barrel=at(au,1.3,branchY);
 const ra=gear(16,.4,revA,C.blue,.18),rb=gear(16,.4,revB,C.green,.18),raOut=gear(12,.3,revA,C.gold,-.18),rbOut=gear(12,.3,revB,C.gold,-.18),og=gear(20,.5,out,C.gold,-.18),rg=gear(32,.8,red,C.gold,-.18),rp=gear(8,.2,red,C.gold,-.53),bg=gear(24,.6,barrel,C.gold,-.53);
 for(const g of [revA,revB])disc(.07,.50,g,C.steel,.06);disc(.07,.43,red,C.steel,-.32);
 const clutchCaps=[];for(const r of [revA,revB]){const cage=at(r,0,0,.31);ring(.28,.19,cage,C.steel,0,.025);const pawl=at(cage,.232,0,.065);bar(0,0,RatchetContact.length*.002,0,.025,pawl,C.red);disc(.022,.04,pawl,C.steel,.02);const rs=new T.Shape();RatchetContact.points.forEach(([x,y],i)=>i?rs.lineTo(x*.002,y*.002):rs.moveTo(x*.002,y*.002));rs.closePath();const bore=new T.Path();bore.absarc(0,0,.075,0,tau,true);rs.holes.push(bore);const core=mesh(new T.ExtrudeGeometry(rs,{depth:.045,bevelEnabled:false}),r,C.gold);core.position.z=.37;clutchCaps.push({cage,pawl,core,contact:RatchetContact.create()});}
 disc(.5,.32,barrel,C.steel,-.78);bar(0,0,.34,0,.05,barrel,C.blue,-.52);
 // Install the same train over the base movement: input is coaxial with the rotor,
 // output is coaxial with the existing barrel arbor.
 const installedTrain=au.clone(true),endVector=[3.3,branchY],bp=S.wheels.barrel.p;
 const installScale=Math.hypot(...bp)/Math.hypot(...endVector),installAngle=Math.atan2(bp[1],bp[0])-Math.atan2(endVector[1],endVector[0]);
 installedTrain.scale.setScalar(installScale);installedTrain.rotation.z=installAngle;installedTrain.position.set(2*installScale*Math.cos(installAngle),2*installScale*Math.sin(installAngle),2.34);assembly.add(installedTrain);
 installedTrain.children[0].children[0].visible=false;const originals=[],copies=[];au.traverse(o=>originals.push(o));installedTrain.traverse(o=>copies.push(o));
 const barrelLink=at(assembly,...bp);disc(.045,.48,barrelLink,C.steel,1.95);const rotorInputShaft=disc(.045,.30,assembly,C.steel,2.53);
 // Date ring: hour wheel drives the 24-hour wheel; finger indexes the 31-position ring.
 const ca=views.calendar,dateRing=at(ca,0,0),dateHour=gear(24,.45,ca,C.blue,.02),dayAxis=at(ca,1.35,0),dayWheel=gear(48,.9,dayAxis,C.gold,.02);
 ring(2.85,2.38,dateRing,C.pale,.15,.07);for(let i=0;i<31;i++){const a=i*tau/31+CalendarMechanics.dateGeometry.toothPhase,b=bar(2.29*Math.cos(a),2.29*Math.sin(a),2.41*Math.cos(a),2.41*Math.sin(a),.08,dateRing,C.gold,.14);const numberAngle=-i*tau/31,t=text(String(i+1),dateRing,2.62*Math.cos(numberAngle),2.62*Math.sin(numberAngle),.24,.27,.23);t.rotation.z=numberAngle;}
 // Keep the printed face opaque; only its reverse is translucent during crown inspection.
 dateRing.children[0].material.side=T.FrontSide;const dateBack=dateRing.children[0].clone();dateBack.material=dateRing.children[0].material.clone();dateBack.material.side=T.BackSide;dateRing.add(dateBack);
 const fingerCarrier=at(dayWheel,0,0);fingerCarrier.rotation.z=Math.PI/48+CalendarMechanics.dateGeometry.end;const finger=bar(.78,0,1.05,0,.075,fingerCarrier,C.red,.15);const jumperAngle=CalendarMechanics.dateGeometry.toothPhase-7.5*tau/31,jumper=at(ca,2.05*Math.cos(jumperAngle),2.05*Math.sin(jumperAngle));jumper.rotation.z=jumperAngle+Math.PI/2;const jumperTip=bar(0,0,0,-.28,.045,jumper,C.green,.15);disc(.065,.07,jumper,C.steel,.15);
 const corrector=at(ca,...CalendarMechanics.dateCorrectionGeometry.pivot),correctorBase=bar(0,0,.30,0,.045,corrector,C.blue,.14),correctorHinge=at(corrector,.30,0),correctorArm=bar(0,0,.30,0,.045,correctorHinge,C.blue,.14);disc(.04,.05,correctorHinge,C.steel,.14);const correctingTip=mesh(new T.BoxGeometry(.08,.08,.10),correctorHinge,C.blue);correctingTip.position.set(.30,0,.14);const dateStem=bar(2.08/.85,-.68/.85,3.65,-1.35,.06,ca,C.steel,.3);const dateCrown=at(ca,3.65,-1.35,.3);mesh(new T.BoxGeometry(.24,.38,.22),dateCrown,C.steel);disc(.10,.07,corrector,C.blue,.10);ring(.37,.29,ca,C.steel,-.03);
 for(const [x1,y1,x2,y2] of [[2.40,-.20,2.84,-.20],[2.40,.20,2.84,.20],[2.40,-.20,2.40,.20],[2.84,-.20,2.84,.20]])bar(x1,y1,x2,y2,.025,ca,C.blue,.30,.025);
 const weekday=createWeekdayCalendar(T,ca,dayWheel,{at,disc,ring,bar,text,mesh,C});
 const chrono=createSeikoChronograph(T,scene,root,{at,disc,ring,bar,gear,needle,text,mesh,C},hooks);
 // Mounted modules retain the very same parts/angles as their enlarged inspection view.
 function mount(source,parent,scale,x,y,z,rotation=0){const g=source.clone(true);g.scale.setScalar(scale);g.position.set(x,y,z);g.rotation.z=rotation;parent.add(g);const a=[],b=[];source.traverse(o=>a.push(o));g.traverse(o=>b.push(o));return {group:g,sync(){for(let i=1;i<a.length;i++){b[i].position.copy(a[i].position);b[i].rotation.copy(a[i].rotation);b[i].scale.copy(a[i].scale);if(a[i].isMesh){b[i].material=a[i].material;for(const k of ['label','advancedPart','focusIndex'])b[i].userData[k]=a[i].userData[k];}}},copy(obj){return b[a.indexOf(obj)];}};}
 const dateMount=mount(ca,root,.85,0,0,-.78);dateMount.group.rotation.x=Math.PI;dateMount.copy(dateCrown).visible=false;dateMount.copy(dateStem).visible=false;
 const hourLink=at(root,0,0);ring(.105,.079,hourLink,C.blue,-.82,.22);
 // Crown-selected vertical arbor and an articulated correcting lever on the dial side.
 const dateInput=at(root,...S.keyless.date.p);disc(.035,2.78,dateInput,C.blue,.67);disc(.035,.23,dateInput,C.blue,-.825);
 const dateInputHead=at(dateInput,0,0,1.86);ring(.305,.225,dateInputHead,C.blue,0,.025);for(let i=0;i<18;i++){const t=i*tau/18,m=mesh(new T.BoxGeometry(.095,Math.PI*.27/18*.80,.09),dateInputHead,C.blue);m.position.set(.27*Math.cos(t),.27*Math.sin(t),.06);m.rotation.z=t;}
 const dateLink=at(root,0,0),dateEnd=CalendarMechanics.dateCorrectionGeometry.pivot.map((v,i)=>v*.85*(i?-1:1)),dateStart=S.keyless.date.p,dateR=Math.hypot(dateEnd[0]-dateStart[0],dateEnd[1]-dateStart[1])/6,dateGears=[];
 for(let i=0;i<4;i++){const ax=at(dateLink,dateStart[0]+(dateEnd[0]-dateStart[0])*i/3,dateStart[1]+(dateEnd[1]-dateStart[1])*i/3,-.72);dateGears.push(gear(18,dateR,ax,C.blue));disc(.035,.18,ax,C.steel,-.06);}
 const dateCam=at(dateLink,...dateEnd,-.84);const eccentric=disc(.085,.06,dateCam,C.red);eccentric.position.x=.075;
 const dateInspection=new T.Group();scene.add(dateInspection);dateInspection.visible=false;const correctionCopies=[];
 function copyCorrection(source,parent){const copy=source.clone(true);parent.add(copy);const a=[],b=[];source.traverse(o=>a.push(o));copy.traverse(o=>b.push(o));correctionCopies.push({a,b});}
 for(const source of [dateMount.group,hourLink,dateInput,dateLink,...hooks.correctionSources()])copyCorrection(source,dateInspection);
 for(const key of ['gmt','moon'])for(const source of [dateInput,...hooks.correctionSources()])copyCorrection(source,views[key]);
 for(const [id,a,b] of [['auto input-A',ai,ra],['auto A-B',ra,rb],['auto A-output',raOut,og],['auto B-output',rbOut,og],['auto output-reduction',og,rg],['auto reduction-barrel',rp,bg],['calendar hour-day',dateHour,dayWheel]])mechanismAudit.mesh(id,a,b);for(let i=1;i<4;i++)mechanismAudit.mesh('date correction '+i,dateGears[i-1],dateGears[i]);
 const calendars=createCalendarComplications(T,root,face,views,{at,gear,disc,ring,bar,needle,text,mesh,C},hooks);
 function tintPart(g,on){g.traverse(m=>{if(!m.isMesh||!m.material?.color)return;if(!m.userData.lessonMaterial){m.material=m.material.clone();m.userData.lessonMaterial=true;m.userData.lessonColor=m.material.color.clone();}m.material.color.copy(m.userData.lessonColor);m.material.emissive?.setHex(on?0x168ab4:0);if(m.material.emissive)m.material.emissiveIntensity=on?.32:0;});}
 const namesForFocus={gmt:['01 · 시침에서 받기','02 · 24시간으로 감속','03 · GMT 독립 조정','04 · 24시간 눈금 읽기'],moon:['01 · 하루에 한 번','02 · 59치 휠과 점퍼','03 · 달판과 표시창','04 · 근사 주기와 보정'],automatic:['01 · 로터가 입력을 만듭니다','02 · 두 클러치가 방향을 고릅니다','03 · 작은 피니언이 다음 큰 휠을 돌립니다','04 · 기존 태엽통의 중심 축을 감습니다'],calendar:['01 · 시침에서 하루 회전 만들기','02 · 바깥 날짜판 · 31칸','03 · 중앙 요일판 · 7칸','04 · 날짜 보정과 요일의 독립성'],chronograph:chrono.names.map((n,i)=>String(i+1).padStart(2,'0')+' · '+n)};
 const focusParts={...calendars.parts,automatic:[[autoRotor,ai],[ra,rb,raOut,rbOut],[og,rg,rp],[bg,barrel]],calendar:[[dateHour,dayWheel],[dateRing,jumper,fingerCarrier],[weekday.star,weekday.carrier,weekday.detent],[corrector,dateCrown]],chronograph:chrono.parts};

 function tag(g,label,chapter,index){g.traverse(m=>{if(m.isMesh)Object.assign(m.userData,{label,advancedPart:chapter,focusIndex:index});});}
 for(const [key,sets] of Object.entries(focusParts))sets.forEach((set,i)=>set.forEach(o=>tag(o,namesForFocus[key][i].replace(/^\d+ · /,''),key,i)));
 tag(installedRotor,'로터 · 손목 움직임에서 에너지','automatic',0);tag(barrelLink,'감속 기어에서 태엽 중심으로','automatic',3);tag(dateInput,'용두가 선택한 날짜 입력 축','calendar',3);tag(dateLink,'날짜 조정 기어열','calendar',3);tag(hourLink,'시침 관에서 날짜 구동으로','calendar',0);
 tag(revA,'A 클러치 · 로터의 첫 이웃 · 시계 입력에서 잠김','automatic',1);tag(revB,'B 클러치 · A의 다음 이웃 · 반시계 입력에서 잠김','automatic',1);
 function setFocus(i){focus=i;$('advancedFocusTitle').textContent=namesForFocus[mode]?.[i]||'';for(const [key,sets] of Object.entries(focusParts))sets.forEach((set,j)=>set.forEach(o=>tintPart(o,key===mode&&i===j)));hooks.focus?.(mode,i);}
 function setIsolated(value){isolated=value;Object.entries(views).forEach(([k,g])=>g.visible=isolated&&k===mode&&k!=='chronograph');$('assemblyView').setAttribute('aria-pressed',!isolated);$('inspectionView').setAttribute('aria-pressed',isolated);hooks.presentation?.(mode,isolated);}
 // UI in the same workbench; all views share the same state.
 const panel=document.createElement('section');panel.id='advancedPanel';panel.innerHTML=`<div class="adv-heading"><div><span class="eyebrow">ADVANCED MOVEMENT · 08—12</span><h2>기본 시계에, 한 가지 기능씩.</h2></div><output id="advancedSummary">날짜 1 · 측정 00:00.0</output></div><div class="adv-tabs"><button data-advanced="none">완성 시계</button><button data-advanced="automatic">06 · 오토매틱</button><button data-advanced="calendar">07 · 날짜</button><button data-advanced="chronograph">08 · 크로노그래프</button></div><div class="adv-view-switch"><button id="assemblyView" aria-pressed="true">시계 안에서 연결 보기</button><button id="inspectionView" aria-pressed="false">연결부 확대 보기</button></div><h3 id="advancedFocusTitle"></h3><div id="advancedControls"></div><p id="advancedNote"></p><details><summary>모형의 범위와 원리 자료</summary><p>기본 무브먼트 위에 기능을 더한 교육용 자체 설계입니다. 확대 모형은 연결 원리를 읽기 위해 펼친 배치이며 특정 제조사의 완성 칼리버가 아닙니다. 접촉력·마찰·충돌을 계산하는 제작용 CAD는 아닙니다. 감기량과 관찰 속도는 교육용으로 확대했습니다.</p><a href="https://horopedia.org/automatic/" target="_blank" rel="noopener noreferrer">오토매틱 원리 ↗</a> · <a href="https://horopedia.org/date-2/" target="_blank" rel="noopener noreferrer">날짜 원리 ↗</a> · <a href="https://horopedia.org/chronograph/" target="_blank" rel="noopener noreferrer">크로노그래프 원리 ↗</a></details>`;document.querySelector('.workspace').prepend(panel);
 const autoExplainer=createAutoExplainer(panel);chrono.attach(panel);
 const stageActions=document.createElement('div');stageActions.id='stageActions';document.querySelector('.stage').append(stageActions);
 const notes={gmt:'시침 관 → 같은 크기의 중간 휠 → 같은 축의 작은 피니언 → 중앙 24시간 휠 순서입니다. 두 번 맞물려 원래 방향을 유지하고 절반 속도로 돕니다. 보라색 GMT 바늘은 24시간 눈금을 읽습니다. ±1시간 버튼은 독립 조정 칼라를 한 칸 옮기는 교육용 조작이며 실제 용두 전환 기구는 단순화했습니다. 날짜는 현지 시각을 따릅니다.',moon:'시침에서 24시간 회전을 만든 뒤, 핑거가 59치 달판을 하루 한 칸 넘깁니다. 같은 판에 달 두 개를 그려 놓아 반 바퀴인 29.5일마다 같은 모양이 돌아옵니다. 표시창 덮개를 열어 숨은 달을 보세요. 평균 삭망월 약 29.53059일과 차이가 있어 약 2.6년마다 하루 정도 보정이 필요한 기본형입니다. 천문력을 계산하는 오늘의 달 표시가 아닙니다.',none:'로터는 뒤쪽, 날짜창과 빨간 크로노그래프 바늘·누적계는 다이얼 쪽에 더했습니다. 초록 중앙 초침은 일반 시각, 빨간 중앙 바늘은 측정 시간입니다. 네 바늘을 비교하기 위한 교육 배치입니다.',automatic:'손목 운동 → 로터 → 방향 전환 장치 → 감속 기어 → 태엽 중심. 파란 위층은 입력 방향을 따라 돌고, 금색 아래층은 잠긴 클러치를 통해 한 방향으로만 돕니다. 다른 클러치는 공회전합니다. 완전히 감기면 슬리핑 브라이들이 미끄러지는 상태를 표현합니다. 로터 8회전 → 태엽 중심 1회전입니다. 감김 백분율은 교육용 저장량 표시입니다.',calendar:'파란 시침 휠은 12시간, 금색 구동 휠은 24시간에 한 바퀴입니다. 빨간 구동 핑거가 날짜판 안쪽 톱니에 닿는 동안에만 판이 한 칸 움직이고, 초록 점퍼가 다음 틈에 들어가 고정합니다. 자정 관찰은 22시부터 01시까지를 느리게 보여줍니다. 빨간 핑거는 길이가 일정하며 하루 휠과 함께 회전해 톱니 구간을 통과합니다. 초록 점퍼는 고정된 축 주위로 회전하며 다음 틈에 복귀합니다. 보라색 핑거는 같은 하루 축의 다른 층에서 중앙 요일 별휠을 하루 한 칸 넘깁니다. 요일판은 별휠과 같은 관에 붙어 있고, 바깥 날짜판과는 독립적입니다. 31 다음은 1, 일요일 다음은 월요일입니다. 날짜만 보정해도 요일은 그대로입니다. 시작 요일 선택은 실물 조작이 아닌 관찰 초기값입니다. Seiko 6139A 도면의 두 핑거 구조를 참고했지만, 이 모형은 단일 언어 7칸·회전식 날짜 보정입니다. 실제 6139A의 이중 언어판·누름 깊이에 따른 날짜/요일 보정은 재현하지 않았습니다.',chronograph:'Seiko 6139A의 정비 도면을 기준으로 수직 클러치와 회전식 해머를 재구성했습니다. 녹색은 계속 도는 입력, 빨간색은 측정 초침축, 금색은 분 누적계입니다. 실제 부품의 연결은 유지하되 크기·간격은 교육용으로 확대했습니다. 아래 참조와 단면을 함께 살펴보세요.'};
 function controls(){stageActions.replaceChildren();const host=$('advancedControls');host.innerHTML=['gmt','moon'].includes(mode)?calendars.controls(mode):mode==='automatic'?`<button id="rotorLeft">↺ 반시계 한 바퀴</button><button id="rotorRight">↻ 시계 한 바퀴</button><button id="autoStep">접촉 한 단계</button><button id="autoPause">${autoPaused?"계속 관찰":"일시 정지"}</button><button id="autoSlow" aria-pressed="${autoSlow}">${autoSlow?"천천히 · ¼ 속도":"기본 속도"}</button><button id="wristToggle" aria-pressed="${wrist}">손목 운동 ${wrist?'정지':'시작'}</button><output id="autoReadout"></output>`:mode==='calendar'?`<button id="dateMidnight">자정 통과 관찰 · 22→01시</button><button id="dateStop">관찰 멈추기</button><button id="dateSafeTime">06:00으로 이동</button><label>관찰 날짜 <select id="datePreset">${Array.from({length:31},(_,i)=>i+1).map(n=>`<option value="${n}">${n}일</option>`).join('')}</select></label><label>관찰 시작 요일 <select id="weekdayPreset">${CalendarMechanics.weekdays.map((s,i)=>`<option value="${i}">${s}요일</option>`).join('')}</select></label><button id="dateWeek">7일 흐름 관찰</button><button id="dateQuick">용두 한 칸 · 날짜 +1</button><output id="dateReadout"></output><output id="datePhase" aria-live="polite"></output>`:mode==='chronograph'?`<button id="chronoWind">태엽 25% 감기</button><button id="chronoToggle">측정 시작</button><button id="chronoReset">영점 복귀</button><button id="chronoSpeed">관찰 1× / 10× / 60×</button><button id="chronoMinuteDemo">58초부터 분 넘김 관찰</button><label><input type="checkbox" id="chronoXray"> 바늘까지 연결 경로 드러내기</label><output id="chronoReadout"></output><label><input type="checkbox" id="chronoControlOnly"> 푸셔·제어 기구 집중 보기</label><output id="chronoActuation" aria-live="polite"></output>`:`<label><input type="checkbox" id="installedRotorToggle" checked> 로터 표시</label><button id="allWrist">손목 운동 ${wrist?'정지':'시작'}</button><button id="fullChrono">측정 시작 / 정지</button><button id="fullReset">영점 복귀</button>`;
 $('advancedNote').textContent=notes[mode];if($('rotorLeft')){const turn=direction=>{wrist=false;autoPaused=false;state.rotorDirection=direction;rotorQueue=direction*tau;};$('rotorLeft').onclick=()=>turn(1);$('rotorRight').onclick=()=>turn(-1);$('autoStep').onclick=()=>{wrist=false;autoPaused=false;rotorQueue=state.rotorDirection*Math.PI/48;};$('autoPause').onclick=()=>autoPaused=!autoPaused;$('autoSlow').onclick=()=>autoSlow=!autoSlow;$('wristToggle').onclick=()=>{wrist=!wrist;autoPaused=false;controls();};}
 if($('dateMidnight')){$('dateMidnight').onclick=()=>{hooks.midnight();state.lastClock=79200;};$('dateStop').onclick=()=>hooks.stopDemo();$('dateSafeTime').onclick=()=>{hooks.safeTime();state.lastClock=21600;};$('weekdayPreset').value=String(state.weekday);$('weekdayPreset').onchange=e=>state.setWeekday(+e.target.value);$('dateWeek').onclick=()=>hooks.advanceHours(168);$('datePreset').value=String(state.date);$('datePreset').onchange=e=>state.setDate(+e.target.value);$('dateQuick').onclick=()=>{hooks.crown(1);hooks.turnCrown(1);};}
 calendars.bind(mode);
 if($('chronoToggle')){$('chronoWind').onclick=()=>hooks.wind();$('chronoToggle').onclick=()=>toggleChrono();$('chronoReset').onclick=()=>chrono.press('reset');$('chronoSpeed').onclick=()=>hooks.speed();$('chronoMinuteDemo').onclick=()=>{if(chrono.ctrl.motion||chrono.ctrl.resetMotion)return;if(hooks.environment().charge<=0)hooks.addWind(25);chrono.ctrl.elapsed=58;if(!chrono.running)toggleChrono();else hooks.run();};}
 if($('installedRotorToggle')){$('installedRotorToggle').checked=showRotor;$('installedRotorToggle').onchange=e=>showRotor=e.target.checked;$('allWrist').onclick=()=>{wrist=!wrist;autoPaused=false;controls();};$('fullChrono').onclick=toggleChrono;$('fullReset').onclick=()=>chrono.press('reset');}for(const source of host.querySelectorAll('button')){if(['chronoSpeed','dateSafeTime','allWrist','fullChrono','fullReset'].includes(source.id)&&mode==='none')continue;const b=document.createElement('button');b.dataset.source=source.id;b.textContent=source.textContent;b.onclick=()=>source.click();stageActions.append(b);}}
 $('assemblyView').onclick=()=>setIsolated(false);$('inspectionView').onclick=()=>setIsolated(true);
 let showRotor=true;function toggleChrono(){chrono.press('toggle');}
 panel.querySelectorAll('[data-advanced]').forEach(b=>b.onclick=()=>hooks.view(b.dataset.advanced));
 function setView(v){mode=v;isolated=false;focus=0;Object.values(views).forEach(g=>g.visible=false);$('assemblyView').setAttribute('aria-pressed',true);$('inspectionView').setAttribute('aria-pressed',false);$('inspectionView').disabled=mode==='none';panel.querySelectorAll('[data-advanced]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.advanced===mode));controls();}
 for(const g of Object.values(views))g.children.forEach((o,i)=>{o.userData.restZ=o.position.z;o.userData.lift=(i%6)*.32;});
 function tick(dt,env){for(const [key,g] of Object.entries(views))g.children.forEach(o=>o.position.z=o.userData.restZ+(key==='chronograph'?0:(env.explosion||0)*o.userData.lift));state.animate(dt);state.observeClock(env.seconds+env.offset);let delta=0;const autoDt=autoPaused?0:dt*(autoSlow?.25:1);if(wrist&&!env.explosion){const old=Math.sin(wristTime*2)*1.5;wristTime+=autoDt;delta+=Math.sin(wristTime*2)*1.5-old;}if(rotorQueue&&!env.explosion){const da=Math.sign(rotorQueue)*Math.min(Math.abs(rotorQueue),autoDt*tau);rotorQueue-=da;delta+=da;}if(delta){const gained=state.rotorMove(delta,hooks.environment().charge);hooks.addWind(gained);}
 panel.hidden=hooks.environment().chapter<5;assembly.visible=env.step>=4;for(let i=1;i<originals.length;i++){copies[i].rotation.copy(originals[i].rotation);copies[i].position.copy(originals[i].position);if(originals[i].isMesh){copies[i].material=originals[i].material;for(const k of ['label','advancedPart','focusIndex'])copies[i].userData[k]=originals[i].userData[k];}}installedTrain.visible=showRotor;barrelLink.visible=showRotor;installedRotor.visible=showRotor;installedRotor.rotation.z=autoRotor.rotation.z=state.rotor;rotorDrive.rotation.z=state.rotor;ai.rotation.z=state.rotor;ra.rotation.z=-state.rotor-Math.PI/16;rb.rotation.z=state.rotor;raOut.rotation.z=env.windAngle*8+(32*Math.atan2(-branchY,-.4)+11*Math.PI)/12;rbOut.rotation.z=env.windAngle*8+(32*Math.atan2(-branchY,.4)+11*Math.PI)/12;og.rotation.z=-env.windAngle*4.8;rg.rotation.z=env.windAngle*3-Math.PI/32;rp.rotation.z=env.windAngle*3;bg.rotation.z=-env.windAngle-Math.PI/24;
 const activeA=state.rotorDirection<0;const contactPoses=clutchCaps.map((cap,i)=>{const locked=i===0?activeA:!activeA,input=i===0?ra.rotation.z:rb.rotation.z,output=i===0?raOut.rotation.z:rbOut.rotation.z,pose=cap.contact.update(input,output,locked);cap.cage.rotation.z=input;cap.core.rotation.z=input+pose.phase;cap.pawl.rotation.z=pose.angle;cap.pawl.traverse(m=>{if(m.material?.color){m.material.color.setHex(locked?0xdf811d:0xe9ac61);m.material.emissive?.setHex(locked?0x7b3900:0);m.material.emissiveIntensity=locked?.25:0;}});return pose;});
 for(const [obj,on] of [[ra,activeA],[rb,!activeA],[raOut,activeA],[rbOut,!activeA]])obj.traverse(m=>{if(m.material?.emissive){m.material.emissive.setHex(on?0x985010:0);m.material.emissiveIntensity=on?.48:0;}});
 autoExplainer.update({visible:mode==='automatic',direction:state.rotorDirection,moving:Math.abs(delta)>1e-9,paused:autoPaused,rotor:state.rotor,output:env.windAngle,slipping:state.slipping,poses:contactPoses});

 const datePose=CalendarMechanics.datePose(env.seconds+env.offset,state.dateTurns);if(env.crownPosition===1){const p=env.correctionProgress||0;if(env.correctionBusy&&env.correctionDirection>0){dateShown=state.dateTurns-(p>=CalendarMechanics.dateCorrectionGeometry.endProgress?1:0)+CalendarMechanics.dateCorrectionPose(p);}else dateShown=state.dateTurns;}else dateShown=datePose.turns;dateRing.rotation.z=dateShown*tau/31; dateHour.rotation.z=-(env.seconds+env.offset)/43200*tau;dayWheel.rotation.z=(env.seconds+env.offset)/86400*tau-Math.PI/48;corrector.rotation.z=CalendarMechanics.dateCorrectionGeometry.angle-Math.PI-env.dateInputAngle*2/3;correctorHinge.rotation.z=env.dateReverse?2.1:0;dateCrown.rotation.x=state.dateTurns*tau/4;jumper.rotation.z=jumperAngle+Math.PI/2+.85*Math.sin((dateShown%1)*Math.PI);
 const weekdayPose=weekday.tick(env.seconds+env.offset,state.weekdayTurns);
 if(lastWeekday!==state.weekday){lastWeekday=state.weekday;weekdayText.material.map.dispose();weekdayText.material.map=labelTexture(CalendarMechanics.weekdays[state.weekday]);weekdayText.material.needsUpdate=true;}
 if(lastDate!==state.date){lastDate=state.date;dateText.material.map.dispose();dateText.material.map=labelTexture(String(state.date));dateText.material.needsUpdate=true;if($('datePreset'))$('datePreset').value=String(state.date);}
 const chronoPose=chrono.tick(dt,env,mode==='chronograph',isolated);state.running=chrono.running;state.elapsed=chrono.elapsed;state.hammer=chronoPose.resetting?1:0;
 const exposeCorrection=env.crownMode||env.crownPosition===1;dateBack.material.transparent=exposeCorrection;dateBack.material.opacity=exposeCorrection?.22:1;dateBack.material.depthWrite=!exposeCorrection;dateMount.sync();dateMount.copy(dateHour).visible=dateMount.copy(dayAxis).visible=!env.crownMode;
 const level=hooks.environment().chapter||0,autoOn=mode==='automatic',dateOn=mode==='calendar',chronoOn=mode==='chronograph';
 assembly.visible=env.step>=4&&autoOn&&!env.crownMode;const showCorrection=dateOn&&env.crownPosition===1||dateOn&&focus===3;dateMount.group.visible=dateOn||showCorrection;hourLink.visible=dateOn||showCorrection;dateLink.visible=showCorrection;dateInput.visible=['calendar','gmt','moon'].includes(mode)&&env.crownPosition===1||showCorrection;
 mainDate.visible=mainWeekday.visible=dateOn||showCorrection;
 installedRotor.visible=showRotor;installedRotor.traverse(m=>{if(m.isMesh){const ghost=mode==='automatic'&&focus>0;m.material.transparent=ghost;m.material.opacity=ghost?.12:1;m.material.depthWrite=!ghost;}});rotorDrive.visible=false;
 installedTrain.position.z=2.34+env.explosion*2;barrelLink.position.z=env.explosion;installedRotor.position.z=(chronoOn?4.05:2.65)+env.explosion*3;
 rotorInputShaft.visible=!chronoOn;rotorInputShaft.scale.y=chronoOn?5.7:1;rotorInputShaft.position.z=chronoOn?3.23:2.53;
 if(chronoOn&&mode==='chronograph')installedRotor.visible=false;
 dateMount.group.position.z=-.78-env.explosion*1.3;dateLink.position.z=-env.explosion*1.3;
 dateInputHead.rotation.z=-env.dateInputAngle*2/3;const datePhase=Math.atan2(dateEnd[1]-dateStart[1],dateEnd[0]-dateStart[0]);dateGears.forEach((g,i)=>g.rotation.z=(i%2?-1:1)*-env.dateInputAngle*2/3+(i%2?(36*datePhase+17*Math.PI)/18:0));dateCam.rotation.z=env.dateInputAngle*2/3;
 dateInspection.visible=isolated&&mode==='calendar';if(mode==='calendar')views.calendar.visible=false;
 for(const {a,b} of correctionCopies)for(let i=0;i<a.length;i++){b[i].position.copy(a[i].position);b[i].quaternion.copy(a[i].quaternion);b[i].scale.copy(a[i].scale);b[i].visible=a[i].visible;if(a[i].isMesh){b[i].material=a[i].material;b[i].userData={...a[i].userData};}}
 calendars.tick(dt,env,mode,isolated,level);
 const correctionStatus=$('correctionStatus');if(correctionStatus){const active=['calendar','gmt','moon'].includes(mode)&&env.crownPosition===1;correctionStatus.hidden=!active;if(active){const p=env.correctionProgress||0,phase=!env.correctionBusy?'위치 선택 완료 · 앞뒤로 돌려 보세요':env.correctionDirection<0&&mode!=='gmt'?'역회전 · 핑거가 물러나 출력은 정지':p<.35?'① 용두와 전달 기어 회전':p<.65?'② 핑거가 출력 휠을 한 칸 이동':'③ 점퍼가 새 위치 고정 · 핑거 복귀';correctionStatus.textContent=phase+' — 용두 → 직각 조정축 → 파란 전달 기어 → '+({calendar:'31칸 날짜판',gmt:'24칸 독립 조정 휠 → GMT 바늘',moon:'59칸 조정 휠 → 달판'})[mode];}}

 if(mode==='calendar')panel.dataset.weekdayContact=JSON.stringify({...weekday.measure(),weekday:state.weekday,date:state.date});
 panel.dataset.dateContact=JSON.stringify({shown:dateShown,angle:dateRing.rotation.z,engaged:datePose.engaged,progress:datePose.progress,dayAngle:dayWheel.rotation.z,fingerAngle:fingerCarrier.rotation.z,fingerLength:datePose.length,rigidDimensions:{finger:[finger.scale.x,finger.scale.y,finger.scale.z],jumper:[jumperTip.scale.x,jumperTip.scale.y,jumperTip.scale.z]},date:state.date});
 if(mechanismAudit.enabled)panel.dataset.copyAudit=JSON.stringify(mechanismAudit.copies([['automatic installed',originals,copies,1],...correctionCopies.map(({a,b},i)=>['correction inspection '+i,a,b])]));
 if(mode!=='none'&&!env.crownMode)$('status').textContent=(isolated?'연결부 확대 · ':'기존 무브먼트에 장착 · ')+['입력 축','연결 전환','동력 전달','출력 / 복귀'][focus];
 uiTime+=dt;if(uiTime>.1){uiTime=0;stageActions.hidden=mode==='none';for(const b of stageActions.children){const source=$(b.dataset.source);if(source){b.textContent=source.textContent;b.disabled=source.disabled;}}const ms=Math.floor(state.elapsed*10),read=String(Math.floor(ms/600)).padStart(2,'0')+':'+String(Math.floor(ms/10)%60).padStart(2,'0')+'.'+ms%10;$('advancedSummary').textContent=({automatic:'자동 감기 · 태엽 '+Math.round(hooks.environment().charge)+'%',calendar:CalendarMechanics.weekdays[state.weekday]+'요일 · '+state.date+'일',gmt:'GMT · 24시간 바늘',moon:'문페이즈 · 59치 달판',chronograph:'측정 '+read})[mode]||'기본 시계';
 if($('autoPause')){$('autoPause').textContent=autoPaused?'계속 관찰':'일시 정지';$('autoPause').setAttribute('aria-pressed',autoPaused);$('autoSlow').textContent=autoSlow?'천천히 · ¼ 속도':'기본 속도';$('autoSlow').setAttribute('aria-pressed',autoSlow);$('wristToggle').textContent='손목 운동 '+(wrist?'정지':'시작');}if($('autoReadout'))$('autoReadout').textContent=`태엽 ${Math.round(hooks.environment().charge)}% · ${state.slipping?'완충 · 브라이들 미끄러짐':'양방향 입력 → 한 방향 감기'}`;
 if($('datePhase')){$('datePhase').textContent=env.crownPosition===1?'용두 보정 · 별도 핑거가 날짜판을 이동':datePose.engaged?'② 빨간 핑거가 날짜판을 미는 중 · '+Math.round(datePose.progress*100)+'%':weekdayPose.engaged?'보라색 핑거 → 요일 별휠 · '+Math.round(weekdayPose.progress*100)+'%':'하루 휠 회전 · 두 판은 각 점퍼가 고정';$('dateStop').disabled=hooks.environment().demoRemaining<=0;}if($('dateReadout')){if(document.activeElement!==$('datePreset'))$('datePreset').value=String(state.date);if(document.activeElement!==$('weekdayPreset'))$('weekdayPreset').value=String(state.weekday);$('dateReadout').textContent=`${CalendarMechanics.weekdays[state.weekday]}요일 · ${state.date}일 · ${state.canQuickset()?'빠른 날짜 조정 가능':'21–03시 · 날짜 조정 잠금'}`;$('dateQuick').disabled=!state.canQuickset();}
 if($('chronoActuation'))$('chronoActuation').textContent=chronoPose.phase;
 if($('chronoReadout')){const e=hooks.environment();$('chronoReadout').textContent=(chronoPose.resetting?'영점 복귀 중':read)+' · '+(chrono.running?'측정 중':'정지');$('chronoToggle').textContent=chrono.running?'측정 정지':'측정 시작 / 재개';$('chronoToggle').disabled=!!chrono.ctrl.motion||!!chrono.ctrl.resetMotion||(!chrono.running&&(e.charge<=0||e.crown===2));$('chronoReset').disabled=!!chrono.ctrl.motion||chrono.running||!!chrono.ctrl.resetMotion;$('chronoSpeed').textContent='측정 속도 '+e.rate+'×';}
 if($('fullReset'))$('fullReset').disabled=state.running;for(const b of stageActions.children){const source=$(b.dataset.source);if(source){b.textContent=source.textContent;b.disabled=source.disabled;}}}}
 const labels={automatic:[['손목 운동 · 로터',-2,1.3,.5],['두 방향을 한 방향으로',-.8,-.7,.3],['감속 → 태엽 중심',1.5,-.65,.1]],calendar:[['시침 축 · 12시간',0,-.55,.1],['24시간 바퀴 + 구동 핑거',1.3,.8,.25],['31칸 날짜판',-2.3,1.1,.3],['점퍼 · 한 칸 고정',3,-.5,.3],['용두 → 날짜 조정 레버',2.8,-1.9,.3]],chronograph:[]};
 setView('none');return {state,setView,tick,press(action){chrono.press(action);},advance(dt){chrono.advance(dt);},pauseInput(){wrist=false;rotorQueue=0;autoPaused=false;},get mode(){return mode;},get isolated(){return isolated;},get xray(){return mode==='chronograph'&&!!$('chronoXray')?.checked||['gmt','moon'].includes(mode)&&!!$('calendarXray')?.checked;},setIsolated,setFocus,get labels(){if(isolated)return labels[mode]||[];if(mode==='automatic')return [['로터 중심 → 첫 감기 휠',0,0,2.7],['클러치 → 감속 기어',.2,.8,2.4],['출력축 → 기존 태엽 중심',...S.wheels.barrel.p,1.95]];if(mode==='calendar')return [['기존 시침 관 → 날짜 입력',0,0,-.85],['24시간 휠',1.15,0,-.95],['날짜판과 점퍼',2.2,.3,-1],['용두 선택 → 날짜 조정',2.5,1.15,-1.1]];if(mode==='chronograph')return [];return []; },reset(){chrono.reset();state.reset();calendars.reset();wrist=false;rotorQueue=0;dateShown=0;autoPaused=false;},correctComplication:d=>calendars.correct(mode,d),quickDate:d=>state.quickDate(d)};
};
