(()=>{
 'use strict';
 const A=AutoMechanics,$=id=>document.getElementById(id),state=new A.State();
 const parts={pump:['펌프 임펠러','엔진과 컨버터 외장에 연결됩니다. 회전하는 날개가 ATF를 바깥쪽으로 보내 터빈에 운동량을 전달합니다. 터빈과 기계적으로 붙어 있지 않아 브레이크로 차를 잡아도 엔진이 돌 수 있습니다.'],turbine:['터빈 · 입력축','유체에 밀리는 날개입니다. 허브와 입력축은 함께 돌고 C1·C2의 입력 쪽으로 회전을 보냅니다. 펌프와 속도가 다른 상태가 슬립입니다.'],stator:['스테이터 · 원웨이 지지','터빈에서 돌아오는 유체 방향을 바꿉니다. 저속에서는 반력으로 원웨이 클러치가 잠기고, 속도가 비슷해지면 풀려 돌 수 있습니다. 이 모형은 유체 속도장과 내부 원웨이 접촉 형상을 계산하지 않습니다.'],lock:['록업 피스톤','터빈 측에 연결된 마찰판이 컨버터 전면 커버에 닿으면 유체를 우회하는 기계적 연결이 됩니다. 먼저 틈을 메우고, 접촉 후 슬립을 줄입니다. 비틀림 댐퍼 스프링은 생략했습니다.'],input:['터빈 입력축 · 클러치 드럼','엔진 쪽 컨버터 커버와 별개의 축입니다. C1과 C2의 한쪽 판을 돌리지만, 풀린 클러치의 반대쪽까지 강제로 돌리지는 않습니다.'],sun:['공통 선기어 · 속 빈 축','앞뒤 두 선기어가 하나의 속 빈 축에 고정됩니다. 안쪽 터빈 축과는 별도로 회전합니다. 1단에서는 입력과 반대 방향, 2단에서는 정지, 3단에서는 입력과 같은 속도로 회전합니다.'],front:['앞 링기어','C1이 붙으면 터빈 입력을 받습니다. 기어는 항상 유성기어와 맞물려 있고, 변속할 때 옆으로 이동하지 않습니다.'],planet:['유성기어 · 고정 길이 핀','자기 축에서 돌면서 캐리어와 함께 공전합니다. 앞뒤 세트의 선기어·링기어 사이에서 동시에 맞물립니다. 핀은 캐리어에 고정되고 기어만 핀 위에서 자유롭게 회전합니다.'],output:['앞 캐리어 + 뒤 링기어 · 출력','청록색 외측 드럼이 앞 캐리어와 뒤 링기어를 연결합니다. 이 둘은 언제나 같은 속도로 돌며 뒤쪽 출력축으로 회전을 보냅니다. 두 독립 출력이 아닙니다.'],rearCarrier:['뒤 캐리어','1단에서 F2가 뒤로 돌려는 반력을 막고, 2·3단에서는 앞으로 돌도록 허용합니다. 후진에서는 반력 방향이 달라 B3로 양방향 고정해야 합니다.'],C1:['C1 · 전진 클러치','입력 드럼의 판과 앞 링기어 드럼의 판이 번갈아 쌓입니다. 유압 피스톤이 틈을 닫고 누르면 마찰로 함께 회전합니다. 모든 전진 단수에서 붙어 있습니다.'],C2:['C2 · 직결 클러치','입력과 공통 선기어를 연결합니다. 3단에서는 C1도 붙어 선기어와 앞 링기어가 같은 속도로 돌고, 세트 전체가 하나처럼 회전합니다. 후진에서도 C2를 사용하지만 C1은 풉니다.'],B2:['B2 · 2단 브레이크','이름은 브레이크지만 도로 바퀴를 멈추는 장치는 아닙니다. F1의 바깥쪽을 변속기 케이스에 고정합니다. F1이 그 안에서 선기어의 역회전만 막으므로, 3단에서도 B2를 유지할 수 있습니다.'],B3:['B3 · 1단·후진 브레이크','뒤 캐리어를 케이스에 양방향 고정합니다. 여기서는 후진에서 작동합니다. 수동 저단의 엔진브레이크 용도는 범위에서 제외했습니다.'],F1:['F1 · 선기어 원웨이 클러치','B2와 직렬입니다. B2가 바깥쪽을 잡은 상태에서 선기어의 음의 회전만 막습니다. 2단은 잠금, 3단은 선기어가 양의 방향으로 돌아 공회전입니다. 내부 스프래그는 생략한 조립체입니다.'],F2:['F2 · 뒤 캐리어 원웨이 클러치','케이스와 뒤 캐리어 사이에 있습니다. 1단의 음의 반력을 막고, 2·3단에서 뒤 캐리어가 양의 방향으로 움직이면 풀립니다. 후진 고정 역할은 B3가 담당합니다.'],case:['케이스 · 고정 지지','유압 브레이크와 원웨이 클러치의 반력을 받습니다. 외장을 가독성을 위해 레일과 지지대로 줄였습니다. 축을 잡는 장치에는 회전하지 않는 반력 경로가 필요합니다.']};
 const lessons=[
  {title:'멈춰 있어도 엔진은 돌아갑니다',deck:'서로 닿지 않는 두 날개 사이로, 유체가 힘을 전달합니다.',intro:'수동변속기는 출발 전에 클러치를 떼었다 붙였습니다. 자동변속기의 토크컨버터에서는 엔진이 펌프를 돌리고, 유체가 터빈을 밀어 입력축을 돌립니다.',copy:[['먼저 차속 신호를 0으로','D · 차속 0에서 재생하세요. 엔진 쪽 금색 펌프는 회전하지만 청록 터빈과 기어 출력은 멈춥니다. 브레이크로 차량을 붙잡은 상태를 가정한 시험입니다. 출발 힘이 0이라는 뜻은 아닙니다.'],['스테이터가 반력을 받습니다','돌아오는 유체를 다시 펌프 회전에 유리한 방향으로 안내합니다. 유체가 스테이터를 반대로 밀 때 원웨이 지지가 잠깁니다. 펌프와 터빈 속도가 가까워지면 공회전할 수 있습니다.'],['록업은 직접 연결입니다','D에서 차속 70 이상, 페달 65% 미만으로 유지하면 3단 체결 후 록업이 진행됩니다. 커버와 마찰판 사이의 틈이 닫힌 다음 두 회전수가 같아집니다. 이 조건은 학습용이며 실차 맵이 아닙니다.']]},
  {title:'같은 기어에서 세 가지 속도',deck:'늘 맞물린 기어에서 입력·출력·고정점을 바꿉니다.',intro:'두 유성기어 세트가 파란 선기어 축을 공유합니다. 앞 캐리어와 뒤 링기어는 청록 드럼으로 묶여 하나의 출력을 만듭니다. 「앞 기어」「뒤 기어」는 같은 조립체의 카메라만 확대합니다.',copy:[['1단 · 두 세트가 함께 일합니다','C1으로 앞 링기어를 돌리고 F2로 뒤 캐리어의 반대 방향 반력을 잡습니다. 공통 선기어가 반대로 돌면서 앞 캐리어의 회전은 더 느려집니다. 느려진 대신 이상적인 기어 토크 배수가 커집니다.'],['2단 · 선기어를 붙잡습니다','B2가 F1의 바깥쪽을 잡으면 선기어의 역회전이 멎습니다. 앞 유성기어가 멈춘 선기어 주위를 굴러가며 캐리어를 돌립니다. 뒤 캐리어는 앞으로 움직일 수 있어 F2가 풀립니다.'],['3단 · 두 입력을 같은 속도로','C1은 링기어, C2는 선기어를 같은 입력축에 연결합니다. 유성기어의 상대 자전이 없어지고 전체가 함께 돕니다. 출력/입력은 1입니다. B2가 붙어 있어도 F1이 공회전하므로 묶여 버리지 않습니다.']]},
  {title:'유압이 마찰판을 붙이는 과정',deck:'명령 → 압력 공급 → 틈 메우기 → 마찰 → 동기화.',intro:'클러치는 두 회전체를 붙이고, 브레이크는 회전체를 케이스에 붙입니다. 왼쪽 클러치 확대에서 회전 주체가 다른 판이 번갈아 쌓인 모습을 보세요. 판 자체의 두께는 변하지 않습니다.',copy:[['피스톤이 움직여도 바로 직결되지는 않습니다','먼저 판 사이의 작은 틈을 메웁니다. 모두 닿은 뒤에는 마찰로 회전 차이가 줄고, 동기화가 끝나야 미끄럼 없는 연결로 취급할 수 있습니다. 주황 표시는 틈 메우기, 녹색 표시는 접촉 상태입니다.'],['압력 경로와 동력 경로를 구별하세요','아래 그림의 유압 지령은 어느 장치를 누를지 정합니다. 실제 회전력은 3D의 축·드럼·판·기어를 통과합니다. 그림은 기능도이며 실제 밸브 바디의 스풀 배치를 복제하지 않았습니다.'],['1→2→3에서 무엇이 달라지나요?','C1은 계속 유지됩니다. 2단에서 B2가 더해지고, 3단에서 C2가 더해집니다. F2와 F1은 회전 방향에 따라 차례로 공회전합니다. 원웨이 장치의 내부 롤러·스프래그 접촉은 이 단계에서는 표시하지 않습니다.']]},
  {title:'언제 다음 단수로 넘어갈까요?',deck:'차속과 페달 입력을 바꿔 변속 지령을 비교합니다.',intro:'D에서 차속 신호를 천천히 올리세요. 많이 가속하려는 상태에서는 더 높은 차속까지 낮은 단수를 유지합니다. 같은 경계에서 계속 오르내리지 않도록 올림과 내림 기준을 다르게 두었습니다.',copy:[['가속페달은 변속 판단에도 쓰입니다','페달을 더 밟으면 높은 회전력 요구로 보고 상향 변속 기준을 늦춥니다. 이 시험대는 차속과 페달을 외부 입력으로 제공하며 실제 차량 운동을 계산하지 않습니다.'],['변속 중에도 이빨은 맞물립니다','기어를 빼서 다른 쌍에 넣는 대신 마찰 장치와 원웨이 지지를 바꿉니다. 접촉 전에는 기존 회전 관계를 유지하고, 마찰 단계에서 새 회전 관계로 부드럽게 이동합니다.'],['관찰 속도와 차량 속도는 다릅니다','1×는 접촉을 볼 수 있는 느린 시계입니다. 차속 슬라이더는 제어 입력입니다. 표시한 입력축 기준 속도비·기어 토크 배수는 치수에서 계산하지만 컨버터 유체 토크·효율·열은 예측하지 않습니다.']]},
  {title:'중립과 후진도 연결의 조합',deck:'엔진을 거꾸로 돌리지 않고, 출력을 뒤집습니다.',intro:'먼저 차속 신호를 0으로 낮춰 N 또는 R을 선택하고 재생하세요. R 체결 후 차속 신호를 조금 올리면 역방향 출력이 나타납니다. 입력은 그대로 양의 방향입니다.',copy:[['N · 엔진과 출력 사이를 풉니다','C1·C2를 풀어 유성기어로 전달되는 입력 경로를 끊습니다. 실제 중립의 오일 끌림과 출력 관성은 생략했습니다. 이 시험대에서는 구동되지 않는 기어를 정지 상태로 둡니다.'],['R · 선기어 입력, 뒤 캐리어 고정','C2로 선기어를 돌리고 B3로 뒤 캐리어를 잡습니다. 제자리에서 도는 뒤 유성기어가 안쪽 이빨의 링기어를 반대 방향으로 밀어 출력을 뒤집습니다. C1은 풀려 있어 앞 링기어는 자유롭게 돌 수 있습니다.'],['왜 F2만으로 후진을 잡을 수 없을까요?','후진에서는 뒤 캐리어에 걸리는 반력 방향이 1단과 다릅니다. 한쪽 방향만 막는 F2 대신 양방향으로 잡는 B3가 필요합니다. P의 주차 폴과 수동 저단 엔진브레이크는 별도 범위로 남겼습니다.']]}
 ];
 let lesson=0,model,q,target,radius=17,last=0,lastUI=0,renderer,camera,selected='pump';
 const n=(v,d=2)=>Number(v).toLocaleString('ko-KR',{maximumFractionDigits:d});
 function tab(part){$('autoFlow').hidden=part;$('autoPartPanel').hidden=!part;$('autoPrinciple').setAttribute('aria-pressed',!part);$('autoParts').setAttribute('aria-pressed',part);}
 function select(k){if(!parts[k])return;selected=k;model?.select(k);$('autoPartTitle').textContent=parts[k][0];$('autoPartText').textContent=parts[k][1];document.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.part===k));}
 function chapter(i,push=true){lesson=i;const l=lessons[i];$('autoEyebrow').textContent=`심화 01 · 탐구 ${i+1} / 5`;$('autoTitle').textContent=l.title;$('autoDeck').textContent=l.deck;$('autoIntro').textContent=l.intro;$('autoCopy').innerHTML=l.copy.map(([h,p])=>`<h3>${h}</h3><p>${p}</p>`).join('');document.querySelectorAll('[data-lesson]').forEach(b=>b.setAttribute('aria-current',+b.dataset.lesson===i?'step':'false'));$('autoNext').textContent=i===4?'내연기관 챕터 맵 →':'다음 · '+lessons[i+1].title;tab(false);const u=new URL(location.href);u.searchParams.set('lesson',i+1);if(push)history.pushState(null,'',u);document.title=l.title+' — 자동변속기 | Mechanism Unfolded';updateUI();}
 lessons.forEach((l,i)=>{const b=document.createElement('button');b.dataset.lesson=i;b.innerHTML=`<b>0${i+1}</b><span>${l.title}</span>`;b.onclick=()=>chapter(i);$('autoNav').append(b);});
 Object.entries(parts).forEach(([k,v])=>{const b=document.createElement('button');b.dataset.part=k;b.textContent=v[0];b.onclick=()=>select(k);$('autoPartButtons').append(b);});
 $('autoPrinciple').onclick=()=>tab(false);$('autoParts').onclick=()=>tab(true);$('autoNext').onclick=()=>lesson===4?location.assign('car.html#roadmap'):chapter(lesson+1);
 $('autoPlay').onclick=()=>{state.running=!state.running;updateUI();};$('autoRate').onchange=e=>state.rate=+e.target.value;
 $('autoStep').onclick=()=>{const rate=state.rate;state.running=true;state.rate=1;state.tick(.05);state.tick(.05);state.running=false;state.rate=rate;model?.update(state.snapshot());updateUI();};
 $('autoSpeed').oninput=e=>{state.speed=+e.target.value;state.choose();updateUI();};$('autoPedal').oninput=e=>{state.pedal=+e.target.value;state.choose();updateUI();};
 document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{state.setSelector(b.dataset.range);updateUI();});
 function diagram(){const active=k=>state.apply[k]>.99?'flow-active':'',positions={C1:35,C2:115,B2:195,B3:275};
  if(lesson===0)return `<svg viewBox="0 0 320 175" role="img" aria-label="펌프에서 터빈과 스테이터를 지나는 유체 순환과 록업"><path class="flow-line flow-active" d="M45 66C80 10 220 10 266 66M266 90C220 150 80 150 45 90"/><path d="M246 55l20 11-3-22M64 102L45 90l2 22" fill="none" stroke="#bb9454" stroke-width="3"/><rect class="flow-node" x="16" y="55" width="73" height="38" rx="6"/><rect class="flow-node" x="230" y="55" width="73" height="38" rx="6"/><rect class="flow-node" x="117" y="112" width="90" height="30" rx="6"/><text x="28" y="78">펌프 · 엔진</text><text x="240" y="78">터빈 · 입력</text><text x="132" y="131">스테이터</text><text x="108" y="82">${state.lock>.99?'록업 · 직접 연결':'ATF 운동량 전달'}</text><text class="tiny" x="16" y="164">유체 순환 개념도 · 실제 유속/토크 증폭 계산 아님</text></svg>`;
  return `<svg viewBox="0 0 320 218" role="img" aria-label="유압 지령과 클러치 및 브레이크 연결"><rect class="flow-node" x="92" y="10" width="136" height="32" rx="5"/><text x="106" y="30">유압 제어 · 선택 ${state.target}단</text><path class="flow-line" d="M160 42V63H35M160 63H275"/>${Object.entries(positions).map(([k,x])=>`<path class="flow-line ${active(k)}" d="M${x} 63V93"/><rect class="flow-node" x="${x-25}" y="93" width="50" height="32" rx="4"/><text x="${x-9}" y="114">${k}</text><text class="tiny" x="${x-27}" y="143">${n(state.apply[k]*100,0)}% 체결</text>`).join('')}<text class="tiny" x="10" y="166">C1 → 앞 링   C2 → 공통 선기어</text><text class="tiny" x="10" y="183">B2 → F1 → 선기어   B3 → 뒤 캐리어</text><text class="tiny" x="10" y="204">기능도 · 비율은 피스톤 틈 메우기, 압력 실측값 아님</text></svg>`;
 }
 function updateUI(){const s=state.snapshot();$('autoPlay').textContent=s.running?'Ⅱ 일시 정지':'▶ 움직임 재생';$('autoPlay').setAttribute('aria-pressed',s.running);$('autoSpeedValue').textContent=s.speed+' km/h';$('autoSpeed').disabled=!!s.transition&&(s.transition.from==='R'||s.transition.to==='R');$('autoPedalValue').textContent=s.pedal+'%';$('autoStatus').textContent=s.message+(s.transition&&!s.running?' · 재생 또는 0.1초 진행으로 체결을 관찰하세요.':'');$('autoPhase').textContent=`${s.selector} · ${s.transition?s.gear+' → '+s.target:s.gear} · ${s.phase}`;document.querySelectorAll('[data-range]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.range===s.selector);b.disabled=!!s.transition;});
  $('autoDevices').innerHTML=['C1','C2','B2','B3','F1','F2'].map(k=>{const f1=k==='F1',f2=k==='F2',on=f1?s.apply.B2>.99&&Math.abs(s.velocity.sun)<1e-5&&s.gear!=='N':f2?s.gear==='1'&&Math.abs(s.velocity.rearCarrier)<1e-5:s.apply[k]>.99,fill=!!s.apply[k]&&!on,text=f1?(s.apply.B2<.99?'지지 해제':on?'잠금':'공회전'):f2?(on?'잠금':'공회전'):on?'접촉':fill?'틈 메우기':'해제';return `<span class="${on?'on':fill?'filling':''}">${k} · ${text}</span>`;}).join('');
  const ratio=A.ratios[s.gear],rows=lesson===0?[['펌프 대비 터빈 속도',n(s.coupling*100,0)+'%'],['록업',s.lock===1?'직접 연결':s.lock>0?'접촉 진행':'해제'],['스테이터',s.coupling>.85?'공회전 영역':'반력 지지 영역'],['관찰 입력','차속 '+s.speed]]:[['현재 / 목표 단수',s.gear+' / '+s.target],['출력 / 터빈 입력',s.transition?'변속 중':n(ratio,3)+'×'],['이상적 기어 토크 배수',ratio&&!s.transition?n(1/Math.abs(ratio),2)+'×':'—'],['공통 선기어 방향',s.velocity.sun<-.0001?'입력과 반대':s.velocity.sun>.0001?'입력과 같은 방향':'정지']];
  $('autoMetrics').innerHTML=rows.map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');$('autoDiagram').innerHTML=diagram();if(renderer){renderer.domElement.dataset.state=JSON.stringify({...s,lesson:lesson+1,camera:{q:q.toArray(),target:target.toArray(),radius}});if(new URL(location.href).searchParams.has('audit'))renderer.domElement.dataset.audit=JSON.stringify(model.audit());}
 }
 chapter(Math.max(0,Math.min(4,(+new URL(location.href).searchParams.get('lesson')||1)-1)),false);select('pump');window.onpopstate=()=>chapter(Math.max(0,Math.min(4,(+new URL(location.href).searchParams.get('lesson')||1)-1)),false);
 if(!window.THREE){$('autoLoading').textContent='3D 라이브러리를 불러오지 못했습니다. 연결을 확인하고 다시 열어 주세요.';return;}
 const T=THREE,viewport=$('autoViewport'),scene=new T.Scene();renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;viewport.append(renderer.domElement);renderer.domElement.setAttribute('role','img');renderer.domElement.setAttribute('aria-label','조작 가능한 자동변속기 3D 조립체');camera=new T.PerspectiveCamera(38,1,.05,120);q=new T.Quaternion().setFromEuler(new T.Euler(-.24,1.1,0,'YXZ'));target=new T.Vector3(0,0,0);scene.add(new T.HemisphereLight(0xffffff,0x62736c,2.5));for(const [x,y,z] of [[5,9,8],[-7,4,-7]]){const light=new T.DirectionalLight(0xffffff,2);light.position.set(x,y,z);scene.add(light);}model=createAutomaticModel(T);scene.add(model.root);model.update(state.snapshot());model.select(selected);$('autoLoading').hidden=true;
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const key=b.dataset.view;target.set(0,0,key==='converter'?-4:key==='front'?0:key==='rear'?2.25:key==='clutch'?-1.7:0);radius=key==='all'?17:key==='converter'?6.4:key==='clutch'?5.8:6.4;q.setFromEuler(new T.Euler(-.24,key==='clutch'||key==='converter'?1.3:1.1,0,'YXZ'));updateUI();});
 let drag=null;const ray=new T.Raycaster(),mouse=new T.Vector2(),label=$('autoHover');
 function hit(e){const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);return ray.intersectObjects(model.pickable)[0];}
 function sphere(x,y){const r=renderer.domElement.getBoundingClientRect(),size=Math.min(r.width,r.height),v=new T.Vector3((2*(x-r.left)-r.width)/size,(r.height-2*(y-r.top))/size,0),n=v.x*v.x+v.y*v.y;if(n<=1)v.z=Math.sqrt(1-n);else v.normalize();return v;}
 renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,id:e.pointerId};renderer.domElement.setPointerCapture(e.pointerId);label.hidden=true;});
 renderer.domElement.addEventListener('pointermove',e=>{if(drag){if(e.shiftKey){const scale=radius*.65/viewport.clientHeight;target.addScaledVector(new T.Vector3(1,0,0).applyQuaternion(q),-(e.clientX-drag.x)*scale);target.addScaledVector(new T.Vector3(0,1,0).applyQuaternion(q),(e.clientY-drag.y)*scale);}else q.multiply(new T.Quaternion().setFromUnitVectors(sphere(e.clientX,e.clientY),sphere(drag.x,drag.y))).normalize();drag.x=e.clientX;drag.y=e.clientY;}else{const h=hit(e);label.hidden=!h;if(h){label.textContent=parts[h.object.userData.part]?.[0]||'';const r=document.querySelector('.stage').getBoundingClientRect();label.style.left=Math.max(6,Math.min(r.width-190,e.clientX-r.left+10))+'px';label.style.top=e.clientY-r.top+12+'px';}}});
 renderer.domElement.addEventListener('pointerup',e=>{if(!drag)return;const click=Math.hypot(e.clientX-drag.sx,e.clientY-drag.sy)<5;drag=null;if(click){const h=hit(e);if(h){select(h.object.userData.part);tab(true);}}renderer.domElement.releasePointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointercancel',()=>drag=null);renderer.domElement.addEventListener('pointerleave',()=>label.hidden=true);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();radius=A.clamp(radius*Math.exp(e.deltaY*.001),2,30);},{passive:false});
 const resize=()=>{renderer.setSize(viewport.clientWidth,viewport.clientHeight,false);camera.aspect=viewport.clientWidth/viewport.clientHeight;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(viewport);resize();document.addEventListener('visibilitychange',()=>{if(document.hidden)state.running=false;last=0;});
 function frame(now){const dt=last?(now-last)/1000:0;last=now;state.tick(dt);model.update(state.snapshot());camera.position.copy(new T.Vector3(0,0,radius*Math.max(1,1/camera.aspect)).applyQuaternion(q).add(target));camera.up.copy(new T.Vector3(0,1,0).applyQuaternion(q));camera.lookAt(target);renderer.render(scene,camera);if(now-lastUI>100){updateUI();lastUI=now;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
})();
