/* Enlarged coaxial teaching model; clearances and lengths are exaggerated for visibility. */
window.createCoaxDemo=function(T,scene,S,toothShape){
 const scale=2.7,cs=S.centralSeconds,cp=cs.p.map(p=>[p[0]*scale,-p[1]*scale]),cr=cs.r*scale,cz=-2.4,fwz=-1.55;
 const group=new T.Group();scene.add(group);group.visible=false;const tau=Math.PI*2,parts={minute:new T.Group(),hour:new T.Group(),middle:new T.Group(),second:new T.Group()};Object.values(parts).forEach(g=>group.add(g));parts.middle.position.x=1.728;
 const colors={minute:0x098dc7,hour:0xc89137,middle:0x697b94,second:0x19856c,fourth:0xc8a05b,third:0xa67740},materials={};for(const k in colors)materials[k]=new T.MeshStandardMaterial({color:colors[k],metalness:.24,roughness:.46,side:T.DoubleSide});
 function mesh(geometry,parent,key){const m=new T.Mesh(geometry,materials[key]);m.userData.label=({minute:'분침 관 · 센터 축에서 전달',hour:'시침 관 · 12배 감속',middle:'분침–시침 사이의 전달 기어',second:'중앙 초침축과 전달 기어',fourth:'4번 휠 · 초침의 동력 원천',third:'3번 휠 · 큰 휠이 4번 피니언을 구동'})[key];parent.add(m);return m;}
 function tube(ro,ri,z,height,parent,key,cut=false){const s=new T.Shape();if(cut){s.absarc(0,0,ro,Math.PI,2*Math.PI,false);s.lineTo(ri,0);s.absarc(0,0,ri,2*Math.PI,Math.PI,true);s.closePath();}else{s.absarc(0,0,ro,0,tau,false);if(ri){const h=new T.Path();h.absarc(0,0,ri,0,tau,true);s.holes.push(h);}}const m=mesh(new T.ExtrudeGeometry(s,{depth:height,bevelEnabled:false,curveSegments:64}),parent,key);m.position.z=z;return m;}
 function gear(n,r,z,parent,key){const s=toothShape(n,r);const hole=new T.Path();hole.absarc(0,0,r*.58,0,tau,true);s.holes.push(hole);const m=mesh(new T.ExtrudeGeometry(s,{depth:.09,bevelEnabled:false}),parent,key);m.position.z=z;m.userData.gear={n,r,width:.09};const bore=key==='minute'?.105:key==='hour'?.23:0,hub=Math.max(r*.2,bore+.04);for(let i=0;i<4;i++){const a=i*Math.PI/2,len=r*.82-hub,bar=mesh(new T.BoxGeometry(len,.055,.09),parent,key);bar.position.set(Math.cos(a)*(hub+len/2),Math.sin(a)*(hub+len/2),z+.045);bar.rotation.z=a;}tube(hub,bore,z,.09,parent,key);return m;}
 const cannonGear=gear(12,.432,-.9,parts.minute,'minute');const minuteLarge=new T.Group();parts.middle.add(minuteLarge);minuteLarge.rotation.z=-35*Math.PI/36;const minuteGear=gear(36,1.296,-.9,minuteLarge,'middle');const minutePin=gear(10,.3456,-.5,parts.middle,'middle');const hourGear=new T.Group();parts.hour.add(hourGear);hourGear.rotation.z=-89*Math.PI/40;const hourOut=gear(40,1.3824,-.5,hourGear,'hour');
 tube(.19,.105,-.9,2.65,parts.minute,'minute',true);tube(.065,0,cz,2.3-cz,parts.second,'second');const centralGear=gear(cs.n,cr,cz,parts.second,'second');tube(.32,.23,-.5,1.65,parts.hour,'hour',true);tube(.12,.065,-.9,.7,parts.middle,'middle');
 function hand(parent,len,w,z,key){const s=new T.Shape();s.moveTo(-w/2,-.22);s.lineTo(-w/2,len*.77);s.lineTo(0,len);s.lineTo(w/2,len*.77);s.lineTo(w/2,-.22);s.closePath();const m=mesh(new T.ExtrudeGeometry(s,{depth:.045,bevelEnabled:false}),parent,key);m.position.z=z;tube(w,0,z,.055,parent,key);}
 const secondsHand=new T.Group();parts.second.add(secondsHand);hand(secondsHand,2.48,.055,2.32,'second');hand(parts.minute,2.15,.13,1.77,'minute');hand(parts.hour,1.35,.20,1.17,'hour');
 const secondsInput=new T.Group(),secondsIdler=new T.Group();group.add(secondsInput,secondsIdler);secondsInput.position.set(...cp[0],0);secondsIdler.position.set(...cp[1],0);const takeoff=gear(cs.n,cr,cz,secondsInput,'second');const idler=gear(cs.n,cr,cz,secondsIdler,'second');
 // The fourth wheel and the added take-off wheel are rigidly fixed to this same arbor.
 gear(S.wheels.fourth.n,S.wheels.fourth.r*scale,fwz,secondsInput,'fourth');const fourthPin=gear(S.wheels.fourth.pn,S.wheels.fourth.pr*scale,fwz+.35,secondsInput,'fourth');tube(.075,0,cz-.05,fwz+.6-cz,secondsInput,'second');
 // Same pitch centers and ratio as the whole movement, mirrored to the dial side.
 const thirdInput=new T.Group();group.add(thirdInput);
 thirdInput.position.set(S.wheels.third.p[0]*scale,-S.wheels.third.p[1]*scale,0);
 const thirdZ=fwz+.35;
 const thirdGear=gear(S.wheels.third.n,S.wheels.third.r*scale,thirdZ,thirdInput,'third');
 gear(S.wheels.third.pn,S.wheels.third.pr*scale,thirdZ+.35,thirdInput,'third');
 tube(.065,0,thirdZ-.12,.68,thirdInput,'third');
 const phi34=Math.atan2(secondsInput.position.y-thirdInput.position.y,secondsInput.position.x-thirdInput.position.x);
 const thirdPhase=((S.wheels.third.n+S.wheels.fourth.pn)*phi34+S.wheels.fourth.pn*Math.PI-Math.PI)/S.wheels.third.n;
 for(const [id,a,b] of [['coax minute input',cannonGear,minuteGear],['coax hour reduction',minutePin,hourOut],['coax third-fourth',thirdGear,fourthPin],['coax seconds 1',takeoff,idler],['coax seconds 2',idler,centralGear]])mechanismAudit.mesh(id,a,b);
 // Physical gearing phase: external teeth alternate at the pitch contact.
 parts.middle.rotation.z=0;const middleBase=parts.middle.rotation.z;
 const phases=[0,0,0];for(let i=1;i<3;i++){const phi=Math.atan2(cs.p[i][1]-cs.p[i-1][1],cs.p[i][0]-cs.p[i-1][0]);phases[i]=2*phi+Math.PI-Math.PI/cs.n-phases[i-1];}
 const handLabels=[['초록 중심 축 → 초침',-.3,0,2.45],['파란 안쪽 관 → 분침',-.35,.15,1.85],['금색 바깥 관 → 시침',-.75,.05,1.05],['옆 축: 큰 바퀴와 작은 바퀴가 함께 회전',1.75,0,-.2]];
 const secondsLabels=[['3번 큰 휠 → 4번 작은 피니언',thirdInput.position.x,thirdInput.position.y,thirdZ+.2],['① 4번 휠 · 같은 축',cp[0][0]-1,cp[0][1]-.5,fwz],['② 전달 기어',cp[0][0]-.45,cp[0][1]+.45,cz],['③ 중간 기어',cp[1][0]+.5,cp[1][1]+.35,cz],['④ 중앙을 관통하는 초침축',0,-.18,.55],['⑤ 초침까지 같은 회전',0,0,2.45]];let focus='both';
 return {group,get labels(){return focus==='second'?secondsLabels:[...handLabels,['3번 휠 → 4번 피니언',thirdInput.position.x,thirdInput.position.y,thirdZ],['4번 휠 · 전달 기어와 같은 축',cp[0][0]-1,cp[0][1],fwz]];},setFocus(key){focus=key;for(const k in materials){const active=key==='both'||key===k||(key==='hour'&&k==='middle')||(key==='second'&&['third','fourth'].includes(k));materials[k].color.setHex(colors[k]);materials[k].emissive.setHex(active?colors[k]:0);materials[k].emissiveIntensity=active?.12:0;materials[k].transparent=!active;materials[k].opacity=active?1:.13;materials[k].depthWrite=active;}},update(seconds,offset=0){secondsHand.rotation.z=phases[2];const sa=-seconds/60*tau;parts.second.rotation.z=-phases[2]+sa;secondsInput.rotation.z=sa;thirdInput.rotation.z=thirdPhase-sa*S.wheels.fourth.pn/S.wheels.third.n;secondsIdler.rotation.z=-phases[1]-sa;const a=-(seconds+offset)/3600*tau;parts.minute.rotation.z=a;parts.hour.rotation.z=a/12;parts.middle.rotation.z=middleBase-a/3;}};
};
