(function(){'use strict';
const $=id=>document.getElementById(id),D=EVData,state={phase:0,running:false,rate:1,pedal:45,rpm:1800,series:96,parallel:2};
const requested=Number(new URL(location.href).searchParams.get('chapter')||1),chapter=requested>=1&&requested<=3&&Number.isInteger(requested)?requested:1,L=D.lessons[chapter-1];
const names={battery:'배터리 팩',inverter:'인버터',motor:'모터 · 고정자와 회전자',gear:'두 단계 감속기',wheel:'차동장치 · 바퀴'};
const descriptions={battery:'화학 에너지를 전기로 내보냅니다. 주황색 두 선은 DC 회로의 양극과 음극입니다. 빛 입자는 에너지 전달의 개념 표시이며 전자의 실제 속도가 아닙니다.',inverter:'배터리 DC를 모터에 필요한 U·V·W 세 상의 전류로 바꿉니다. 세 선으로 고정자 코일에 연결됩니다. 실제 스위칭 소자와 코일 결선의 세부는 생략했습니다.',motor:'바깥 코일은 고정되고 안쪽 자석과 축이 회전합니다. 빨강은 N극, 파랑은 S극, 청록 화살표는 합성 자기장입니다. 회전자와 고정자 사이에는 접촉하지 않는 공극이 있습니다.',gear:'금색 첫 기어 쌍과 청록색 두 번째 쌍은 서로 다른 축 방향 층에 있습니다. 가운데 은색 축이 큰 기어와 작은 기어를 강체로 연결합니다. 정면에서는 층이 겹치므로 비스듬히 보기로 확인하세요.',wheel:'청록색 큰 기어가 차동 케이스를 돌립니다. 내부 차동 기어는 생략한 직진 모형으로, 양쪽 출력축과 바퀴가 같은 속도로 돕니다. 코너에서 좌우 속도가 달라지는 작동은 여기서 시뮬레이션하지 않습니다.'};
$('title').textContent=L?D.titles[chapter-1]:D.titles[0];document.title=$('title').textContent+' — 전기차 · Mechanism Unfolded';$('number').textContent=`ELECTRIC VEHICLE / BASIC ${String(chapter).padStart(2,'0')}`;
for(const k of ['intro','question','try','body','formula','detail'])$(k).textContent=L[k];$('steps').innerHTML=L.steps.map(x=>`<li>${x}</li>`).join('');
$('nav').innerHTML=D.titles.map((t,i)=>`${i===0?'<small>기본편 · 01–07</small>':i===7?'<small>심화편 · 08–12</small>':''}${i<3?`<a href="ev.html?chapter=${i+1}" ${i+1===chapter?'aria-current="page"':''}>${String(i+1).padStart(2,'0')} ${t}</a>`:`<span class="pending">${String(i+1).padStart(2,'0')} ${t} · 준비 중</span>`}`).join('');
$('mapCards').innerHTML=D.titles.map((t,i)=>i<3?`<a href="ev.html?chapter=${i+1}"><small>기본 ${i+1} / 탐구하기 ↗</small><strong>${t}</strong></a>`:`<article><small>${i<7?'기본':'심화'} ${i+1} / 준비 중</small><strong>${t}</strong></article>`).join('');
$('prev').href=chapter===1?'./':'ev.html?chapter='+(chapter-1);$('prev').textContent=chapter===1?'← 이야기 목록':'← '+D.titles[chapter-2];$('next').href=chapter===3?'#map':'ev.html?chapter='+(chapter+1);$('next').textContent=chapter===3?'다음 챕터 계획 보기 ↘':D.titles[chapter]+' →';
if(requested!==chapter){const u=new URL(location.href);u.searchParams.set('chapter','1');history.replaceState(null,'',u);}
$('seriesLabel').hidden=$('parallelLabel').hidden=chapter!==1;
let selected=chapter===1?'battery':chapter===2?'motor':'gear';
function select(id){selected=id;$('partName').textContent=names[id];$('partText').textContent=descriptions[id];document.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.part===id)));if(model)model.highlight(id);}
$('parts').innerHTML=Object.entries(names).map(([k,v])=>`<button data-part="${k}">${v}</button>`).join('');
let renderer,model;try{if(!window.THREE)throw Error('3D 라이브러리를 불러오지 못했습니다.');renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch(e){$('viewport').textContent='3D를 시작할 수 없습니다. WebGL 지원과 네트워크 연결을 확인한 뒤 새로고침해 주세요.';return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xeaf0e6,1);$('viewport').appendChild(renderer.domElement);const scene=new THREE.Scene();scene.add(new THREE.HemisphereLight(0xffffff,0x75806b,2.3));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-5,8,12);scene.add(light);model=EVModel.create(THREE);scene.add(model.group);
const camera=new THREE.PerspectiveCamera(38,1,.1,150),target=new THREE.Vector3(0,-.7,0);let yaw=-.55,pitch=.22,distance=17;
function view(name){if(name==='motor'){target.set(-3,1,-1.3);distance=7;yaw=Math.PI+.3;pitch=.13;}else if(name==='gear'){target.set(.6,1,.5);distance=16;yaw=0;pitch=0;}else if(name==='oblique'){target.set(.6,1,.5);distance=18;yaw=.62;pitch=.28;}else{target.set(0,-.7,0);distance=17;yaw=-.55;pitch=.22;}$('mode').textContent={whole:'전체 연결',motor:'모터 확대',gear:'기어 정면',oblique:'두 층과 연결축'}[name];document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>select(b.dataset.part));select(selected);view('whole');
function metrics(){const m=D.calculate(state);$('pedalOut').textContent=state.pedal+'%';$('rpmOut').textContent=state.rpm.toLocaleString()+' rpm';let values=chapter===1?[[m.voltage.toFixed(1)+' V','팩 전압'],[m.capacity.toFixed(1)+' kWh','저장 에너지 · 명목'],[m.dc.toFixed(1)+' kW','배터리 공급 전력'],[m.current.toFixed(1)+' A','DC 회로 전류']]:chapter===2?[[m.torque.toFixed(0)+' N·m','모터 토크'],[m.power.toFixed(1)+' kW','모터 기계 출력'],[(m.power*1.36).toFixed(0)+' PS','같은 출력을 마력으로'],[m.current.toFixed(1)+' A','배터리 DC 전류']]:[[m.wheelRPM.toFixed(0)+' rpm','바퀴 회전수'],[m.wheelTorque.toFixed(0)+' N·m','양쪽 바퀴 총 토크'],[m.speed.toFixed(1)+' km/h','미끄럼 없는 환산 속도'],[(m.power*.96).toFixed(1)+' kW','바퀴 기계 출력']];$('metrics').innerHTML=values.map(([v,k])=>`<div class="metric"><strong>${v}</strong><small>${k}</small></div>`).join('');}
for(const id of ['pedal','rpm','series','parallel','rate'])$(id).addEventListener('input',()=>{state[id]=Number($(id).value);metrics();});
function play(){state.running=!state.running;$('play').textContent=state.running?'Ⅱ 일시정지':'▶ 재생';$('play').setAttribute('aria-pressed',String(state.running));}$('play').onclick=play;$('step').onclick=()=>{if(state.running)play();state.phase+=Math.PI/18;};
const canvas=renderer.domElement,ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let drag=null;
function hit(e){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const h=ray.intersectObject(model.group,true).find(x=>x.object.userData.part);return h?.object.userData.part;}
canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(drag){yaw-=(e.clientX-drag.x)*.008;pitch+=(e.clientY-drag.y)*.008;drag.x=e.clientX;drag.y=e.clientY;$('tip').hidden=true;}else{const id=hit(e);$('tip').hidden=!id;if(id)$('tip').textContent=names[id];}};canvas.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<5){const id=hit(e);if(id)select(id);}drag=null;};canvas.onpointercancel=()=>drag=null;canvas.onpointerleave=()=>{$('tip').hidden=true;};canvas.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(4,Math.min(40,distance*Math.exp(e.deltaY*.001)));},{passive:false});$('viewport').onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();yaw+=e.key==='ArrowLeft'?.12:e.key==='ArrowRight'?-.12:0;pitch+=e.key==='ArrowUp'?.12:e.key==='ArrowDown'?-.12:0;}};
const resize=()=>{const r=$('viewport').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.zoom=Math.min(1,camera.aspect/1.35);camera.updateProjectionMatrix();};new ResizeObserver(resize).observe($('viewport'));resize();metrics();let last=performance.now(),count=0;
function frame(now){const dt=(now-last)/1000;last=now;D.advance(state,dt);const currentFraction=D.calculate(state).torque/180;model.update(state.phase,currentFraction*100);const q=new THREE.Quaternion().setFromEuler(new THREE.Euler(pitch,yaw,0,'YXZ'));camera.position.copy(new THREE.Vector3(0,0,distance).applyQuaternion(q).add(target));camera.up.copy(new THREE.Vector3(0,1,0).applyQuaternion(q));camera.lookAt(target);renderer.render(scene,camera);if(count++%4===0){$('phaseBars').hidden=chapter!==2;if(chapter===2)$('phaseBars').innerHTML='<small>U · V · W 위상 전류 (정규화) · 중심에서 좌/우 = −/＋</small>'+[0,1,2].map((i)=>{const v=-currentFraction*Math.sin(state.phase-i*2*Math.PI/3);return `<div class="phase-row"><span>${['U','V','W'][i]} ${v.toFixed(1)}</span><div class="phase-track"><i style="left:${v<0?50+v*50:50}%;width:${Math.abs(v)*50}%;background:${['#c27a46','#648faf','#9375a5'][i]}"></i></div></div>`;}).join('');$('diagnostics').textContent='렌더링된 기어 중심: '+model.diagnostics().map(g=>g.center.map(n=>n.toFixed(2)).join(',')).join(' / ')+` · 회전자 위상 ${state.phase.toFixed(4)} rad · ${state.running?'재생':'정지'} · 감속 3 × 3 = 9. 직선축 연결 및 맞물림 수치 검증, 전체 충돌·열·전자기 해석은 아님.`;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
})();
