(()=>{'use strict';
const $=id=>document.getElementById(id),D=Firearms,clock=new D.Clock();let mechanics=true,chapter=0,compare=false,kind='flint',renderer,scene,camera,objects=[],yaw=.25,pitch=.18,distance=8.4,last=0,lastPhase=-1;
const requested=Number(new URL(location.href).searchParams.get('chapter'));chapter=Number.isInteger(requested)&&requested>=1&&requested<=4?requested-1:0;
D.chapters.forEach((c,i)=>{const b=document.createElement('button');b.dataset.chapter=i+1;b.innerHTML=`${String(i+1).padStart(2,'0')} · ${c.kind}<small>${c.title}</small>`;b.onclick=()=>select(i);$('chapters').append(b);});
const mapLink=document.createElement('a');mapLink.href='#map';mapLink.textContent='다음 이야기 · 전체 12장 ↘';$('chapters').append(mapLink);
$('roadmap').innerHTML=D.roadmap.map(([t,k],i)=>`<article class="${i<4?'':'future'}"><span class="eyebrow">${String(i+1).padStart(2,'0')} / ${i<4?'공개':'예정'}</span><h3>${t}</h3><p>${k}</p>${i<4?`<a href="firearms.html?chapter=${i+1}">이 장 탐구하기 ↗</a>`:'<p>후속 제작 예정</p>'}</article>`).join('');
function sync(){const c=mechanics?FirearmPrinciples.lessons[chapter]:D.chapters[chapter];$('play').textContent=clock.running?'일시 정지':'원리 흐름 재생';$('play').setAttribute('aria-pressed',clock.running);for(const [i,b] of [...$('steps').children].entries())b.setAttribute('aria-pressed',clock.phase===i);$('explanation').textContent=(c.explain||c.text)[clock.phase];$('viewport').dataset.state=JSON.stringify({chapter:chapter+1,time:clock.time,phase:clock.phase,running:clock.running,compare,kind,camera:[yaw,pitch,distance],model:mechanics?'classroom-principle':'static-exterior-concept'});$('scrub').value=clock.time;concept();highlight();}
function select(i,push=true){chapter=i;clock.time=0;clock.running=false;lastPhase=-1;const c=D.chapters[i];document.title=`${i+1}. ${c.kind} — 총기의 변천사 | Mechanism Unfolded`;for(const key of ['intro','history','gain','limit','observe','question'])$(key).textContent=c[key];if(mechanics)$('observe').textContent='원리 흐름을 재생하거나 관찰 위치 슬라이더를 움직여 접촉 전후를 비교하세요. 이 모형은 해당 시대의 점화에 관련된 일반 원리를 분리한 것으로, 총 내부의 부품 연결을 뜻하지 않습니다.';$('materials').innerHTML=`<h3>${c.materials[0]}</h3><p>${c.materials[1]}</p><a href="${c.materials[2]}" target="_blank" rel="noreferrer">${c.materials[3]} ↗</a>`;$('era').textContent=`${String(i+1).padStart(2,'0')} / ${c.era}`;$('title').textContent=c.title;$('variants').hidden=i!==2;document.querySelector('[data-kind=wheel]').textContent=mechanics?'바퀴 마찰':'휠록';document.querySelector('[data-kind=flint]').textContent=mechanics?'직선 마찰':'플린트록';$('compare').disabled=i===0;if(i===0)compare=false;$('compare').setAttribute('aria-pressed',compare);$('compare').textContent=compare?'현재 방식만 보기':'이전 방식과 비교';$('comparison').hidden=!compare;$('comparison').textContent=c.comparison;$('sources').innerHTML=`<a target="_blank" rel="noreferrer" href="${c.source}">${c.sourceName} ↗</a>${c.historySource?`<br><a href="${c.historySource}" target="_blank" rel="noreferrer">Springer · 화약의 기원과 연단술 ↗</a>`:''}${c.extra?`<br><a href="${c.extra}" target="_blank" rel="noreferrer">The Met · 휠록 소장품 ↗</a>`:''}`;$('steps').innerHTML=(mechanics?FirearmPrinciples.lessons[i].steps:c.steps).map((s,k)=>`<button data-phase="${k}" aria-pressed="false"><b>0${k+1}</b>${s}</button>`).join('');for(const b of $('steps').children)b.onclick=()=>{clock.running=false;clock.time=+b.dataset.phase*2;sync();};for(const b of $('chapters').querySelectorAll('button')){b.classList.toggle('active',+b.dataset.chapter===i+1);if(+b.dataset.chapter===i+1)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');}$('next').textContent=i===3?'전체 챕터 맵 보기 ↓':`다음 · ${D.chapters[i+1].kind} →`;if(push){const u=new URL(location.href);u.searchParams.set('chapter',i+1);history.pushState({},'',u);}rebuild();sync();}
$('mechanismView').onclick=()=>{mechanics=true;select(chapter,false);};$('exteriorView').onclick=()=>{mechanics=false;select(chapter,false);};$('scrub').oninput=e=>{clock.running=false;clock.time=+e.target.value;sync();};
$('play').onclick=()=>{if(clock.time>=8)clock.time=0;clock.running=!clock.running;sync();};$('restart').onclick=()=>{clock.time=0;clock.running=false;sync();};$('speed').onchange=e=>clock.speed=+e.target.value;$('compare').onclick=()=>{compare=!compare;select(chapter,false);};for(const b of document.querySelectorAll('[data-kind]'))b.onclick=()=>{kind=b.dataset.kind;for(const x of document.querySelectorAll('[data-kind]'))x.setAttribute('aria-pressed',x===b);rebuild();sync();};$('resetView').onclick=()=>{yaw=.25;pitch=.18;distance=8.4;sync();};$('next').onclick=()=>chapter<3?select(chapter+1):$('map').scrollIntoView({behavior:'auto'});addEventListener('popstate',()=>{const n=Number(new URL(location.href).searchParams.get('chapter'));select(Number.isInteger(n)&&n>=1&&n<=4?n-1:0,false);});
function energy(){ $('energyStudy').hidden=chapter!==0||mechanics;if(chapter!==0||mechanics)return;const t=clock.time,heat=Math.max(0,Math.min(1,(t-2)/2)),move=Math.max(0,Math.min(1,(t-6)/2)),wall=270+move*100;let dots='';for(let i=0;i<18;i++){const x=48+(i%6)*(wall-80)/6+Math.sin(t*3+i)*heat*7,y=38+Math.floor(i/6)*22+Math.cos(t*3+i)*heat*5;dots+=`<circle cx="${x}" cy="${y}" r="4" fill="${heat>.3?'#b06b35':'#6e8b8a'}"/>`;}$('energyDiagram').innerHTML=`<svg viewBox="0 0 480 135" role="img" aria-label="기체의 가열, 압력, 이동 가능한 벽의 개념도"><path d="M425 20H25V108H425" fill="none" stroke="#82938b" stroke-width="3"/>${dots}<rect x="${wall}" y="22" width="12" height="84" fill="#5e7976"/>${t>=4?`<path d="M${wall-55} 65H${wall-8}m-10 -7 10 7-10 7" fill="none" stroke="#ad713b" stroke-width="3"/>`:''}<text x="30" y="128" font-size="11" fill="#596a64">기체 · 설명용 입자 표시</text><text x="${wall-25}" y="128" font-size="11" fill="#596a64">이동 가능한 벽</text></svg>`;$('energyCaption').textContent=['열이 전달되기 전의 기준 상태입니다.','열에너지가 늘어나는 것을 입자 색과 움직임으로 표시했습니다.','기체가 벽에 힘을 가합니다. 벽의 양쪽 압력 차이가 중요합니다.','벽이 이동하며 기체가 일을 합니다. 실제 압력·속도 계산이 아닌 정성적 설명입니다.'][clock.phase];}
function concept(){energy();$('concept').hidden=mechanics;if(mechanics)return;const c=mechanics?FirearmPrinciples.lessons[chapter]:D.chapters[chapter],phase=clock.phase,position=45+Math.min(clock.time/8,1)*390;const heat='<path d="M-12 15Q-22 3-10 -7T-9 -24M3 15Q-7 2 5 -9T6 -25M17 15Q7 2 19 -9"/>';
const wheel='<circle r="21"/><path d="M-21 0H21M0 -21V21M-15 -15L15 15M-15 15L15 -15"/>';
const impact='<path d="M-22 -22L-3 -3M-15 -24L-22 -22L-20 -14M6 1L18 -8M8 10H25M3 18L14 28"/><circle cx="-1" cy="5" r="5"/>';
const pressure='<circle r="12"/><path d="M0 -15V-28m-5 5 5-5 5 5M15 0H28m-5 -5 5 5-5 5M0 15V28m-5 -5 5 5 5-5M-15 0H-28m5 -5-5 5 5 5"/>';
const icons=chapter===0?[heat,heat,pressure,'<path d="M-25 0H25m-10 -10 10 10-10 10"/>']:chapter===1?[heat,'<path d="M-25 0H25m-10 -10 10 10-10 10"/>',heat,pressure]:chapter===2?[wheel,kind==='wheel'?wheel:impact,heat,pressure]:[impact,impact,heat,pressure];
$('concept').innerHTML=`<svg viewBox="0 0 480 116" role="img" aria-label="${c.steps.join('에서 ')}로 이어지는 개념 흐름"><path d="M45 83H435" stroke="#d3c4aa" stroke-width="2"/><circle cx="${position}" cy="83" r="5" fill="#a76b32"/>${icons.map((icon,i)=>`<g transform="translate(${60+i*120} 37)" fill="none" stroke="${phase===i?'#a76b32':'#8c9690'}" stroke-width="2" stroke-linecap="round">${icon}</g><text x="${60+i*120}" y="108" text-anchor="middle" font-size="10" fill="#536362">${i+1}. ${c.steps[i]}</text>`).join('')}</svg>`;}
function build(type){return mechanics?FirearmPrinciples.create(THREE,type,kind):FirearmsModel.create(THREE,type,kind);}
function rebuild(){ $('mechanismView').setAttribute('aria-pressed',mechanics);$('exteriorView').setAttribute('aria-pressed',!mechanics);$('viewTitle').textContent=mechanics?'움직이는 원리 · '+FirearmPrinciples.lessons[chapter].title:'역사적 외형 관찰';$('viewScope').textContent=mechanics?'총의 내부 장치가 아닌 독립된 교실 실험 모형입니다. 접촉과 운동 순서를 보여주며, 실제 열·충돌 수치를 계산하지 않습니다.':'종류를 구분하는 외형 모형입니다. 유물의 정밀 복원이나 내부 작동 모형이 아닙니다.';if(!scene)return;for(const g of objects){scene.remove(g);g.userData.texture?.dispose();g.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});}objects=[];const types=compare?[chapter-1,chapter]:[chapter];types.forEach((t,i)=>{const g=build(t);if(compare){g.scale.setScalar(mechanics?.6:.74);g.position.y=i===0?(mechanics?1.2:1.05):-(mechanics?1.2:1.05);}scene.add(g);objects.push(g);});const label=t=>mechanics?FirearmPrinciples.lessons[t].title:t===2?(kind==='wheel'?'휠록':'플린트록'):D.chapters[t].kind;$('objectLabels').textContent=compare?`위 · ${label(chapter-1)} / 아래 · ${label(chapter)}`:(mechanics?FirearmPrinciples.lessons[chapter].legend:`${label(chapter)} · 외형 개념 모형`);highlight();}
function highlight(){if(mechanics){const reports=objects.map(g=>g.userData.update(clock.time));$('viewport').dataset.audit=JSON.stringify(reports);$('contactState').textContent=chapter===0?'열 → 압력 → 이동':reports.at(-1)?.contact?'접촉 중':'접촉 전 / 분리';return;}$('contactState').textContent='외형 관찰';$('viewport').dataset.audit='[]';objects.forEach(g=>g.userData.parts.forEach(m=>{const active=clock.phase<3?m.userData.role==='ignition':['barrel','bronze'].includes(m.userData.role);m.material.emissive.setHex(active?0x775121:0x000000);m.material.emissiveIntensity=.28;}));}
function init(){try{if(typeof THREE==='undefined')throw Error('3D library unavailable');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(38,1,.1,80);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.domElement.setAttribute('aria-label','회전 가능한 역사 외형 또는 독립된 기계 원리 모형');renderer.domElement.setAttribute('role','img');$('viewport').append(renderer.domElement);$('fallback').hidden=true;scene.add(new THREE.HemisphereLight(0xfff5df,0x788b91,2.6));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(2,5,5);scene.add(light);let pointer=null;renderer.domElement.addEventListener('pointerdown',e=>{pointer=[e.clientX,e.clientY];renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!pointer)return;yaw+=(e.clientX-pointer[0])*.008;pitch=Math.max(-1.4,Math.min(1.4,pitch+(e.clientY-pointer[1])*.008));pointer=[e.clientX,e.clientY];sync();});renderer.domElement.addEventListener('pointerup',()=>pointer=null);renderer.domElement.addEventListener('pointercancel',()=>pointer=null);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(5,Math.min(18,distance*Math.exp(e.deltaY*.001)));sync();},{passive:false});new ResizeObserver(()=>{const el=$('viewport');renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();}).observe($('viewport'));rebuild();}catch(e){$('fallback').textContent='3D 모형을 불러오지 못했습니다. 아래 원리 흐름과 역사 설명은 계속 이용할 수 있습니다.';}}
function frame(t){const dt=last?Math.min((t-last)/1000,.1):0;last=t;const wasRunning=clock.running;clock.tick(dt);if(lastPhase!==clock.phase||clock.running||wasRunning!==clock.running){sync();lastPhase=clock.phase;}if(renderer){camera.position.set(distance*Math.sin(yaw)*Math.cos(pitch),distance*Math.sin(pitch),distance*Math.cos(yaw)*Math.cos(pitch));camera.lookAt(0,0,0);renderer.render(scene,camera);}requestAnimationFrame(frame);}
init();select(chapter,false);requestAnimationFrame(frame);
})();
