(()=>{'use strict';
const $=id=>document.getElementById(id),D=Firearms,clock=new D.Clock();let chapter=0,compare=false,kind='flint',renderer,scene,camera,objects=[],yaw=.25,pitch=.18,distance=10,last=0,lastPhase=-1;
const requested=Number(new URL(location.href).searchParams.get('chapter'));chapter=Number.isInteger(requested)&&requested>=1&&requested<=4?requested-1:0;
D.chapters.forEach((c,i)=>{const b=document.createElement('button');b.dataset.chapter=i+1;b.innerHTML=`${String(i+1).padStart(2,'0')} · ${c.kind}<small>${c.title}</small>`;b.onclick=()=>select(i);$('chapters').append(b);});
const mapLink=document.createElement('a');mapLink.href='#map';mapLink.textContent='다음 이야기 · 전체 12장 ↘';$('chapters').append(mapLink);
$('roadmap').innerHTML=D.roadmap.map(([t,k],i)=>`<article class="${i<4?'':'future'}"><span class="eyebrow">${String(i+1).padStart(2,'0')} / ${i<4?'공개':'예정'}</span><h3>${t}</h3><p>${k}</p>${i<4?`<a href="firearms.html?chapter=${i+1}">이 장 탐구하기 ↗</a>`:'<p>후속 제작 예정</p>'}</article>`).join('');
function sync(){const c=D.chapters[chapter];$('play').textContent=clock.running?'일시 정지':'원리 흐름 재생';$('play').setAttribute('aria-pressed',clock.running);for(const [i,b] of [...$('steps').children].entries())b.setAttribute('aria-pressed',clock.phase===i);$('explanation').textContent=c.explain[clock.phase];$('viewport').dataset.state=JSON.stringify({chapter:chapter+1,time:clock.time,phase:clock.phase,running:clock.running,compare,kind,camera:[yaw,pitch,distance],model:'static-exterior-concept'});concept();highlight();}
function select(i,push=true){chapter=i;clock.time=0;clock.running=false;lastPhase=-1;const c=D.chapters[i];document.title=`${i+1}. ${c.kind} — 총기의 변천사 | Mechanism Unfolded`;for(const key of ['intro','history','gain','limit','observe','question'])$(key).textContent=c[key];$('era').textContent=`${String(i+1).padStart(2,'0')} / ${c.era}`;$('title').textContent=c.title;$('variants').hidden=i!==2;$('compare').disabled=i===0;if(i===0)compare=false;$('compare').setAttribute('aria-pressed',compare);$('compare').textContent=compare?'현재 방식만 보기':'이전 방식과 비교';$('comparison').hidden=!compare;$('comparison').textContent=c.comparison;$('sources').innerHTML=`<a target="_blank" rel="noreferrer" href="${c.source}">${c.sourceName} ↗</a>${c.extra?`<br><a href="${c.extra}" target="_blank" rel="noreferrer">The Met · 휠록 소장품 ↗</a>`:''}`;$('steps').innerHTML=c.steps.map((s,k)=>`<button data-phase="${k}" aria-pressed="false"><b>0${k+1}</b>${s}</button>`).join('');for(const b of $('steps').children)b.onclick=()=>{clock.running=false;clock.time=+b.dataset.phase*2;sync();};for(const b of $('chapters').querySelectorAll('button')){b.classList.toggle('active',+b.dataset.chapter===i+1);if(+b.dataset.chapter===i+1)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');}$('next').textContent=i===3?'전체 챕터 맵 보기 ↓':`다음 · ${D.chapters[i+1].kind} →`;if(push){const u=new URL(location.href);u.searchParams.set('chapter',i+1);history.pushState({},'',u);}rebuild();sync();}
$('play').onclick=()=>{if(clock.time>=8)clock.time=0;clock.running=!clock.running;sync();};$('restart').onclick=()=>{clock.time=0;clock.running=false;sync();};$('speed').onchange=e=>clock.speed=+e.target.value;$('compare').onclick=()=>{compare=!compare;select(chapter,false);};for(const b of document.querySelectorAll('[data-kind]'))b.onclick=()=>{kind=b.dataset.kind;for(const x of document.querySelectorAll('[data-kind]'))x.setAttribute('aria-pressed',x===b);rebuild();sync();};$('resetView').onclick=()=>{yaw=.25;pitch=.18;distance=10;sync();};$('next').onclick=()=>chapter<3?select(chapter+1):$('map').scrollIntoView({behavior:'auto'});addEventListener('popstate',()=>{const n=Number(new URL(location.href).searchParams.get('chapter'));select(Number.isInteger(n)&&n>=1&&n<=4?n-1:0,false);});
function concept(){const c=D.chapters[chapter],phase=clock.phase,position=45+Math.min(clock.time/8,1)*390;const heat='<path d="M-12 15Q-22 3-10 -7T-9 -24M3 15Q-7 2 5 -9T6 -25M17 15Q7 2 19 -9"/>';
const wheel='<circle r="21"/><path d="M-21 0H21M0 -21V21M-15 -15L15 15M-15 15L15 -15"/>';
const impact='<path d="M-22 -22L-3 -3M-15 -24L-22 -22L-20 -14M6 1L18 -8M8 10H25M3 18L14 28"/><circle cx="-1" cy="5" r="5"/>';
const pressure='<circle r="12"/><path d="M0 -15V-28m-5 5 5-5 5 5M15 0H28m-5 -5 5 5-5 5M0 15V28m-5 -5 5 5 5-5M-15 0H-28m5 -5-5 5 5 5"/>';
const icons=chapter===0?[heat,heat,pressure,'<path d="M-25 0H25m-10 -10 10 10-10 10"/>']:chapter===1?[heat,'<path d="M-25 0H25m-10 -10 10 10-10 10"/>',heat,pressure]:chapter===2?[wheel,kind==='wheel'?wheel:impact,heat,pressure]:[impact,impact,heat,pressure];
$('concept').innerHTML=`<svg viewBox="0 0 480 116" role="img" aria-label="${c.steps.join('에서 ')}로 이어지는 개념 흐름"><path d="M45 83H435" stroke="#d3c4aa" stroke-width="2"/><circle cx="${position}" cy="83" r="5" fill="#a76b32"/>${icons.map((icon,i)=>`<g transform="translate(${60+i*120} 37)" fill="none" stroke="${phase===i?'#a76b32':'#8c9690'}" stroke-width="2" stroke-linecap="round">${icon}</g><text x="${60+i*120}" y="108" text-anchor="middle" font-size="10" fill="#536362">${i+1}. ${c.steps[i]}</text>`).join('')}</svg>`;}
function build(type){const g=new THREE.Group(),parts=[];function mesh(geo,color,x,y,z,role){const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,roughness:.65,metalness:role==='wood'?.05:.55}));m.position.set(x,y,z);m.userData.role=role;g.add(m);parts.push(m);return m;}function box(w,h,d,col,x,y,z,role){return mesh(new THREE.BoxGeometry(w,h,d),col,x,y,z,role);}function barrel(len,r,x,y){const b=mesh(new THREE.CylinderGeometry(r,r,len,32,1,true),0x7f8a85,x,y,0,'barrel');b.rotation.z=Math.PI/2;const ring=mesh(new THREE.TorusGeometry(r,.04,8,32),0xb69760,x+len/2,y,0,'barrel');ring.rotation.y=Math.PI/2;}
if(type===0){barrel(3.2,.3,.4,.1);mesh(new THREE.SphereGeometry(.36,24,16),0x8d7950,-1.25,.1,0,'barrel');box(1.3,.2,.2,0x765747,-2,.05,0,'wood');}
else{box(4.4,.3,.4,0x86634d,-.1,-.18,0,'wood');const butt=box(1.25,.65,.45,0x715744,-2.45,-.32,0,'wood');butt.rotation.z=.1;barrel(4.8,.16,.55,.13);mesh(new THREE.SphereGeometry(.23,16,12),0xb99963,-1.35,.1,.16,'ignition');if(type===1){const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(-1.8,.38,.27),new THREE.Vector3(-1.6,.8,.27),new THREE.Vector3(-1.3,.67,.27)]);mesh(new THREE.TubeGeometry(curve,20,.04,8,false),0x9c8b67,0,0,0,'ignition');}else if(type===2&&kind==='wheel'){mesh(new THREE.CylinderGeometry(.3,.3,.08,32),0xaf9567,-1.35,.22,.29,'ignition').rotation.x=Math.PI/2;}else{const marker=box(.14,.6,.14,0xb99963,-1.65,.48,.2,'ignition');marker.rotation.z=-.35;box(.25,.15,.22,type===3?0xb87b54:0x969c93,-1.53,.77,.2,'ignition');}}
g.userData.parts=parts;g.userData.type=type;return g;}
function rebuild(){if(!scene)return;for(const g of objects){scene.remove(g);g.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});}objects=[];const types=compare?[chapter-1,chapter]:[chapter];types.forEach((t,i)=>{const g=build(t);if(compare){g.scale.setScalar(.74);g.position.y=i===0?1.05:-1.05;}scene.add(g);objects.push(g);});const label=t=>t===2?(kind==='wheel'?'휠록':'플린트록'):D.chapters[t].kind;$('objectLabels').textContent=compare?`위 · ${label(chapter-1)} / 아래 · ${label(chapter)}`:`${label(chapter)} · 외형 개념 모형`;highlight();}
function highlight(){objects.forEach(g=>g.userData.parts.forEach(m=>{const active=clock.phase<3?m.userData.role==='ignition':m.userData.role==='barrel';m.material.emissive.setHex(active?0x775121:0x000000);m.material.emissiveIntensity=.28;}));}
function init(){try{if(typeof THREE==='undefined')throw Error('3D library unavailable');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(38,1,.1,80);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.domElement.setAttribute('aria-label','총기 종류를 비교하는 회전 가능한 외형 개념 모형');renderer.domElement.setAttribute('role','img');$('viewport').append(renderer.domElement);$('fallback').hidden=true;scene.add(new THREE.HemisphereLight(0xfff5df,0x788b91,2.6));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(2,5,5);scene.add(light);let pointer=null;renderer.domElement.addEventListener('pointerdown',e=>{pointer=[e.clientX,e.clientY];renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!pointer)return;yaw+=(e.clientX-pointer[0])*.008;pitch=Math.max(-1.4,Math.min(1.4,pitch+(e.clientY-pointer[1])*.008));pointer=[e.clientX,e.clientY];sync();});renderer.domElement.addEventListener('pointerup',()=>pointer=null);renderer.domElement.addEventListener('pointercancel',()=>pointer=null);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(5,Math.min(18,distance*Math.exp(e.deltaY*.001)));sync();},{passive:false});new ResizeObserver(()=>{const el=$('viewport');renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();}).observe($('viewport'));rebuild();}catch(e){$('fallback').textContent='3D 모형을 불러오지 못했습니다. 아래 원리 흐름과 역사 설명은 계속 이용할 수 있습니다.';}}
function frame(t){const dt=last?Math.min((t-last)/1000,.1):0;last=t;const wasRunning=clock.running;clock.tick(dt);if(lastPhase!==clock.phase||clock.running||wasRunning!==clock.running){sync();lastPhase=clock.phase;}if(renderer){camera.position.set(distance*Math.sin(yaw)*Math.cos(pitch),distance*Math.sin(pitch),distance*Math.cos(yaw)*Math.cos(pitch));camera.lookAt(0,0,0);renderer.render(scene,camera);}requestAnimationFrame(frame);}
init();select(chapter,false);requestAnimationFrame(frame);
})();
