/* Linked teaching diagrams: functional paths, not an assembly drawing. */
(()=>{
const $=id=>document.getElementById(id),blue='#148fc5',gold='#b18a49',green='#24896f';let chapter=0,focus=0;
const text=(x,y,t,cls='')=>`<text x="${x}" y="${y}" text-anchor="middle" class="${cls}">${t}</text>`;
const box=(x,y,w,t,c=blue)=>`<rect x="${x}" y="${y}" width="${w}" height="40" rx="8" fill="white" stroke="${c}" stroke-width="2"/>${text(x+w/2,y+25,t)}`;
const arrow=(d,c=blue)=>`<path d="${d}" fill="none" stroke="${c}" stroke-width="3" marker-end="url(#arr${c===gold?'G':c===green?'S':'B'})"/>`;
const defs=`<defs>${[['B',blue],['G',gold],['S',green]].map(([id,c])=>`<marker id="arr${id}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10" fill="${c}"/></marker>`).join('')}</defs>`;
function wheel(id,x,y,r,c){return `<g transform="translate(${x} ${y})"><g id="${id}">${Array.from({length:16},(_,i)=>`<rect x="-3" y="${-r-5}" width="6" height="11" rx="1" fill="${c}" transform="rotate(${i*22.5})"/>`).join('')}<circle r="${r}" fill="#fff" stroke="${c}" stroke-width="5"/><path d="M${-r+4} 0H${r-4}M0 ${-r+4}V${r-4}" stroke="${c}" stroke-width="4"/><circle r="5" fill="${c}"/></g></g>`;}
const config=[
 ['용두를 돌린 힘은 어디로 갈까요?','버튼을 눌러 감는 과정을 보세요. 먼저 작은 감기 기어들이 움직이고, 마지막에 태엽의 중심 축이 돌아갑니다.',['① 용두와 감기 축','② 회전 방향 바꾸기','③ 태엽 중심 감기'],['손으로 용두를 돌리면 가로로 놓인 감기 축도 함께 돌아갑니다.','감기 피니언과 크라운 휠이 맞물려 회전 축의 방향을 바꿉니다. 아래 그림은 연결 순서를 펼친 확대 개념도입니다.','래칫 휠은 태엽의 중심 축을 돌립니다. 되감김을 막는 멈춤쇠가 있어, 손을 놓아도 중심 축이 바로 거꾸로 풀리지 않습니다.']],
 ['힘의 길은 센터에서 나뉩니다.','센터 → 3번 → 4번은 계속 이어지는 기어열입니다. 바늘을 돌리는 길은 그 끝에 전부 몰려 있지 않습니다.',['① 태엽통','② 센터 휠','③ 3번 휠','④ 4번 휠'],['태엽이 풀리려는 힘으로 통이 돌아갑니다. 통 바깥의 이가 센터 축의 작은 바퀴를 밀어 줍니다.','센터 축에서 두 갈래로 이어집니다. 옆의 3번 휠을 돌리는 동시에, 반대편의 분침·시침에도 회전을 보냅니다.','3번 휠은 센터에서 받은 회전을 4번 휠로 넘기는 중간 바퀴입니다.','4번 휠은 탈진기로 힘을 보내면서, 추가 전달 기어를 통해 중앙 초침도 돌립니다.']],
 ['계속 풀리려는 힘에 문을 달아 줍니다.','팔렛 포크가 기어열을 잡고 있다가 놓으면 한 걸음 전진합니다.',['① 잡기와 놓기'],['태엽을 감고 한 번 해제를 누르세요. 포크가 놓아 줄 때만 연결된 기어열이 전진합니다.']],
 ['문을 여는 박자는 밸런스가 정합니다.','밸런스가 돌아올 때 포크를 움직이고, 태엽에서 온 힘을 조금 받아 다시 왕복합니다.',['① 밸런스와 포크'],['밸런스는 박자를 만들고, 태엽은 에너지를 공급합니다. 둘이 다른 역할이라는 점을 관찰하세요.']],
 ['같은 시계 안에서, 세 가지 속도로.','센터의 회전은 분침으로 바로 이어지고, 한 번 더 느려지는 길을 거쳐 시침으로 갑니다. 중앙 초침은 4번 휠에서 추가 기어를 거쳐 힘을 받습니다.',['① 센터 축 통과 보기','② 다이얼 아래 연결 보기','③ 중앙 초침 찾기','④ 세 바늘 함께 보기'],['지판을 흐리게 표시합니다. 직접 드래그해 옆에서 축을 살펴보세요. 파란 센터 축이 뒤쪽 큰 휠에서 앞쪽 분침까지 이어집니다.','분침과 함께 도는 작은 바퀴가 옆 기어를 돌립니다. 그 축의 더 작은 바퀴가 중앙의 시침 바퀴를 천천히 돌립니다.','4번 휠 위의 초록 기어가 중간 기어를 거쳐 중앙 기어를 돌립니다. 중앙의 가는 초침축은 분침관의 빈 공간을 통과합니다.','분침이 한 바퀴 돌면 시침은 다음 숫자까지 한 칸 갑니다. 그동안 중앙 초침은 60바퀴 돕니다.']]
];
config.push(
 ['손목의 움직임을 태엽에 저장합니다.','기존 시계의 뒷면에 자동 감기 장치를 얹었습니다. 마지막 출력축은 원래 태엽통의 중심 축과 같은 위치에 있습니다.',['① 무거운 로터','② 양방향 클러치','③ 감속 기어','④ 태엽 중심과 연결'],['반원형 로터는 무게가 한쪽에 몰려 있습니다. 손목이 움직이면 로터와 중심 피니언이 돌고, 첫 감기 휠에 회전을 넘깁니다.','기어 위치가 바뀌는 것이 아니라 내부 클러치의 잠김이 바뀝니다. 뒤에서 보아 로터가 시계 방향이면 첫 이웃 A가, 반시계 방향이면 다음 이웃 B가 잠겨 위층의 힘을 아래층으로 넘깁니다. 다른 쪽은 위·아래층이 독립적으로 도는 공회전 상태입니다. 아래 실시간 단면도와 방향 버튼으로 비교하세요.','큰 바퀴와 같은 축의 작은 피니언이 다음 큰 바퀴를 천천히 돌립니다. 회전수를 줄이는 대신 태엽을 감는 데 필요한 힘을 얻습니다. 층을 펼치면 큰 바퀴와 작은 피니언 사이의 축을 볼 수 있습니다.','마지막 휠의 축은 원래 태엽통 한가운데까지 이어집니다. 이 축이 태엽의 안쪽 끝을 감습니다. 시계가 갈 때는 태엽의 바깥 끝이 통을 돌려 기본 기어열에 힘을 보냅니다. 감는 축과 힘을 꺼내는 통을 구별해 보세요.']],
 ["하루 회전으로, 날짜와 요일을 따로 넘깁니다.", "바깥 31칸 날짜판과 안쪽 7칸 요일판은 같은 하루 축에서 힘을 받지만 서로 다른 출력입니다. 자정 관찰로 두 핑거의 접촉을 비교해 보세요.", ["① 하루 회전 만들기", "② 날짜 · 31칸", "③ 요일 · 7칸", "④ 독립적인 보정"], ["시침 축은 12시간에 한 바퀴 돕니다. 맞물린 두 배 큰 금색 휠은 24시간에 한 바퀴 돌며 두 층의 핑거를 함께 운반합니다.", "아래층 빨간 핑거가 바깥 날짜판 안쪽 이를 밀고, 초록 점퍼가 다음 틈에서 붙잡습니다. 날짜판은 31일마다 한 바퀴입니다.", "위층 보라색 핑거는 안쪽의 요일 별휠을 밉니다. 별휠과 요일판은 빈 중심 관으로 연결되어 함께 돌아갑니다. 별도의 초록 점퍼가 7개 위치를 고정합니다. 판의 살 사이로 연결을 보세요.", "날짜만 바꾸면 요일은 그대로입니다. 06:00에서 날짜 +1을 눌러 확인하세요. 시작 날짜·요일 선택은 관찰용 초기값입니다. 이 단일 언어 모형은 실제 6139A의 이중 언어판과 누름식 요일 보정을 재현하지 않습니다."]],
 ["수직 클러치로 측정을 켜고 끕니다.", "Seiko 6139A의 제어 기구를 살펴봅니다. 버튼은 상태를 선택하고, 바늘을 움직이는 에너지는 태엽에서 옵니다.", ["① 4번 휠에서 받기", "② 컬럼 휠과 수직 클러치", "③ 손가락과 분 누적계", "④ 회전 해머와 영점"], ["녹색 입력 휠은 1분에 한 번 계속 돕니다. 빨간 클러치 링과 측정 초침축은 같은 중심에 있지만, 분리하면 입력만 자유롭게 회전합니다. 기존 시계의 초침축을 입력으로 쓰는 부분은 이 사이트의 교육용 연결입니다.", "푸셔 → 작동 레버와 갈고리 → 컬럼 휠 래칫 → 첫 결합 레버 → 둘째 결합 레버 순서입니다. 기둥 사이로 접점이 들어가면 두 레버가 벌어지고, 스프링이 클러치 링을 아래 입력 휠에 눌러 측정을 시작합니다. 정지 때는 링을 들어 올립니다.", "측정 초침은 빨간 축에 직접 붙어 있습니다. 축 아래의 탄성 손가락이 파란 중간 휠을 한 칸 밀면 맞물린 금색 30분 휠과 같은 축의 분 바늘도 한 칸 움직입니다. 전달 기어와 하트캠은 서로 다른 높이에 있습니다.", "정지 후 리셋 푸셔 → 복귀 레버 → 해머 뒤꿈치 순서로 힘이 전달됩니다. 해머는 하나의 축 주위로 회전하며 두 하트캠을 누릅니다. 별도의 랙이나 크랭크는 없습니다. 측정 중에는 컬럼의 기둥이 해머의 걸림부를 막습니다. 아래 1분 17초 예제와 일시 정지·한 단계 버튼으로 관찰하세요."]]
);
config.splice(7,0,
 ['시침에서 하루 한 바퀴를 만듭니다.','보라색 바늘은 12가 아닌 24시간 눈금을 읽습니다.',['① 12시간 입력','② 반속 기어','③ 독립 조정','④ 낮과 밤 읽기'],['기존 시침 관과 같은 축의 파란 기어가 입력입니다. 시침은 하루에 두 번 돕니다.','같은 크기의 중간 휠은 속도를 유지하고, 그 축의 작은 피니언이 중앙의 두 배 큰 휠을 돌려 속도를 절반으로 줄입니다. 두 번 맞물려 방향은 유지됩니다.','GMT ±1시간은 구동 휠에 대해 표시 칼라를 한 칸 옮깁니다. 현지 시·분침과 날짜는 그대로입니다. 이 독립 조정 모델은 용두 연결부를 단순화한 교육용 방식입니다.','12시간 진행을 누르면 현지 시침은 한 바퀴, GMT 바늘은 반 바퀴 돕니다. 24는 자정, 12는 정오이므로 낮과 밤도 구별됩니다.']],
 ['날짜와 달 표시는 같은 하루 입력에서 출발합니다.','하루마다 한 칸, 같은 달 모습은 29.5일마다 돌아옵니다.',['① 하루 입력','② 한 칸 전진','③ 두 개의 달','④ 오차와 보정'],['시침의 12시간 회전을 24시간으로 감속합니다. 날짜판과 마찬가지로 하루 한 번 작동하는 핑거가 필요합니다.','핑거가 59치 휠을 한 칸 넘기면 점퍼가 다음 위치를 잡습니다. 하루 진행 버튼으로 기존 시계의 시각과 함께 관찰하세요.','한 달판에 달 두 개가 서로 반대쪽에 있습니다. 창은 한쪽 일부만 보여 주고 나머지는 가립니다. 덮개를 열면 전체 달판을 볼 수 있습니다.','59일에 한 바퀴, 달 두 개이므로 주기는 29.5일입니다. 실제 평균 약 29.53059일보다 짧아 약 2.6년이면 하루의 차이가 납니다. 조정 버튼은 달판만 한 칸 옮깁니다. 오늘의 천문 위상을 자동 계산하는 모델은 아닙니다.']]
);
function diagram(){
if(chapter===6)return `<svg viewBox="0 0 1000 180" role="img" aria-label="시침의 하루 회전이 날짜와 요일 두 경로로 나뉩니다">${defs}${box(15,68,230,'시침 → 24시간 휠',blue)}${arrow('M245 88H300V42H350',gold)}${arrow('M300 88V128H350','#9b66bd')}${box(350,22,270,'날짜 핑거 · 아래층',gold)}${box(350,108,270,'요일 핑거 · 위층','#9b66bd')}${arrow('M620 42H680',gold)}${arrow('M620 128H680','#9b66bd')}${box(680,22,290,'31칸 날짜판 + 점퍼',gold)}${box(680,108,290,'7칸 요일판 + 점퍼','#9b66bd')}</svg>`;
if(chapter>=5){const paths=[['로터','양방향 클러치','감속 기어','기존 태엽 중심'],['시침 → 하루 회전','날짜 핑거 → 31칸','요일 핑거 → 7칸','독립된 두 표시'],['시침 관','중간 휠 · 피니언','24시간 휠','GMT 바늘'],['시침 관','하루 구동 핑거','59치 달판','표시창'],['기존 초침축','클러치','측정 휠','측정 초침 · 누적계']][chapter-5];return `<svg viewBox="0 0 1000 115" role="img" aria-label="${paths.join(' → ')}">${defs}${paths.map((v,i)=>box(15+i*250,25,220,v,i===focus?green:blue)+(i<3?arrow('M'+(235+i*250)+' 45H'+(265+i*250),green):'')).join('')}${text(500,100,'기존 부품에서 이어지는 실제 연결을 아래 3D에서 선택해 보세요','mini')}</svg>`;}

if(chapter===0)return `<svg viewBox="0 0 1000 235" role="img" aria-label="용두, 감기 피니언, 크라운 휠, 래칫 휠, 태엽 중심의 연결"><g>${defs}${text(500,19,'감기 경로 확대 · 부품을 옆으로 펼친 개념도', 'mini')}<rect x="32" y="66" width="44" height="64" rx="8" fill="#d5e0e7" stroke="#6f8494" stroke-width="3"/><g id="crownStripes">${[76,86,96,106,116].map(y=>`<path d="M37 ${y}H71" stroke="#6f8494" stroke-width="2"/>`).join('')}</g><path d="M76 98H181" stroke="#6f8494" stroke-width="9"/>${wheel('wPin',211,98,25,blue)}${arrow('M247 98H356')}${wheel('wCrown',400,98,34,blue)}${arrow('M444 98H555')}${wheel('wRatchet',600,98,40,gold)}${arrow('M650 98H776',gold)}<circle cx="844" cy="98" r="58" fill="#f8f3e8" stroke="${gold}" stroke-width="4"/><path id="springDiagram" stroke="#788d9b" stroke-width="2.5" fill="none"/><circle cx="844" cy="98" r="7" fill="${blue}"/><path id="arborLine" d="M844 98L865 98" stroke="${blue}" stroke-width="5"/>${text(75,166,'손으로 용두 돌리기')}${text(211,166,'감기 피니언')}${text(400,166,'크라운 휠')}${text(600,166,'래칫 휠')}${text(844,166,'태엽의 안쪽 끝')}${text(400,192,'가로 축의 회전을 세로 축으로','mini')}${text(600,192,'태엽 중심 축과 함께 회전','mini')}${text(844,218,'감김 0%', 'mini').replace('<text','<text id="windReadout"')}</g></svg>`;
if(chapter===1)return `<svg viewBox="0 0 1000 235" role="img" aria-label="태엽통에서 센터, 3번, 4번, 탈진기로 이어지는 길과 바늘로 갈라지는 길">${defs}${box(25,45,135,'태엽통',gold)}${arrow('M160 65H220',gold)}${box(220,45,140,'센터 휠')}${arrow('M360 65H430')}${box(430,45,120,'3번 휠')}${arrow('M550 65H620')}${box(620,45,120,'4번 휠',green)}${arrow('M740 65H810',green)}${box(810,45,150,'탈진기 · 밸런스')}${arrow('M290 85V165H395')}${box(395,145,205,'분침 + 느려진 시침')}${arrow('M680 85V165H770',green)}${box(770,145,190,'중앙 초침',green)}${text(290,216,'센터 축에서 바늘 쪽으로 갈라집니다','mini')}${text(846,216,'추가 기어를 거쳐 중앙으로 전달합니다','mini')}</svg>`;
if(chapter===4)return `<svg viewBox="0 0 1000 250" role="img" aria-label="센터 축에서 분침과 시침으로 갈라지고 4번 휠에서 초침으로 이어지는 구조">${defs}${box(20,35,125,'센터 휠')}${arrow('M145 55H235')}${box(235,35,195,'지판을 통과하는 축')}${arrow('M430 55H530')}${box(530,35,180,'분침 · 1시간 한 바퀴')}${arrow('M475 55V140H530',gold)}${box(530,120,180,'옆 기어에서 느려짐',gold)}${arrow('M710 140H775',gold)}${box(775,120,205,'시침 · 12시간 한 바퀴',gold)}${box(20,190,125,'4번 휠',green)}${arrow('M145 210H530',green)}${box(530,190,240,'중앙 초침 · 1분 한 바퀴',green)}${text(330,232,'4번 휠 → 중간 기어 → 중앙 초침축','mini')}${text(330,109,'분침은 이 축과 함께 돌아갑니다','mini')}</svg>`;
return `<svg viewBox="0 0 1000 150" role="img" aria-label="태엽의 힘과 밸런스의 박자가 팔렛 포크에서 만납니다">${defs}${box(30,55,190,'태엽에서 온 힘',gold)}${arrow('M220 75H390',gold)}${box(390,55,210,'팔렛 포크 · 문지기')}${arrow('M600 75H775')}${box(775,55,195,'밸런스 · 박자')}${text(500,135,'기어를 잠그고, 밸런스가 돌아올 때 잠깐 놓아 줍니다','mini')}</svg>`;
}
document.querySelector('.workspace').prepend($('handExperiment'));
window.watchJourney={onFocus:()=>{},setStep(n){chapter=n;focus=n===4?3:0;const c=config[n];$('journeyTitle').textContent=c[0];$('journeyIntro').textContent=c[1];$('journeySteps').replaceChildren();c[2].forEach((label,i)=>{const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-pressed',i===focus);b.onclick=()=>{focus=i;this.refresh();this.onFocus(i);};$('journeySteps').append(b);});if(n===0){const wind=document.createElement('button');wind.id='guideWind';wind.textContent='↻ 용두 돌려 감기 +25%';wind.onclick=()=>document.getElementById('wind').click();$('journeySteps').append(wind);}$('journeyVisual').innerHTML=diagram();$('handExperiment').hidden=n!==4;this.refresh();},refresh(){const c=config[chapter];$('journeyNote').textContent=c[3][focus];if(chapter>=5)$('journeyVisual').innerHTML=diagram();Array.from($('journeySteps').children).forEach((b,i)=>{if(b.id!=='guideWind')b.setAttribute('aria-pressed',i===focus);});},update({charge,windAngle,seconds,winding}){if(chapter===0){$('guideWind').disabled=charge>=99.99||winding;for(const [id,m] of [['wPin',2],['wCrown',44/34],['wRatchet',-1]])$(id)?.setAttribute('transform',`rotate(${windAngle*180/Math.PI*m})`);$('arborLine')?.setAttribute('transform',`rotate(${-windAngle*180/Math.PI} 844 98)`);let path='';for(let i=0;i<=200;i++){const u=i/200,r=7+47*Math.pow(u,.8+charge/800),a=-Math.PI*2*(4+charge/40)*(1-u);path+=(i?'L':'M')+(844+Math.cos(a)*r).toFixed(2)+' '+(98+Math.sin(a)*r).toFixed(2);}$('springDiagram').setAttribute('d',path);$('windReadout').textContent=(winding?'감는 중 · ':'저장된 힘 · ')+Math.round(charge)+'%';}if(chapter===4){const mins=seconds/60;$('handMinutes').value=Math.min(60,mins);$('handMinutesValue').textContent=mins.toFixed(1)+'분';$('handReadout').textContent=`분침 ${(mins/60).toFixed(2)}바퀴 · 시침 ${(mins/60).toFixed(2)}칸 · 초침 ${mins.toFixed(1)}바퀴`;}}};
})();
