/* Educational SW210-inspired layout. Custom gearing/dimensions, not manufacturer CAD. */
(()=>{'use strict';
const $=id=>document.getElementById(id),stage=document.querySelector('.stage');
try{
if(!window.THREE||!window.WatchSpec)throw Error('3D 자료를 불러오지 못했습니다. 연결을 확인하고 새로고침해 주세요.');
const ADVANCED_MODES=['automatic','calendar','gmt','moon','chronograph'];
const T=THREE,S=WatchSpec,W=S.wheels,TAU=Math.PI*2,scene=new T.Scene();scene.background=new T.Color('#f0f2f4');
const camera=new T.PerspectiveCamera(35,1,.1,100),renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;stage.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-label','원형 지판에 조립된 손목시계 무브먼트');scene.add(new T.HemisphereLight(0xf5faff,0x8292a5,2));
for(const [color,power,p] of [[0xfff0d4,3.5,[-5,6,9]],[0xe2ecff,3,[5,-2,6]],[0xffffff,3,[0,-4,-8]]]){const l=new T.DirectionalLight(color,power);l.position.set(...p);scene.add(l);}
let advanced=null,automaticWindPulse=0;const root=new T.Group();scene.add(root);const groups={},meshes=[],wheels={},pins={};const colors={barrel:0xb79450,center:0xc8a05b,third:0xc8a05b,fourth:0xd0ab60,escape:0xb8a16b,fork:0x8c6b72,balance:0xcfa557,motion:0xbba05d,hands:0x334b65,plate:0xaab3bf,bridge:0xb8c0cb,crown:0x9ba7b8};
function group(key,x=0,y=0,z=0){const g=new T.Group();g.position.set(x,y,z);root.add(g);groups[key]=g;return g;}
function add(geo,key,parent,color=colors[key]){const m=new T.Mesh(geo,new T.MeshStandardMaterial({color:color??0xaab2bb,metalness:.7,roughness:.3,side:T.DoubleSide}));m.userData.key=key;parent.add(m);meshes.push(m);return m;}
function hole(r,x=0,y=0){const p=new T.Path();p.absarc(x,y,r,0,TAU,true);return p;}
function extrude(s,d=.075,b=.004){return new T.ExtrudeGeometry(s,{depth:d,bevelEnabled:b>0,bevelThickness:b,bevelSize:b,bevelSegments:2,curveSegments:64});}
function ring(ro,ri,d,key,g,z=0,color){const s=new T.Shape();s.absarc(0,0,ro,0,TAU,false);if(ri)s.holes.push(hole(ri));const m=add(extrude(s,d),key,g,color);m.position.z=z;return m;}
function shaft(r,z1,z2,key,g,color){const m=add(new T.CylinderGeometry(r,r,Math.abs(z2-z1),32),key,g,color);m.rotation.x=Math.PI/2;m.position.z=(z1+z2)/2;return m;}
function beam(x1,y1,x2,y2,width,key,g,z=.05,color){const m=add(new T.BoxGeometry(Math.hypot(x2-x1,y2-y1),width,.05),key,g,color);m.position.set((x1+x2)/2,(y1+y2)/2,z);m.rotation.z=Math.atan2(y2-y1,x2-x1);return m;}
function screw(x,y,z,g,scale=1){const p=new T.Group();p.position.set(x,y,z);g.add(p);shaft(.083*scale,0,.055,'bridge',p,0x45617b);const cut=add(new T.BoxGeometry(.115*scale,.018*scale,.012),'bridge',p,0x182b3a);cut.position.z=.059;cut.rotation.z=.3;}
function jewel(x,y,z,g,size=.075){const p=new T.Group();p.position.set(x,y,z);g.add(p);ring(size*1.55,size,.035,'bridge',p,0,0xc0a166);ring(size,.025,.025,'bridge',p,.035,0x9e3555);}
function toothShape(n,r){const m=2*r/n,ra=r+.8*m,rf=Math.max(r*.60,r-1.15*m),rb=r*Math.cos(Math.PI/9),inv=x=>{const t=Math.sqrt(Math.max(0,x*x-1));return t-Math.atan(t);},ip=inv(r/rb),half=Math.PI/(2*n)*.9,s=new T.Shape();let first=true;
for(let i=0;i<n;i++){const a=i*TAU/n,pts=[[rf,a-Math.PI/n]];for(const side of [-1,1]){const start=Math.max(rf,rb),rs=[start,start+(ra-start)/3,start+(ra-start)*2/3,ra];if(side===1)rs.reverse();for(const rr of rs)pts.push([rr,a+side*(half+ip-inv(Math.max(1,rr/rb)))]);}pts.push([rf,a+Math.PI/n]);for(const [rr,t] of pts){const x=Math.cos(t)*rr,y=Math.sin(t)*rr;first?s.moveTo(x,y):s.lineTo(x,y);first=false;}}s.closePath();return s;}
function gear(n,r,key,parent,z,spoked=true,d=.065){const g=new T.Group();g.position.z=z;g.userData.gear={n,r,width:d};parent.add(g);const s=toothShape(n,r);s.holes.push(hole(spoked?r*.79:r*.26));add(extrude(s,d,r>.2?.004:.001),key,g);if(spoked){ring(r*.18,key==='center'?S.centralSeconds.centerBore:key==='seconds'?.026:r*.025,d,key,g);for(let i=0;i<5;i++){const a=i*TAU/5;beam(Math.cos(a)*r*.12,Math.sin(a)*r*.12,Math.cos(a)*r*.81,Math.sin(a)*r*.81,r*.065,key,g,d/2);}}return g;}
const plate=group('plate'),ps=new T.Shape();ps.absarc(0,0,S.radius,0,TAU,false);for(const [x,y,r] of [[0,0,.23],[.05,-1.96,.85],[-1.65,.35,.29],[1.8,-1.4,.32],[...S.keyless.setting.p,.065],[-1.95,-1.2,.23],[...S.advanced.chronograph.counterPoint,.06]])ps.holes.push(hole(r,x,y));const plateMesh=add(extrude(ps,.14,.014),'plate',plate);plateMesh.position.z=-.18;ring(3.12,2.99,.24,'plate',plate,-.21,0x7d8c9c);ring(3.15,3.09,.065,'plate',plate,.035,0xb9c2cd);
for(let i=0;i<18;i++){const a=i*2.399,r=.8+(i%4)*.44,g=new T.Group();g.position.set(Math.cos(a)*r,Math.sin(a)*r,-.032);plate.add(g);ring(.22,.217,.002,'plate',g,0,0xa0acbb);}
for(const a of [.35,1.32,2.25,3.15,4,5.4])screw(2.81*Math.cos(a),2.81*Math.sin(a),.055,plate,.85);
const train=['barrel','center','third','fourth','escape'];for(const k of train){const q=W[k],g=group(k,...q.p);wheels[k]=gear(q.n,q.r,k,g,q.z,k!=='barrel');if(q.pn)pins[k]=gear(q.pn,q.pr,k,g,q.pz,false,.075);if(k==='center')ring(.045,S.centralSeconds.centerBore,3.18,k,g,-1.2,0x738599);else shaft(k==='escape'?.015:.04,-.23,k==='fourth'?2.005:k==='barrel'?1.73:1.66,k,g,0x738599);}
function phaseLink(a,b,targetPin=true,sourcePin=false){const x=W[a],y=W[b],nA=sourcePin?x.pn:x.n,nB=targetPin?y.pn:y.n,phi=Math.atan2(y.p[1]-x.p[1],y.p[0]-x.p[0]);(targetPin?pins[b]:wheels[b]).rotation.z=((nA+nB)*phi+nB*Math.PI-Math.PI)/nB;}
for(let i=0;i<4;i++)phaseLink(train[i],train[i+1]);
const drum=new T.Group();groups.barrel.add(drum);ring(1.26,1.20,S.barrelBody.height,'barrel',drum,S.barrelBody.z);ring(1.20,.085,.04,'barrel',drum,.24,0x697787);
ring(.38,.04,.10,'barrel',groups.barrel,.18);ring(.11,.045,.1,'barrel',groups.barrel,.27);
const spring=group('spring',...W.barrel.p),sg=new T.BufferGeometry(),verts=new Float32Array(601*6),indices=[];for(let i=0;i<600;i++){const k=i*2;indices.push(k,k+1,k+2,k+1,k+3,k+2);}sg.setAttribute('position',new T.BufferAttribute(verts,3));sg.setIndex(indices);add(sg,'barrel',spring,0xc4cfda);
const barrelHook=beam(1.15,0,1.23,0,.065,'barrel',groups.barrel,.43,0xe47c34);barrelHook.userData.label='태엽 바깥 끝 · 태엽통 벽의 걸림부';
const lid=group('lid',...W.barrel.p);const lidDisk=ring(1.265,.08,S.barrelBody.lidThickness,'barrel',lid,S.barrelBody.lidZ,0xa9b6c2);const ratchetGroup=new T.Group();lid.add(ratchetGroup);gear(44,.69,'barrel',ratchetGroup,1.30,false);ring(.17,.06,.08,'barrel',ratchetGroup,1.37,0xa8b4c0);screw(0,0,1.45,ratchetGroup,1.1);
const arborMarker=group('arborMarker',...W.barrel.p);shaft(.068,.26,1.67,'barrel',arborMarker,0x148fc5);beam(0,0,.23,0,.055,'barrel',arborMarker,.51,0x148fc5);
// Two orthogonal face-tooth engagements and a fixed-length selecting yoke.
const K=S.keyless,crownXY=K.winding.p;
function faceTeeth(parent,n,r,z,key='keyless'){const g=new T.Group();g.position.z=z;parent.add(g);ring(r+.035,r-.045,.025,key,g,0,0x93aaba);for(let i=0;i<n;i++){const a=i*TAU/n,m=add(new T.BoxGeometry(.095,Math.PI*r/n*.80,.09),key,g,0x9bb2bf);m.position.set(r*Math.cos(a),r*Math.sin(a),.06);m.rotation.z=a;}return g;}
const cw=group('crownWheel',...crownXY),cwRotor=gear(34,K.crownR,'crown',cw,1.60,false),cwFace=faceTeeth(cw,24,K.crownR,1.64);
const windingIdler=group('windingIdler',...K.winding.idler),windingIdlerRotor=gear(32,K.winding.idlerR,'crown',windingIdler,1.60,true);
const crown=group('crown',3.38,0,K.stemZ),stem=add(new T.CylinderGeometry(.045,.045,2.9,32),'crown',crown);stem.rotation.z=Math.PI/2;stem.position.x=-1.20;
const knob=add(new T.CylinderGeometry(.28,.28,.40,64),'crown',crown);knob.rotation.z=Math.PI/2;knob.position.x=.18;for(let i=0;i<36;i++){const a=i*TAU/36,m=add(new T.BoxGeometry(.38,.025,.025),'crown',crown,0x6f8296);m.position.set(.18,.282*Math.cos(a),.282*Math.sin(a));}
const windingPin=group('windingPin',crownXY[0]+K.crownR,0,K.stemZ),pinTurn=new T.Group();windingPin.add(pinTurn);pinTurn.rotation.y=Math.PI/2;const windPinRotor=gear(18,K.crownR*18/24,'crown',pinTurn,-.055,false,.11);
const slidingClutch=group('slidingClutch',K.sliderX[0],0,K.stemZ),clutchAxis=new T.Group();slidingClutch.add(clutchAxis);clutchAxis.rotation.y=Math.PI/2;const clutchRotor=gear(K.sliderN,K.sliderR,'crown',clutchAxis,-.055,false,.11);
const clutchDogs=new T.Group();slidingClutch.add(clutchDogs);for(let i=0;i<8;i++){const a=i*TAU/8,m=add(new T.BoxGeometry(.15,.035,.035),'crown',clutchDogs,0x148fc5);m.position.set(.10,.125*Math.cos(a),.125*Math.sin(a));}
const selectorLever=group('selectorLever',...K.yokePivot,K.stemZ+.23);const yokeArm=beam(0,0,K.yokeLength,0,.055,'crown',selectorLever,0,0xb18a49);shaft(.065,-.04,.06,'crown',selectorLever,0xb18a49);
const yokeSlot=group('yokeSlot',K.sliderX[0],0,K.stemZ+.20);for(const x of [-.09,.09])beam(x,-.34,x,.15,.035,'crown',yokeSlot,0,0xb18a49);
const ks=K.setting,settingBridge=group('settingBridge',...ks.p),settingTop=faceTeeth(settingBridge,ks.topN,ks.topR,1.86),settingBottom=gear(ks.n,ks.r,'motion',settingBridge,ks.z,false,.055);shaft(.045,ks.z,1.92,'crown',settingBridge,0xb18a49);
const settingPhase=((36+18)*Math.atan2(ks.p[1],ks.p[0]-.64)+18*Math.PI-Math.PI-35*Math.PI)/18;
const keyless=group('keyless');
const clickPivot=group('ratchetClick',W.barrel.p[0]-.82,W.barrel.p[1]+.15,1.69);beam(0,0,.17,-.15,.055,'barrel',clickPivot,0,0x19896c);shaft(.055,-.02,.06,'barrel',clickPivot);
for(const [g,label] of [[selectorLever,'요크 · 고정 길이 레버가 회전해 연결 부품을 이동'],[yokeSlot,'요크의 포크 · 슬라이딩 피니언 홈을 잡음'],[slidingClutch,'슬라이딩 피니언 · 용두와 함께 회전'],[windingPin,'감기 피니언 · 역회전 때 연결 이탈'],[cw,'크라운 휠 · 직각 회전을 평면 회전으로'],[windingIdler,'중간 감기 휠 · 태엽 중심의 래칫 휠로'],[clickPivot,'클릭 · 태엽이 거꾸로 풀리는 것을 막음'],[settingBridge,'시간 맞춤 축 · 아래 피니언에서 분 휠로']])g.traverse(m=>{if(m.isMesh)m.userData.label=label;});
const bp=[.05,-1.96],ep=W.escape.p,ev=new T.Vector2(bp[0]-ep[0],bp[1]-ep[1]).normalize(),fp=[ep[0]+ev.x*S.escapement.pivotDistance,ep[1]+ev.y*S.escapement.pivotDistance],forkBase=Math.atan2(ev.y,ev.x)-Math.PI/2;
const fork=group('fork',...fp,1.06),forkRotor=new T.Group();fork.add(forkRotor);beam(0,0,-.25,-.22,.055,'fork',forkRotor);beam(0,0,.25,-.22,.055,'fork',forkRotor);beam(0,0,0,.60,.05,'fork',forkRotor);for(const side of [-1,1])beam(side*S.escapement.slotHalfWidth,S.escapement.slotStart,side*S.escapement.slotHalfWidth,S.escapement.slotEnd,S.escapement.tineWidth,'fork',forkRotor);for(const x of [-.25,.25]){const m=add(new T.BoxGeometry(S.escapement.jewelWidth,S.escapement.jewelLength,.065),'fork',forkRotor,0xa7385b);m.position.set(x,S.escapement.jewelY,.055);m.userData.jewel=true;}shaft(.038,-.98,.12,'fork',forkRotor,0x74899d);
const balance=group('balance',...bp,.97),br=new T.Group();balance.add(br);ring(.82,.74,.065,'balance',br);for(let i=0;i<3;i++){const a=i*TAU/3;beam(.1*Math.cos(a),.1*Math.sin(a),.78*Math.cos(a),.78*Math.sin(a),.055,'balance',br,.03);}shaft(.045,-1.15,.27,'balance',br,0x647d91);ring(.12,.045,.10,'balance',br,.06);for(let i=0;i<8;i++){const a=i*TAU/8,m=shaft(.025,0,.07,'balance',br,0x9e7332);m.position.x=Math.cos(a)*.795;m.position.y=Math.sin(a)*.795;}ring(.39,.055,.025,'balance',br,.09,0x8797a8);const roller=shaft(S.escapement.pinRadius,.12,.20,'balance',br,0xb24161);roller.position.x=-ev.x*S.escapement.rollerRadius;roller.position.y=-ev.y*S.escapement.rollerRadius;roller.userData.jewel=true;
const hg=new T.BufferGeometry();hg.setAttribute('position',new T.BufferAttribute(new Float32Array(301*3),3));const hairLine=new T.Line(hg,new T.LineBasicMaterial({color:0x385875}));balance.add(hairLine);const stud=shaft(.055,.28,.36,'balance',balance,0x617991);stud.position.x=.55;
const bridge=group('bridge');function bridgeShape(points,z){const s=new T.Shape();points.forEach(([x,y],i)=>i?s.lineTo(x,y):s.moveTo(x,y));s.closePath();const m=add(extrude(s,.1,.025),'bridge',bridge);m.position.z=z;}
bridgeShape([[-2.68,1.23],[-1.98,2.22],[-.5,2.62],[-.52,1.55],[.07,.64],[-.04,.05],[-.54,-.4],[-.78,-1.03],[-1.59,-1.23],[-2.46,-.62]],1.20);bridgeShape([[.05,2.79],[1.55,2.40],[2.56,1.28],[2.74,.19],[2.13,.12],[1.30,.43],[.32,.84]],1.18);for(const k of ['center','third','fourth','escape'])jewel(...W[k].p,1.315,bridge,k==='escape'?.05:.065);for(const p of [[-2.10,1.63],[-2.18,-.38],[1.55,2.08],[2.39,.63]])screw(...p,1.31,bridge);
bridgeShape([[.04,-2.1],[.08,-1.80],[1.55,-1.73],[1.88,-2.12],[1.23,-2.45],[.50,-2.20]],1.27);jewel(...bp,1.39,bridge,.10);screw(1.52,-2.03,1.40,bridge,1.1);
const motion=group('motion');for(const k of ['cannon','minute','hour']){const q=W[k],g=new T.Group();g.position.set(...q.p,0);motion.add(g);groups[k]=g;wheels[k]=gear(q.n,q.r,'motion',g,q.z,k==='minute',.055);if(q.pn)pins[k]=gear(q.pn,q.pr,'motion',g,q.pz,false,.065);}shaft(.045,-.73,-.34,'motion',groups.minute,0x6b8196);ring(.17,.075,.07,'motion',groups.hour,-.65);phaseLink('cannon','minute',false);phaseLink('minute','hour',false,true);ring(.075,.046,.60,'motion',motion,-.75,0x536e87);ring(.106,.077,.13,'motion',motion,-.78,0xc5a259);
const face=group('hands',0,0,-.95);face.rotation.x=Math.PI;const dial=ring(2.82,.16,.035,'hands',face,0,0xe4e8ea);dial.material.metalness=.15;dial.material.roughness=.68;ring(2.96,2.83,.09,'hands',face,.005,0x8497ac);for(let i=0;i<60;i++){const a=i*TAU/60,l=i%5===0?.21:.075,m=add(new T.BoxGeometry(i%5===0?.055:.019,l,.025),'hands',face,0x354b61);m.position.set(Math.sin(a)*(2.57-l/2),Math.cos(a)*(2.57-l/2),.055);m.rotation.z=-a;}
function textOnDial(text,x,y,size){const c=document.createElement('canvas');c.width=256;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#344b62';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='500 74px Georgia';ctx.fillText(text,128,64);const m=new T.Mesh(new T.PlaneGeometry(size*2,size),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),transparent:true,depthWrite:false}));m.position.set(x,y,.064);face.add(m);return m;}
for(const [t,x,y] of [['12',0,2.12],['3',2.15,0],['6',0,-2.13],['9',-2.15,0]])textOnDial(t,x,y,.35);const brand=textOnDial('inside',0,.83,.28);
const mh=new T.Group(),hh=new T.Group();face.add(mh,hh);function hand(g,len,w,z){const s=new T.Shape();s.moveTo(-w/2,-.2);s.lineTo(-w/2,len*.66);s.lineTo(0,len);s.lineTo(w/2,len*.66);s.lineTo(w/2,-.2);s.closePath();const m=add(extrude(s,.025,.005),'hands',g,0x254763);m.position.z=z;beam(0,.18,0,len*.66,w*.18,'hands',g,z+.038,0xb9c5cf);}hand(mh,2.18,.105,.18);hand(hh,1.46,.17,.12);ring(.11,.026,.15,'hands',face,.1,0x9bafc1);
const secondsFace=new T.Group();face.add(secondsFace);secondsFace.position.z=.30;const sh=new T.Group();secondsFace.add(sh);hand(sh,2.42,.035,.015);for(const m of sh.children)if(m.material?.color)m.material.color.setHex(0x19856c);ring(.045,.026,.07,'hands',secondsFace,0,0x19856c);
const cs=S.centralSeconds,secondsTrain=group('secondsTrain'),secondsRotors=[];cs.p.forEach((p,i)=>{const g=new T.Group();g.position.set(...p,0);secondsTrain.add(g);const rotor=gear(cs.n,cs.r,'seconds',g,cs.z,true);rotor.traverse(m=>{if(m.isMesh){m.material.color.setHex(0x19856c);m.userData.pathColor=0x19856c;}});secondsRotors.push(rotor);});
const secondsPhase=[0,0,0];for(let i=1;i<3;i++){const a=cs.p[i-1],b=cs.p[i],phi=Math.atan2(b[1]-a[1],b[0]-a[0]);secondsPhase[i]=2*phi+Math.PI-Math.PI/cs.n-secondsPhase[i-1];}const secondsShaft=shaft(cs.shaftRadius,-1.33,2.005,'seconds',secondsTrain,0x19856c),secondsCollar=shaft(.034,1.94,2.005,'seconds',secondsTrain,0x19856c);

for(const [obj,col] of [[mh,0x148fc5],[hh,0xb18a49],[sh,0x24896f],[groups.cannon,0x148fc5],[groups.minute,0xb18a49],[groups.hour,0xb18a49]])obj.traverse(m=>{if(m.isMesh){m.userData.pathColor=col;m.material.color.setHex(col);}});
for(const [a,b] of [['barrel','center'],['center','third'],['third','fourth'],['fourth','escape']])mechanismAudit.mesh('train '+a+' → '+b,wheels[a],pins[b]);
mechanismAudit.mesh('cannon → minute',wheels.cannon,wheels.minute);mechanismAudit.mesh('minute → hour',pins.minute,wheels.hour);mechanismAudit.mesh('setting → minute',settingBottom,wheels.minute);mechanismAudit.mesh('winding crown → idler',cwRotor,windingIdlerRotor);mechanismAudit.mesh('winding idler → ratchet',windingIdlerRotor,ratchetGroup.children[0]);for(let i=1;i<3;i++)mechanismAudit.mesh('seconds '+i,secondsRotors[i-1],secondsRotors[i]);
const names={barrel:'태엽통',center:'센터 휠',third:'3번 휠',fourth:'4번 휠',escape:'이스케이프 휠',fork:'팔렛 포크',balance:'밸런스·헤어스프링',motion:'바늘 구동 기어',hands:'다이얼·바늘'},levels={barrel:0,center:1,third:1,fourth:1,escape:2,fork:2,balance:3,motion:4,hands:4};
const coaxDemo=createCoaxDemo(T,scene,S,toothShape);let coaxMode=false,crownMode=false;
let correctionTravel=0,correctionDirection=1;let crownInput=0,dateInputAngle=0,pendingDate=false,crownMessage='';let crownPosition=0,crownPull=0,handOffset=0,settingLeft=0,settingTurn=0,freeCrownTurn=0,freeTurnLeft=0,resumeAfterSetting=false;
let timeExperiment=false,windingLeft=0,handDemoLeft=0,handDemoSpeed=300,routeFocus=0;
let courseChapter=0,step=0,seconds=0,charge=0,playing=false,beats=0,fraction=0,rate=.125,selected='barrel',view='rear',yaw=.08,tilt=.27,distance=12.6,flip=0,windAngle=0,release=0,last=performance.now(),lastUI=0,lastSpring='',smoothSeconds=0,forkShown=-.12;
const orbit=WatchOrbit.create();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,target=new T.Vector3();
const data={barrel:['Barrel & mainspring','위쪽 · 무브먼트 면','태엽의 안쪽 끝은 중심축의 갈고리에, 바깥쪽 끝은 통 안쪽의 걸림부에 연결됩니다. 감을 때는 축을 돌려 금속 띠를 휘게 합니다. 놓으면 초록 래칫 클릭이 축의 역회전을 막고, 태엽이 펴지려는 힘은 바깥 고정부를 통해 회전 가능한 통을 돌립니다. 접착제가 아니라 기계적인 연결입니다. 덮개를 열어 파란 중심과 주황색 바깥 고정부를 비교하세요.','연결','용두로 감고 → 통에서 힘을 꺼냅니다'],center:['Center wheel & pinion','중앙 · 다이얼로 이어지는 축','긴 축이 지판을 관통합니다. 무브먼트 면에서는 기어열을, 다이얼 면에서는 캐넌 피니언과 분침을 구동합니다.','회전','1시간에 1회전'],third:['Third wheel & pinion','중앙의 왼쪽 · 중간 기어','아래의 작은 피니언은 센터 휠과 맞물립니다. 같은 축의 큰 휠은 한 층 위에서 4번 휠의 피니언을 돌립니다.','연결','센터에서 받아 → 4번 휠로 전달'],fourth:['Fourth wheel & pinion','중앙 아래쪽 · 탈진기로 연결','3번 휠에서 동력을 받아 1분에 한 번 회전합니다. 위쪽 휠은 이스케이프 피니언과 맞물립니다. 이 축 위의 추가 기어가 중간 기어를 거쳐 중앙 초침축을 돌립니다.','회전','1분에 1회전'],escape:['Escape wheel & pinion','아래 왼쪽 · 밸런스 옆','작은 피니언은 4번 휠에서 힘을 받고, 위쪽 15개 이는 팔렛과 번갈아 접촉합니다. 잠금·충격면의 정밀 치형은 단순화했습니다.','전진','해제당 반 잇수 · 12°'],fork:['Pallet fork','이스케이프 휠과 밸런스 사이','두 팔렛이 휠을 번갈아 잠그고, 반대편 포크가 밸런스의 롤러 쥬얼과 작용합니다. 기어열의 에너지를 진동계에 전달하는 위치입니다.','역할','잠금 · 해제 · 충격 전달'],balance:['Balance & hairspring','아래쪽 · 가장 큰 진동 공간','밸런스가 왕복할 공간을 가장자리 쪽에 확보합니다. 헤어스프링의 바깥 끝은 고정되고 안쪽은 밸런스 축과 움직입니다.','기준','4 Hz · 초당 8회 해제'],motion:['Motion works','지판 반대편 · 다이얼 아래','센터 축의 회전이 먼저 분침을 돌립니다. 옆의 중간 기어를 한 번 돌아오는 길을 거치면 회전이 느려져 시침을 돌립니다. 분침이 한 바퀴 도는 동안 시침은 다음 숫자까지 한 칸 움직입니다.','기어비','분침 한 바퀴 → 시침 한 칸'],hands:['Dial & coaxial hands','중앙의 시침·분침·초침','파란 분침과 금색 시침은 중앙에 포개져 있지만 속도가 다릅니다. 초록색 초침은 별도 전달 기어가 돌리는 중앙 축에 달려 있습니다. 위의 시간 슬라이더로 세 바늘을 함께 움직여 보세요.','방향','다이얼 면에서 시계 방향']};
Object.assign(names,{crown:'용두·감기 축',keyless:'연결 전환·시간 맞춤 기구',seconds:'초침 전달 기어·중앙 축',automatic:'로터·오토매틱 감기',calendar:'날짜판·날짜 구동 기구',gmt:'GMT·24시간 바늘',moon:'문페이즈·달판',chronograph:'크로노그래프·클러치·리셋'});
Object.assign(levels,{crown:0,keyless:0,seconds:4,automatic:4,calendar:4,gmt:4,moon:4,chronograph:4});
Object.assign(data,{gmt:['GMT / second time zone','다이얼 아래 · 24시간 휠','시침의 회전을 절반으로 줄여 하루에 한 번 도는 바늘을 추가합니다.','주기','24시간에 한 바퀴'],moon:['Moon phase','다이얼 아래 · 59치 달판','하루 한 칸씩 달판을 돌리고 표시창이 달의 일부를 가립니다.','주기','59칸 · 두 달 · 29.5일'],
 crown:['Crown & stem','오른쪽 · 손의 입력','용두를 돌리거나 당겨 감기·날짜·시간 조정 경로를 선택합니다. 회전하는 감기 축과 움직이는 연결 부품을 구분해 보세요.','세 위치','0 감기 · 1 날짜 · 2 시간'],
 keyless:['Keyless works','용두 안쪽 · 연결 전환','용두를 당기면 레버와 연결 부품이 움직여 감기, 날짜 조정, 시간 맞춤 중 한 경로를 선택합니다. 시간 맞춤 전달축 아래 기어는 분 휠과 맞물리는 데 필요합니다. 초침을 중앙으로 옮겨도 이 기어는 남습니다.','시간 조정','전달축 → 분 휠 → 시침·분침'],
 seconds:['Indirect central seconds','4번 휠 위 → 중앙 관통축','4번 휠에 고정된 전달 기어가 중간 기어를 거쳐 중앙 초침축을 돌립니다. 시간 맞춤 기어와는 별도 경로입니다. 확대 뷰도 같은 잇수·중심 위치를 사용합니다.','회전','정방향 → 역방향 → 정방향 · 1분 1회전'],
 automatic:['Automatic winding','무브먼트 뒤쪽 · 로터','로터의 양방향 회전을 방향 전환 장치에서 한 방향으로 모으고 감속하여 태엽을 감습니다. 감김 상태는 기본 모델의 태엽과 공유합니다.','에너지','손목 운동 → 로터 → 태엽'],
 calendar:['Simple date calendar','다이얼 아래 · 31칸 날짜판','12시간마다 도는 시침 쪽에서 받아 24시간 바퀴를 돌립니다. 핑거가 하루에 한 칸 밀고 점퍼가 정렬합니다. 용두 첫 번째 당김 위치는 빠른 날짜 조정입니다.','주기','24시간에 한 칸 · 31 다음 1'],
 chronograph:['Seiko 6139A chronograph','컬럼 휠 · 수직 클러치 · 회전 해머','푸셔가 컬럼 휠을 한 칸 돌려 두 결합 레버를 여닫습니다. 클러치 스프링이 동력을 연결하고, 정지 후 복귀 레버가 회전 해머로 두 하트캠을 영점에 맞춥니다.','측정','중앙 측정 초침 · 30분 누적계']});
for(const k of ['crown','keyless','seconds','automatic','calendar','gmt','moon','chronograph']){const b=document.createElement('button');b.className='part';b.dataset.part=k;b.innerHTML='<i class="swatch" style="--c:#19896c"></i>'+names[k]+'<span class="arrow">↗</span>';document.querySelector('.partlist').append(b);}
for(const g of [slidingClutch,selectorLever,settingBridge])g.traverse(m=>{if(m.isMesh)m.userData.key='keyless';});
// Cache original materials so repeated selections never accumulate tint.
const selectionBlue=new T.Color(0x148fc5),contextGrey=new T.Color(0xa3acb6);
function highlight(key){
 for(const m of meshes){
  const mat=m.material;
  if(!m.userData.baseMaterial)m.userData.baseMaterial={color:mat.color.clone(),metalness:mat.metalness,roughness:mat.roughness};
  const base=m.userData.baseMaterial,active=m.userData.key===key;
  mat.color.copy(base.color);mat.metalness=base.metalness;mat.roughness=base.roughness;mat.emissive.setHex(0);mat.emissiveIntensity=0;mat.opacity=1;mat.transparent=false;mat.depthWrite=true;
  if(active){mat.color.copy(m.userData.pathColor?new T.Color(m.userData.pathColor):m.userData.jewel?new T.Color(0xe53b72):m===dial?new T.Color(0xd9edf7):selectionBlue);mat.metalness=.22;mat.roughness=.42;mat.emissive.setHex(0x006b9e);mat.emissiveIntensity=m===dial?.06:.35;}
  else if(m.userData.key in names)mat.color.lerp(contextGrey,.25);
  if(active&&m.geometry!==sg&&!m.userData.selectionOutline){
   const line=new T.LineSegments(new T.EdgesGeometry(m.geometry,40),new T.LineBasicMaterial({color:0x064b70,transparent:true,opacity:.85,depthTest:true,depthWrite:false}));
   line.raycast=()=>{};m.add(line);m.userData.selectionOutline=line;
  }
  if(m.userData.selectionOutline)m.userData.selectionOutline.visible=active;
 }
 hairLine.material.color.setHex(key==='balance'?0x009fd7:0x385875);
}
function choose(k){if(advanced&&ADVANCED_MODES.includes(k)){inspectAdvanced(k);return;}if(!(k in names)||levels[k]>step)return;selected=k;const d=data[k];$('partTitle').textContent=names[k];['partEng','partTag','partDesc','specLabel','specValue'].forEach((id,i)=>$(id).textContent=d[i]);document.querySelectorAll('[data-part]').forEach(b=>{b.classList.toggle('active',b.dataset.part===k);b.setAttribute('aria-pressed',b.dataset.part===k);});highlight(k);showPartLesson(k,names[k]);$('locationChip').textContent=names[k]+' · '+d[1];}
function setView(v,explicit=false){if(!explicit)return;view=v;orbit.preset(v);$('rear').setAttribute('aria-pressed',v==='rear');$('dialView').setAttribute('aria-pressed',v==='dial');$('viewCaption').textContent=v==='rear'?'무브먼트 방향 · 자유 회전 가능':'다이얼 방향 · 자유 회전 가능';}

const titles=[['손으로 감아, 힘을 저장합니다.','먼저 용두를 돌려 보세요. 감기 기어가 태엽의 중심을 돌리고, 금속 띠에 힘이 저장됩니다.','태엽 감기'],['저장된 힘이 기어를 돌립니다.','태엽통 → 센터 → 3번 → 4번. 서로 닿는 큰 바퀴와 작은 바퀴를 따라가 보세요.','동력 전달'],['힘을 조금씩 풀어 줍니다.','팔렛 포크가 잡았다 놓아 주면, 연결된 기어들이 조금씩 전진합니다.','탈진기'],['왕복 운동이 박자를 정합니다.','밸런스가 돌아올 때마다 포크를 움직여 다음 한 걸음을 허용합니다.','진동계'],['세 바늘은 서로 다른 길로 움직입니다.','분침은 센터 축에서, 초침은 4번 휠에서, 시침은 더 느려지는 기어를 거쳐 움직입니다.','바늘 연결']];
const lessons=[['감는 동안과 풀리는 동안을 구분해 보세요.','용두는 태엽의 안쪽 끝을 감습니다. 저장한 힘을 꺼낼 때는 태엽의 바깥 끝이 통을 돌립니다.','움직임 전달하기 →'],['센터에서 길이 나뉩니다.','한쪽은 3번·4번 휠을 지나 박자를 조절하는 장치로, 다른 쪽은 지판 반대편의 분침과 시침으로 이어집니다.','탈진기 연결하기 →'],['잠금 → 해제 → 다시 잠금','태엽을 감은 뒤 한 번 해제를 눌러, 포크와 기어열이 함께 움직이는 모습을 보세요.','밸런스 연결하기 →'],['시계가 스스로 다음 걸음을 정합니다.','밸런스 핀이 포크 입구를 통과할 때마다 잠금이 풀립니다. 관찰 모드는 실제보다 8배 느립니다.','세 바늘 연결하기 →'],['분침 한 바퀴, 시침 한 칸.','위의 시간 슬라이더를 움직여 보세요. 중앙 초침은 1분마다 한 바퀴, 분침은 1시간마다 한 바퀴 돕니다.','처음부터 다시 보기 ↺']];
function setStep(n){if(n>=5){selectAdvanced(ADVANCED_MODES[n-5]);return;}courseChapter=n;document.body.classList.remove('advancedLesson');if($('advancedParts'))$('advancedParts').hidden=true;const storedOffset=handOffset;const storedCharge=charge,storedSeconds=seconds,storedBeats=beats;step=n;reset(false);seconds=smoothSeconds=storedSeconds;beats=storedBeats;handOffset=storedOffset;charge=storedCharge;windAngle=charge/100*TAU*5.625;routeFocus=n===4?3:0;const d=titles[n];$('pageTitle').textContent=d[0];$('pageSub').textContent=d[1];$('chapter').textContent='0'+(n+1)+' / 08 · '+d[2];document.querySelectorAll('[data-step]').forEach(b=>{b.classList.toggle('active',+b.dataset.step===n);b.setAttribute('aria-current',+b.dataset.step===n?'step':'false');});document.querySelectorAll('[data-part]').forEach(b=>b.hidden=levels[b.dataset.part]>n||ADVANCED_MODES.includes(b.dataset.part));$('manualPanel').hidden=n!==1;$('springPanel').hidden=false;$('wind').hidden=false;$('tick').hidden=n!==2;$('rate').hidden=n<3;$('hour').hidden=n!==4;$('play').hidden=n===2||n===0;$('cover').disabled=false;$('bridges').disabled=n<3;$('openDial').disabled=n<4;$('dialView').disabled=n<4;$('bridges').checked=$('cover').checked=$('openDial').checked=false;$('lessonNo').textContent='0'+(n+1);$('lessonTitle').textContent=lessons[n][0];$('lessonText').textContent=lessons[n][1];$('next').textContent=n===4?'다음 · 오토매틱':lessons[n][2];$('gearReadings').hidden=n!==1;$('beatReadings').hidden=n<2;$('observeTitle').textContent=['用두 → 감기 기어 → 태엽 중심','태엽통 → 센터 → 3번 → 4번','잡고 → 놓고 → 다시 잡기','한 번 왕복 → 두 번 해제','초침 1분 · 분침 1시간 · 시침 12시간'][n].replace('用두','용두');$('observeText').textContent=n===4?'세 바늘은 중앙에 모이지만 초침의 회전은 별도 기어로 전달됩니다.':'위의 경로 버튼으로 연결을 하나씩 따라가세요.';rate=.125;$('rate').textContent='관찰 0.125×';$('experimentHint').textContent=n===0?'용두 버튼을 누르면 약 2.5초 동안 감깁니다. 파란 표시가 태엽의 중심입니다.':n===1?'태엽을 감고 풀어 보세요. 직접 돌려보기는 회전비를 보는 별도 실험입니다.':'태엽을 감은 뒤 작동하세요. 기본 관찰 속도는 8배 느립니다.';setView('rear');choose(['barrel','center','fork','balance','hands'][n]);window.watchJourney.setStep(n);sync();}
function reset(resetAdvanced=true){if(advanced){advanced.pauseInput();advanced.setView('none');}if(resetAdvanced&&advanced)advanced.reset();if(crownMode)setCrownMode(false);if(coaxMode)setCoaxMode(false);automaticWindPulse=0;crownInput=dateInputAngle=0;pendingDate=false;crownMessage='';crownPosition=0;handOffset=settingLeft=settingTurn=freeCrownTurn=freeTurnLeft=0;resumeAfterSetting=false;timeExperiment=false;windingLeft=handDemoLeft=0;routeFocus=step===4?3:0;seconds=smoothSeconds=beats=fraction=release=windAngle=0;forkShown=-.12;charge=0;playing=false;lastSpring='';readings();sync();}
function sync(){const empty=charge<=0;$('play').disabled=empty||crownPosition===2;$('play').textContent=playing?'일시 정지':empty?'먼저 태엽을 감으세요':step===0?'태엽 감기':step===1?'태엽 풀어 기어 돌리기':'시계 작동';$('play').setAttribute('aria-pressed',playing);$('wind').disabled=crownPosition!==0||charge+windingLeft>=100;$('tick').disabled=crownPosition===2||empty;$('hour').disabled=crownPosition===2||charge<100/45;$('manual').disabled=crownPosition===2;$('status').textContent=crownMode?(crownPosition===1?crownCorrection()+' 조정 · 용두에서 독립 보정 경로로 전달':crownPosition===2?'시간 맞춤: 용두 → 전달축 → 분 휠 → 두 바늘':'태엽 감기: 용두 → 감기 휠 → 태엽 중심'):coaxMode?'세 축·관의 절개 모형 · 파란 분침 1회전 = 금색 시침 1칸':crownPosition===2?'시간 맞춤 · 시침·분침만 조정 · 초침 정지':timeExperiment?'바늘 연결 실험 · 태엽 소모 없이 시간만 움직입니다':empty?'태엽을 감아 작동을 시작하세요':playing?'연결된 기어열이 동력을 전달합니다':step===2?'잠김 · 한 번 해제를 눌러 주세요':'부품을 선택해 위치와 연결을 살펴보세요';updateCrownUI();}
function readings(){const ca=seconds/3600;$('turnA').textContent=ca.toFixed(2);$('turnB').textContent=(-ca*8).toFixed(2);if(step===1){const d=ca*360,v=d>360?d%360:d;$('manual').value=Math.round(v);$('manualValue').textContent=Math.round(v)+'°';}$('charge').value=charge;$('chargeText').textContent=charge>0&&charge<1?'<1%':Math.round(charge)+'%';$('beatCount').textContent=beats.toLocaleString('ko-KR');$('lockState').textContent=timeExperiment?'바늘 속도 비교 중':release>0?'해제 · 충격 전달':'잠김';const whole=Math.floor(seconds+1e-6),h=Math.floor(whole/3600),m=Math.floor(whole/60)%60,s=whole%60;$('timeReading').textContent=step===2?'수동 전환 · 일정한 박자 없음':'모의 경과 '+[h,m,s].map(x=>String(x).padStart(2,'0')).join(':');$('hour').disabled=crownPosition===2||charge<100/45;}
function advance(n){const cost=100/(S.reserveSeconds*8),count=Math.min(n,Math.floor((charge+1e-10)/cost));beats+=count;seconds+=count/8;advanced?.advance(count/8);charge=Math.max(0,charge-count*cost);release=.18;if(charge<cost){charge=0;playing=false;}readings();sync();}
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>setStep(+b.dataset.step));document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>choose(b.dataset.part));$('next').onclick=()=>setStep((courseChapter+1)%10);$('rear').onclick=()=>setView('rear',true);$('dialView').onclick=()=>{$('openDial').checked=false;setView('dial',true)};$('front').onclick=()=>orbit.preset('front');$('resetView').onclick=()=>{orbit.preset('reset');view='rear';};$('manual').oninput=e=>{playing=false;seconds=+e.target.value/360*3600;smoothSeconds=seconds;readings();sync();};$('wind').onclick=()=>{if(crownPosition!==0)return;timeExperiment=false;playing=false;handDemoLeft=0;windingLeft+=Math.min(25,100-charge-windingLeft);sync();};$('play').onclick=()=>{if(crownPosition===2||charge<=0||windingLeft>0)return;timeExperiment=false;handDemoLeft=0;playing=!playing;sync();};$('tick').onclick=()=>{if(crownPosition!==2&&charge>0)advance(1);};$('hour').onclick=()=>{if(crownPosition!==2&&charge>=100/45){playing=false;advance(28800);smoothSeconds=seconds;}};$('rate').onclick=()=>{rate=({0.125:.25,0.25:.5,0.5:1,1:60,60:3600,3600:.125})[rate]??.125;$('rate').textContent=rate<=1?'관찰 '+rate+'×':rate+'× 빠르게';$('experimentHint').textContent=rate<=1?'모든 부품이 같은 '+rate+'배속입니다. 밸런스는 화면에서 초당 '+(S.frequency*rate)+'회 왕복합니다.':'모든 부품이 '+rate+'배속입니다. 빠른 진동은 화면 주사율 때문에 건너뛰어 보일 수 있습니다. 접점은 0.125×에서 관찰하세요.';};$('restart').onclick=()=>{const n=courseChapter;reset();setStep(n);};$('openDial').onchange=()=>{if($('openDial').checked)setView('dial');};
window.watchJourney.onFocus=(i)=>{if(courseChapter>=5){advanced.setFocus(i);return;}routeFocus=i;if(step===0){choose('barrel');$('cover').checked=false;setView('rear');tilt=.65;}else if(step===1){choose(['barrel','center','third','fourth'][i]||'center');setView('rear');}else if(step===4){choose(i===0?'center':i===1?'motion':'hands');if(i===0){setView('rear');tilt=1.10;}else setView('dial');$('openDial').checked=i<3;}else choose(step===2?'fork':'balance');};
$('handMinutes').oninput=e=>{timeExperiment=true;playing=false;windingLeft=handDemoLeft=0;seconds=+e.target.value*60;smoothSeconds=seconds;sync();readings();};$('handDemo').onclick=()=>{timeExperiment=true;playing=false;windingLeft=0;seconds=smoothSeconds=0;handDemoSpeed=300;handDemoLeft=3600;routeFocus=3;if(!crownMode)choose('hands');$('openDial').checked=false;sync();};
$('secondDemo').onclick=()=>{timeExperiment=true;playing=false;windingLeft=0;seconds=smoothSeconds=0;handDemoSpeed=7.5;handDemoLeft=60;routeFocus=3;if(!crownMode)choose('hands');$('openDial').checked=false;sync();};
function crownCorrection(){return ({calendar:'날짜',gmt:'GMT',moon:'달 위상'})[advanced?.mode]||'';}
function updateCrownUI(){const correction=crownCorrection(),setting=crownPosition===2,dateMode=crownPosition===1,isDate=advanced?.mode==='calendar';$('crownDate').hidden=!correction;$('crownDate').textContent='1 · 한 칸 당기기 — '+correction+' 조정';$('crownOut').textContent=(correction?'2 · 두 칸 당기기':'1 · 한 칸 당기기')+' — 시간 맞춤';$('crownIn').setAttribute('aria-pressed',crownPosition===0);$('crownDate').setAttribute('aria-pressed',dateMode);$('crownOut').setAttribute('aria-pressed',setting);$('crownModeText').textContent=setting?(correction?'두 칸 당김: ':'한 칸 당김: ')+'시침·분침을 맞춥니다. 현재 시점을 유지하며 일반 초침과 구동계는 멈춥니다. 한 번 조작은 5분입니다(시연용).':dateMode&&!isDate?(advanced.mode==='gmt'?'한 칸 당김: GMT 바늘만 한 시간씩 앞뒤로 맞춥니다. 일반 시침·분침과 날짜는 바뀌지 않습니다.':'한 칸 당김: 앞으로 돌려 달판을 하루 한 칸 전진시킵니다. 반대로 돌리면 공회전합니다. 일반 바늘은 그대로입니다.'):dateMode?'한 칸 당김: 앞으로 돌려 날짜를 한 칸 바꿉니다. 시침·분침과 일반 초침의 시각은 바꾸지 않습니다. 이 모델은 날짜 기구가 맞물리는 21–03시에는 빠른 조정을 잠급니다. 바로 옆 06:00 버튼으로 잠금을 해제해 관찰할 수 있습니다.':'밀어 넣음: 앞으로 돌려 태엽을 감습니다. 뒤로 돌리면 공회전합니다. 로터로도 같은 태엽을 감을 수 있습니다.';$('crownFeedback').textContent=crownMessage;$('crownSafeTime').hidden=!(dateMode&&isDate);$('crownDateStatus').hidden=!(dateMode&&isDate);$('crownDateStatus').textContent=advanced?'날짜 '+advanced.state.date+'일 · '+(advanced.state.canQuickset()?'빠른 조정 가능':'21–03시: 빠른 조정 잠금'):'';$('routeStem').setAttribute('transform',`translate(${-12*crownPosition} 0)`);$('routeClutch').setAttribute('transform',`translate(${11*crownPosition} 0)`);$('windRoute').style.opacity=crownPosition===0?'1':'.18';$('setRoute').style.opacity=setting?'1':'.18';$('crownForward').textContent=setting?'↻ 앞으로 5분':dateMode?'↻ '+correction+(isDate?' +1일':advanced.mode==='gmt'?' +1시간':' +1칸'):'↻ 앞으로 돌려 감기';$('crownBackward').textContent=setting?'↺ 뒤로 5분':dateMode?(advanced.mode==='gmt'?'↺ GMT −1시간':'↺ 공회전'):'↺ 반대로 돌리기';$('crownForward').disabled=!!freeTurnLeft||!!settingLeft||(crownPosition===0&&(charge+windingLeft>=100||windingLeft>0))||(dateMode&&isDate&&!advanced.state.canQuickset());$('crownBackward').disabled=!!freeTurnLeft||!!settingLeft||windingLeft>0;for(const id of ['handMinutes','handDemo','secondDemo'])$(id).disabled=setting;$('speedExperiment').hidden=setting;$('crownQuickMode').textContent=['용두 · 태엽 감기','용두 · '+correction+' 조정','용두 · 시간 맞춤'][crownPosition];$('crownQuickToggle').textContent='용두 다음 위치';$('crownQuickForward').disabled=$('crownForward').disabled;$('crownQuickBack').disabled=$('crownBackward').disabled;const total=Math.floor(seconds+handOffset+1e-6),t=((total%43200)+43200)%43200,h=Math.floor(t/3600)||12,m=Math.floor(t/60)%60,sec=Math.floor(seconds+1e-6)%60;$('crownClock').textContent=[h,m,sec].map(n=>String(n).padStart(2,'0')).join(':');$('crownQuickClock').textContent=$('crownClock').textContent;}
function setCrownPosition(position){if(position===1&&!crownCorrection())position=2;if(position===crownPosition)return;const wasRunning=playing,wasSetting=crownPosition===2,keepRear=view==='rear',savedYaw=yaw,savedTilt=tilt,savedDistance=distance;crownPosition=position;if(position===1){dateInputAngle=0;correctionTravel=0;}pendingDate=false;crownMessage='';windingLeft=handDemoLeft=settingLeft=freeTurnLeft=0;timeExperiment=false;if(position===2){resumeAfterSetting=wasRunning;playing=false;if(!crownMode&&!advanced?.mode.includes('calendar')){setView('rear');if(keepRear){yaw=savedYaw;tilt=savedTilt;distance=savedDistance;}}}else if(wasSetting){playing=resumeAfterSetting&&charge>0;resumeAfterSetting=false;}sync();readings();}
$('crownSafeTime').onclick=()=>{playing=false;handDemoLeft=settingLeft=0;handOffset=21600-seconds;advanced.state.lastClock=21600;crownMessage='06:00으로 이동했습니다. 날짜 +1과 역방향 공회전을 비교하세요.';sync();};$('crownIn').onclick=()=>setCrownPosition(0);$('crownDate').onclick=()=>setCrownPosition(1);$('crownOut').onclick=()=>setCrownPosition(2);
function turnCrown(direction){if(crownPosition===1){if(freeTurnLeft)return;correctionTravel=0;correctionDirection=direction;if(['gmt','moon'].includes(advanced?.mode)){const changed=advanced.correctComplication(direction);freeTurnLeft=-direction*TAU*1.5;crownMessage=changed?(advanced.mode==='gmt'?'용두 → 독립 조정 칼라 → GMT 바늘 한 시간 이동':'용두 → 달판 보정 → 59치 휠 한 칸 이동'):'역방향 공회전 · 달판은 그대로입니다.';sync();return;}if(direction<0){freeTurnLeft+=TAU*1.5;crownMessage='역방향: 용두와 조정축만 회전 · 조정 핑거는 물러나 날짜판은 그대로입니다.';}else if(advanced?.state.canQuickset()){pendingDate=true;freeTurnLeft-=TAU*1.5;crownMessage='정방향: 조정축 → 편심 핑거 → 날짜판 한 칸 → 점퍼 고정';}else crownMessage='21–03시에는 날짜 기구가 맞물려 있습니다. 아래 06:00 버튼으로 옮긴 뒤 조정하세요.';sync();return;}const action=S.crownAction(crownPosition,direction);if(crownPosition===2){settingLeft+=action.settingSeconds;routeFocus=3;}else if(action.windPercent)$('wind').click();else {freeTurnLeft+=TAU;crownMessage='역방향: 브레게 톱니가 미끄러져 감기 피니언은 정지합니다. 초록 클릭이 태엽의 역회전을 막습니다.';}if(action.windPercent)crownMessage='정방향: 파란 연결 톱니 → 감기 피니언 → 크라운 휠 → 중간 휠 → 태엽 중심';sync();}
$('crownForward').onclick=$('crownQuickForward').onclick=()=>turnCrown(1);$('crownBackward').onclick=$('crownQuickBack').onclick=()=>turnCrown(-1);$('crownQuickToggle').onclick=()=>setCrownPosition(crownCorrection()?(crownPosition+1)%3:crownPosition===0?2:0);
function setCoaxMode(enabled){if(enabled&&advanced){advanced.setView('none');$('handExperiment').hidden=false;}if(enabled&&crownMode)setCrownMode(false);if(enabled&&crownPosition===2)setCrownPosition(0);coaxMode=enabled;for(const id of ['secondDemo','handDemo'])$(id).hidden=enabled;root.visible=!enabled;coaxDemo.group.visible=enabled;$('coaxToggle').textContent=enabled?'전체 시계로 돌아가기':'세 바늘의 축·관 구조 확대';$('coaxToggle').setAttribute('aria-pressed',enabled);for(const id of ['coaxMinute','coaxHour','coaxSecond','coaxBoth','coaxRun','coaxSecondRun','coaxNote'])$(id).hidden=!enabled;if(enabled){playing=false;windingLeft=handDemoLeft=settingLeft=0;yaw=-.28;tilt=1.02;distance=13;flip=0;view='rear';setView('rear');yaw=-.28;tilt=1.02;$('viewCaption').textContent='세 축·관 확대 · 길이와 간격을 늘린 절개 모형';coaxDemo.setFocus('both');setCoaxFocus('both');$('partTitle').textContent='한 중심, 세 개의 회전';$('partEng').textContent='Coaxial seconds, minute & hour';$('partTag').textContent='중심은 초침 · 중간은 분침 · 바깥은 시침';$('specLabel').textContent='관찰';$('specValue').textContent='분침 한 바퀴 → 시침 한 칸';$('partDesc').textContent='초침은 가장 가는 초록 축에, 분침은 그 축을 감싸는 파란 관에, 시침은 바깥 금색 관에 붙습니다. 세 부품은 한 중심을 쓰지만 서로 고정되어 있지 않습니다. 왼쪽 3번 휠의 큰 바퀴가 4번 휠의 작은 피니언과 맞물립니다. 4번 휠과 초록 전달 기어는 같은 축에 고정되어 있습니다. 그 회전이 초록 중간 기어와 중앙 기어를 지나 초침축으로 이어집니다. 시침은 분침 쪽 감속 기어에서 힘을 받습니다.';$('locationChip').textContent='확대 절개 모형 · 두 관의 앞 절반을 제거했습니다';}else{target.set(0,0,0);distance=12.6;setView('dial');}sync();}
function setCoaxFocus(key){coaxDemo.setFocus(key);for(const [id,k] of [['coaxMinute','minute'],['coaxHour','hour'],['coaxSecond','second'],['coaxBoth','both']])$(id).setAttribute('aria-pressed',key===k);$('coaxNote').textContent=key==='second'?'① 금색 4번 휠과 ② 초록 전달 기어는 한 축에 고정되어 함께 돕니다. ③ 중간 기어를 거쳐 ④ 중앙 초침축이 돌고, 이 축이 분침관 안을 통과해 ⑤ 초침까지 이어집니다. 기어들은 무브먼트 쪽, 바늘들은 반대쪽입니다. 초침 한 바퀴 관찰을 눌러 연결 전체를 보세요.':key==='minute'?'① 파란 바퀴 → 파란 안쪽 관 → 긴 분침. 한 몸이므로 함께 돕니다. 금색 관은 이 관에 붙어 있지 않습니다.':key==='hour'?'② 파란 바퀴가 옆의 큰 바퀴를 돌립니다. 같은 옆 축의 작은 바퀴가 금색 큰 바퀴 → 바깥 관 → 짧은 시침을 더 천천히 돌립니다.':'가장 안쪽의 초록 축은 초침, 그 주위의 파란 관은 분침, 바깥 금색 관은 시침을 돌립니다. 두 관을 절개해 서로 닿지 않는 틈을 보여줍니다.';}
$('coaxToggle').onclick=()=>{if(coaxMode){setCoaxMode(false);choose('hands');}else setCoaxMode(true);};$('coaxMinute').onclick=()=>setCoaxFocus('minute');$('coaxHour').onclick=()=>setCoaxFocus('hour');$('coaxSecond').onclick=()=>setCoaxFocus('second');$('coaxSecondRun').onclick=()=>{if(crownPosition===2)setCrownPosition(0);setCoaxMode(true);setCoaxFocus('second');timeExperiment=true;seconds=smoothSeconds=handOffset=0;handDemoSpeed=7.5;handDemoLeft=60;sync();};$('coaxBoth').onclick=()=>setCoaxFocus('both');$('coaxRun').onclick=()=>{if(crownPosition===2)setCrownPosition(0);setCoaxMode(true);timeExperiment=true;playing=false;handOffset=0;seconds=smoothSeconds=0;handDemoSpeed=300;handDemoLeft=3600;sync();};
let pointer=null;const rc=new T.Raycaster();function visible(m){while(m){if(!m.visible)return false;m=m.parent;}return true;}
const hoverTip=document.createElement('div');hoverTip.id='partTooltip';hoverTip.setAttribute('role','tooltip');hoverTip.hidden=true;stage.append(hoverTip);
const canvas=renderer.domElement;canvas.style.touchAction='none';canvas.setAttribute('aria-label','자유 회전 3D 시계 · 드래그 회전 · Shift 드래그 이동 · 스크롤 확대');
function hitAt(e){const r=canvas.getBoundingClientRect();rc.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);return rc.intersectObjects(scene.children,true).find(h=>h.object.isMesh&&visible(h.object)&&(!h.object.material?.transparent||h.object.material.opacity>.2));}
function hoverAt(e){if(pointer?.moved){hoverTip.hidden=true;return;}const h=hitAt(e),m=h?.object,label=m?.userData.label||names[m?.userData.key]||({plate:'지판 · 부품을 지지하는 바탕',bridge:'브리지 · 회전축을 지지'}[m?.userData.key]);hoverTip.hidden=!label;if(!label){canvas.style.cursor='grab';return;}canvas.style.cursor='pointer';hoverTip.textContent=label;const r=stage.getBoundingClientRect();hoverTip.style.left=Math.max(8,Math.min(e.clientX-r.left+14,stage.clientWidth-230))+'px';hoverTip.style.top=Math.max(8,Math.min(e.clientY-r.top+16,stage.clientHeight-55))+'px';}
canvas.onpointerdown=e=>{if(e.button!==0&&e.button!==2)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,moved:false,pan:e.shiftKey||e.button===2};canvas.setPointerCapture(e.pointerId);hoverTip.hidden=true;canvas.style.cursor='grabbing';};
canvas.onpointermove=e=>{if(!pointer){if(e.pointerType!=='touch')hoverAt(e);return;}if(e.pointerId!==pointer.id)return;if(Math.hypot(e.clientX-pointer.sx,e.clientY-pointer.sy)>4)pointer.moved=true;if(pointer.moved){const r=canvas.getBoundingClientRect();if(pointer.pan)orbit.pan(e.clientX-pointer.x,e.clientY-pointer.y,r.height);else orbit.drag([pointer.x-r.left,pointer.y-r.top],[e.clientX-r.left,e.clientY-r.top],r.width,r.height);pointer.x=e.clientX;pointer.y=e.clientY;view='free';$('rear').setAttribute('aria-pressed',false);$('dialView').setAttribute('aria-pressed',false);$('viewCaption').textContent='자유 3D · 시점은 직접 조작할 때만 바뀝니다';}};
canvas.onpointerup=e=>{if(!pointer||e.pointerId!==pointer.id)return;const click=!pointer.moved&&!pointer.pan;pointer=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);canvas.style.cursor='grab';if(click){const h=hitAt(e),u=h?.object.userData;if(u?.chronoAction){advanced.press(u.chronoAction);}else if(u?.advancedPart){inspectAdvanced(u.advancedPart,u.focusIndex);}else if(u?.key&&names[u.key])choose(u.key);if(e.pointerType!=='touch')hoverAt(e);}};
canvas.onpointercancel=()=>{pointer=null;hoverTip.hidden=true;canvas.style.cursor='grab';};canvas.onlostpointercapture=()=>{if(pointer){pointer=null;hoverTip.hidden=true;canvas.style.cursor='grab';}};canvas.onpointerleave=()=>{if(!pointer)hoverTip.hidden=true;};canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener('wheel',e=>{e.preventDefault();hoverTip.hidden=true;orbit.zoom(e.deltaY);},{passive:false});
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(stage);resize();

function setCrownMode(enabled){if(enabled&&advanced){advanced.setView('none');$('handExperiment').hidden=step!==4;}if(enabled&&coaxMode)setCoaxMode(false);crownMode=enabled;$('handExperiment').hidden=enabled||step!==4;$('crownInspect').textContent=enabled?'전체 시계로 돌아가기':'용두 연결 구조 확대';$('crownInspect').setAttribute('aria-pressed',enabled);if(enabled){playing=false;setView('rear');yaw=.18;tilt=-.72;distance=10;highlight('crown');showPartLesson('crown','용두');$('partTitle').textContent=crownCorrection()?'용두 하나, 세 개의 선택 위치':'용두 하나, 감기와 시간 맞춤';$('partEng').textContent='Winding & hand setting';$('partTag').textContent='실제 모델의 부품을 분리해 관찰';$('partDesc').textContent='밀어 넣으면 감기 피니언과 감기 휠을 통해 태엽의 중심 축을 돌립니다. 한 칸 당기면 파란 조정축에서 다이얼 아래의 편심 핑거로 연결되어 날짜판을 한 칸 밉니다. 역방향에는 핑거가 물러나 날짜판은 움직이지 않습니다. 금색 요크는 고정 길이로 회전하며 홈을 잡아 연결 부품을 옮깁니다. 두 칸 당기면 연결 부품이 시간 맞춤 전달축과 맞물립니다. 이 축의 아래 기어가 분 휠을 돌리고, 분침과 시침이 함께 움직입니다. 캐넌 피니언의 마찰 결합이 미끄러져 주행 기어열은 강제로 돌리지 않습니다.';if(!crownCorrection())$('partDesc').textContent='밀어 넣으면 감기 기어를 통해 태엽을 감습니다. 한 칸 당기면 연결 부품이 시간 맞춤 기어를 선택합니다. 분 휠에서 분침과 시침으로 연결되므로 두 바늘이 함께 움직입니다. 기본 시계에는 날짜 조정 위치가 없습니다. 심화편에서는 중간 위치로 각 컴플리케이션을 조정합니다.';$('specLabel').textContent='조작';$('specValue').textContent='위치 선택 → 앞·뒤로 돌리기';$('locationChip').textContent='연결 구조 확대 · 직각 치형과 레버는 교육용 단순화';$('viewCaption').textContent='금색 요크: 연결 선택 · 파란 축: 선택한 동력 경로';}else{distance=12.6;setView('rear');highlight(selected);}sync();}
$('crownInspect').onclick=()=>setCrownMode(!crownMode);
document.querySelector('.workspace').prepend($('crownPanel'));

function drawSpring(ba){const key=charge.toFixed(4)+'|'+ba.toFixed(4);if(key===lastSpring)return;lastSpring=key;const attr=sg.attributes.position,inner=ba-TAU*(7+charge/100*5.625);for(let i=0;i<=600;i++){const u=i/600,r=.09+1.10*Math.pow(u,.82+charge/800),a=inner+(ba-inner)*u;attr.setXYZ(i*2,Math.cos(a)*r,Math.sin(a)*r,.31);attr.setXYZ(i*2+1,Math.cos(a)*r,Math.sin(a)*r,.49);}attr.needsUpdate=true;sg.computeVertexNormals();sg.computeBoundingSphere();}
function drawHair(a){const p=hg.attributes.position;for(let i=0;i<=300;i++){const u=i/300,r=.07+.48*u,t=(1-u)*(TAU*5+a);p.setXYZ(i,Math.cos(t)*r,Math.sin(t)*r,.28);}p.needsUpdate=true;hg.computeBoundingSphere();}
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;automaticWindPulse=Math.max(0,automaticWindPulse-dt);if(freeTurnLeft!==0){const da=Math.sign(freeTurnLeft)*Math.min(Math.abs(freeTurnLeft),dt*TAU);freeCrownTurn+=da;crownInput+=da;if(crownPosition===1){dateInputAngle+=da;correctionTravel+=Math.abs(da)/(TAU*1.5);}freeTurnLeft-=da;if(pendingDate&&correctionTravel>=CalendarMechanics.dateCorrectionGeometry.endProgress){advanced.quickDate(1);pendingDate=false;}}crownPull+=((crownPosition/2)-crownPull)*Math.min(1,dt*12);if(crownPosition===2&&settingLeft!==0){const ds=Math.sign(settingLeft)*Math.min(Math.abs(settingLeft),dt*300);handOffset+=ds;settingLeft-=ds;settingTurn+=ds/300*TAU;crownInput-=ds/3600*TAU;}if(windingLeft>0){const add=Math.min(windingLeft,dt*10);windingLeft-=add;charge+=add;windAngle+=add/100*TAU*5.625;crownInput-=add/100*TAU*5.625*44/34*24/18;if(windingLeft<.00001){windingLeft=0;sync();}}if(handDemoLeft>0){const ds=Math.min(handDemoLeft,dt*handDemoSpeed);handDemoLeft-=ds;seconds+=ds;smoothSeconds=seconds;}release=Math.max(0,release-dt);flip+=((view==='dial'?Math.PI:0)-flip)*(reduced?1:Math.min(1,dt*5));
if(playing&&crownPosition!==2){if(step===1){const ds=Math.min(charge/100*S.reserveSeconds,dt*(600+charge*60));seconds+=ds;charge-=ds/S.reserveSeconds*100;if(charge<=0){charge=0;playing=false;sync();}}else if(step>=3){fraction+=dt*8*rate;const n=Math.floor(fraction);if(n){fraction-=n;advance(n);}}}
smoothSeconds=rate>1||step<2?seconds:smoothSeconds+(seconds-smoothSeconds)*Math.min(1,dt*28);const ca=smoothSeconds/3600*TAU;for(const k of train){groups[k].visible=levels[k]<=step;groups[k].rotation.z=ca*S.ratios[k];groups[k].position.z=0;}
spring.visible=lid.visible=true;spring.position.z=0;lid.position.z=0;ratchetGroup.position.z=S.bridgeLift;lidDisk.visible=$('cover').checked;ratchetGroup.visible=true;lid.rotation.z=ca*S.ratios.barrel;ratchetGroup.rotation.z=-windAngle-lid.rotation.z;arborMarker.rotation.z=-windAngle;arborMarker.visible=true;arborMarker.position.z=0;drawSpring(ca*S.ratios.barrel);crown.visible=cw.visible=windingIdler.visible=true;cw.position.z=windingIdler.position.z=0;
const windOut=-windAngle*44/34;cwRotor.rotation.z=cwFace.rotation.z=windOut;
const meshPhase=(pa,pb,na,nb)=>((na+nb)*Math.atan2(pb[1]-pa[1],pb[0]-pa[0])+nb*Math.PI-Math.PI)/nb;
windingIdlerRotor.rotation.z=-windOut*34/32+meshPhase(crownXY,K.winding.idler,34,32);
// The ratchet shares the same winding angle; use a static phase to interleave teeth.
ratchetGroup.rotation.z=-windAngle-lid.rotation.z+meshPhase(K.winding.idler,W.barrel.p,32,44)-meshPhase(crownXY,K.winding.idler,34,32)*32/44;
crown.rotation.x=crownInput;windPinRotor.rotation.z=-windAngle*44/34*24/18;clutchRotor.rotation.z=crownInput;clutchDogs.rotation.x=crownInput;
const p=crownPull*2,seg=Math.min(1,Math.floor(p)),u=p-seg,sliderX=K.sliderX[seg]*(1-u)+K.sliderX[seg+1]*u;
const slipping=crownPosition===0&&(freeTurnLeft>0||automaticWindPulse>0);slidingClutch.position.x=sliderX-(slipping?.05*(1-Math.cos((crownInput-windPinRotor.rotation.z)*8)):0);slidingClutch.position.z=K.stemZ;
selectorLever.rotation.z=K.yokePose(slidingClutch.position.x).angle;selectorLever.position.z=K.stemZ+.23;yokeSlot.position.x=slidingClutch.position.x;yokeSlot.position.z=K.stemZ+.20;
crown.position.x=3.38+crownPull*.46;windingPin.position.z=crown.position.z=K.stemZ;keyless.visible=false;settingBridge.position.z=0;settingBridge.visible=step>=4||crownMode||crownPosition===2;
settingTop.rotation.z=(ca+handOffset/3600*TAU)*2/3;settingBottom.rotation.z=settingPhase+settingTop.rotation.z;clutchDogs.visible=crownPosition===0;clickPivot.visible=!crownMode||crownPosition===0;clickPivot.position.z=1.69;clickPivot.rotation.z=windingLeft>0||automaticWindPulse>0?Math.sin(windAngle*44)*.08:0;

fork.visible=step>=2;fork.position.z=1.06+S.bridgeLift;const balanceAngle=step>=3?S.balanceAngle(seconds+fraction/(2*S.frequency)):0;if(step>=3){forkShown=S.forkAngle(balanceAngle);}else forkShown+=((beats%2?.12:-.12)-forkShown)*Math.min(1,dt*25);forkRotor.rotation.z=forkBase+forkShown;balance.visible=step>=3;balance.position.z=.97+S.bridgeLift;br.rotation.z=balanceAngle;drawHair(br.rotation.z);bridge.visible=step>=3&&$('bridges').checked;bridge.position.z=S.bridgeLift;
motion.visible=face.visible=step>=4||crownPosition===2;motion.position.z=0;for(const k of ['cannon','minute','hour'])groups[k].rotation.z=(ca+handOffset/3600*TAU)*S.ratios[k];face.position.z=-.95-0;dial.visible=!$('openDial').checked;brand.visible=!$('openDial').checked;const handAngles=S.handAngles(smoothSeconds,handOffset);hh.rotation.z=handAngles.hour;mh.rotation.z=handAngles.minute;sh.rotation.z=handAngles.second;const seeShaft=crownMode||crownPosition===1||advanced?.xray||step===4&&routeFocus===0;plateMesh.material.transparent=seeShaft;plateMesh.material.opacity=seeShaft?.16:1;plateMesh.material.depthWrite=!seeShaft;if(seeShaft)dial.visible=brand.visible=false;
if(crownMode){cw.visible=windingIdler.visible=crownPosition===0;settingBridge.visible=crownPosition===2;plate.visible=bridge.visible=fork.visible=balance.visible=face.visible=false;for(const k of train)groups[k].visible=k==='barrel'&&crownPosition===0;spring.visible=lid.visible=crownPosition===0;motion.visible=crownPosition===2;ratchetGroup.visible=arborMarker.visible=crownPosition===0;lidDisk.visible=false;target.set(1.1,.4,.55);flip=0;for(const [part,active] of [[windingIdler,crownPosition===0],[cw,crownPosition===0],[ratchetGroup,crownPosition===0],[windingPin,crownPosition===0],[settingBridge,crownPosition===2]])part.traverse(m=>{if(m.isMesh){m.material.transparent=!active;m.material.opacity=active?1:.22;m.material.depthWrite=active;}});}else{plate.visible=true;for(const part of [cw,windingIdler,ratchetGroup,windingPin,settingBridge])part.traverse(m=>{if(m.isMesh){m.material.transparent=false;m.material.opacity=1;m.material.depthWrite=true;}});if(!coaxMode)target.set(0,0,0);}
secondsShaft.visible=secondsCollar.visible=advanced?.mode!=='chronograph';secondsTrain.visible=step>=4&&!crownMode;secondsTrain.position.z=0;secondsRotors.forEach((g,i)=>g.rotation.z=secondsPhase[i]+ca*cs.ratios[i]);
root.visible=!coaxMode&&(!advanced||!advanced.isolated);advanced?.tick(dt,{seconds:smoothSeconds,offset:handOffset,step,explosion:0,windAngle,crownMode,crownPosition,dateInputAngle,correctionProgress:Math.min(1,correctionTravel),correctionDirection,correctionBusy:Math.abs(freeTurnLeft)>0,dateReverse:crownPosition===1&&freeTurnLeft>0});if(advanced?.isolated){flip=0;target.set(0,0,0);}if(courseChapter===5){ratchetGroup.visible=arborMarker.visible=true;lidDisk.visible=false;}
coaxDemo.group.visible=coaxMode;coaxDemo.update(smoothSeconds,handOffset);if(coaxMode){flip=0;target.set(.65,.05,.30);}const pose=orbit.update(dt);camera.up.fromArray(pose.up);camera.position.fromArray(pose.position);camera.lookAt(new T.Vector3(...pose.target));renderer.domElement.dataset.camera=JSON.stringify(orbit.state);renderer.domElement.dataset.keyless=JSON.stringify({position:crownPosition,input:crownInput,date:advanced.state.date,dateInput:dateInputAngle,slider:slidingClutch.position.x,yokeLength:yokeArm.geometry.parameters.width*yokeArm.scale.x,handOffset,charge,ratchetVisible:ratchetGroup.visible,windingPinAngle:windPinRotor.rotation.z,automaticFreewheel:slipping,clickVisible:clickPivot.visible,clickKey:clickPivot.children[0].userData.key,correctionProgress:correctionTravel,busy:!!(freeTurnLeft||windingLeft||settingLeft)});renderer.domElement.dataset.timing=JSON.stringify({seconds:seconds+fraction/(2*S.frequency),rate,playing,balance:balanceAngle,fork:forkShown});renderer.render(scene,camera);if(now-lastUI>120){if(mechanismAudit.enabled)renderer.domElement.dataset.meshAudit=JSON.stringify(mechanismAudit.snapshot(T,scene));readings();updateCrownUI();window.watchJourney.update({charge,windAngle,seconds,winding:windingLeft>0});lastUI=now;}requestAnimationFrame(frame);}

function advancedPresentation(mode,isolated){if(mode==='calendar'&&!isolated)$('openDial').checked=true;setView(mode==='calendar'&&!isolated?'dial':'rear');yaw=.08;tilt=isolated?.35:.38;distance=isolated?13:14.5;target.set(0,0,0);$('locationChip').textContent=isolated?'동일한 부품을 확대 · 축 간 연결을 따라가세요':'기존 무브먼트에 장착 · 입력과 출력이 원래 축으로 이어집니다';$('viewCaption').textContent='드래그로 회전하고 연결부 확대에서 축을 따라가세요';}
function inspectAdvanced(k,i){if(advanced.mode===k&&i!==undefined){$('advancedParts').hidden=false;$('journeySteps').children[i]?.click();return;}const d=data[k];$('partTitle').textContent=names[k];['partEng','partTag','partDesc','specLabel','specValue'].forEach((id,j)=>$(id).textContent=d[j]);if($('advancedParts'))$('advancedParts').hidden=true;showPartLesson(k,names[k]);document.querySelector('.details').scrollTop=0;}
function advancedFocus(mode,i){document.querySelector('.details').scrollTop=0;$('partDesc').textContent=$('journeyNote').textContent;document.querySelectorAll('#advancedParts button').forEach((b,j)=>b.setAttribute('aria-pressed',i===j));if(!advanced?.isolated)advancedPresentation(mode,false);highlight(mode==='automatic'&&i===3?'barrel':mode==='calendar'?'motion':mode==='chronograph'?'seconds':'none');$('observeTitle').textContent=window.watchJourney?document.getElementById('journeySteps').children[i]?.textContent||names[mode]:names[mode];$('observeText').textContent='강조한 부품과 연결된 축을 살펴보고 위 조작 버튼으로 움직여 보세요.';}
function selectAdvanced(mode){if(step<4)setStep(4);if(coaxMode)setCoaxMode(false);if(crownMode)setCrownMode(false);advanced.setView(mode);$('handExperiment').hidden=mode!=='none';document.body.classList.toggle('advancedLesson',mode!=='none');document.querySelector('.details').scrollTop=0;if(mode==='none'){choose('hands');return;}
 courseChapter=5+ADVANCED_MODES.indexOf(mode);const n=courseChapter,d=data[mode];document.querySelectorAll('[data-part]').forEach(b=>{const a=ADVANCED_MODES.indexOf(b.dataset.part);b.hidden=a>=0&&b.dataset.part!==mode;});
 const heads={gmt:['하루 한 바퀴로, 다른 시간대를 읽습니다.','시침의 회전을 나누고 독립 GMT 바늘을 조정해 보세요.','GMT'],moon:['하루 한 칸이, 달의 모양을 만듭니다.','날짜와 같은 하루 입력이 59치 달판과 표시창으로 이어집니다.','문페이즈'],automatic:['손목의 움직임이 태엽을 감습니다.','로터부터 원래 태엽 중심까지, 같은 시계 안에서 연결을 따라갑니다.','오토매틱'],calendar:['시침의 회전이 날짜를 넘깁니다.','기존 시침 관에서 출발해 24시간 휠과 날짜판으로 이어집니다.','날짜'],chronograph:['시계는 계속 가고, 측정만 멈춥니다.','Seiko 6139A의 컬럼 휠·수직 클러치·회전 해머를 살펴봅니다.','크로노그래프']}[mode];
 $('pageTitle').textContent=heads[0];$('pageSub').textContent=heads[1];$('chapter').textContent='0'+(n+1)+' / 08 · '+heads[2];
 document.querySelectorAll('[data-step]').forEach(b=>{const active=+b.dataset.step===n;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'step':'false');});
 $('partTitle').textContent=names[mode];['partEng','partTag','partDesc','specLabel','specValue'].forEach((id,i)=>$(id).textContent=d[i]);showPartLesson(mode,names[mode]);
 $('lessonNo').textContent='0'+(n+1);$('lessonTitle').textContent=heads[0];$('lessonText').textContent=heads[1];$('next').textContent=n===9?'01장부터 다시 보기':'다음 · '+(n===5?'날짜 기구':'크로노그래프');
 document.querySelectorAll('[data-part]').forEach(b=>{b.classList.toggle('active',b.dataset.part===mode);b.setAttribute('aria-pressed',b.dataset.part===mode);});
 window.watchJourney.setStep(n);let subparts=$('advancedParts');if(!subparts){subparts=document.createElement('div');subparts.id='advancedParts';subparts.className='adv-tabs';$('partDesc').after(subparts);}subparts.hidden=false;subparts.replaceChildren();Array.from($('journeySteps').children).forEach((source,i)=>{const b=document.createElement('button');b.className='smallbtn';b.textContent=source.textContent;b.onclick=()=>source.click();subparts.append(b);});advancedPresentation(mode,false);advanced.setFocus(0);sync();
}
advanced=createAdvancedWatch(T,scene,root,face,S,{
 project:obj=>{obj.updateWorldMatrix(true,false);const v=obj.getWorldPosition(new T.Vector3()).project(camera),r=canvas.getBoundingClientRect(),s=stage.getBoundingClientRect();return {x:(v.x+1)*r.width/2+r.left-s.left,y:(1-v.y)*r.height/2+r.top-s.top,visible:v.z>=-1&&v.z<=1&&Math.abs(v.x)<1&&Math.abs(v.y)<1};},
 view:selectAdvanced,crown:setCrownPosition,turnCrown,correctionSources:()=>[crown,slidingClutch,selectorLever,yokeSlot],environment:()=>({charge,crown:crownPosition,rate,chapter:courseChapter,demoRemaining:handDemoLeft}),presentation:advancedPresentation,focus:advancedFocus,
 addWind:amount=>{if(amount>0&&advanced?.mode==='automatic')automaticWindPulse=.08;charge=Math.min(100,charge+amount);windAngle+=amount/100*TAU*5.625;sync();},
 wind:()=>{setCrownPosition(0);$('wind').click();},
 run:()=>{if(step<4){const savedCharge=charge;setStep(4);charge=savedCharge;}setCrownPosition(0);playing=true;timeExperiment=false;handDemoLeft=0;rate=1;sync();},
 speed:()=>{rate=rate===1?10:rate===10?60:1;$('rate').textContent=rate+'× 빠르게';},
 stopDemo:()=>{handDemoLeft=0;sync();},
 advanceHours:h=>{playing=false;setCrownPosition(0);handDemoSpeed=21600;handDemoLeft=h*3600;timeExperiment=true;sync();},
 safeTime:()=>{playing=false;handDemoLeft=0;handOffset=21600-seconds;sync();},
 midnight:()=>{setCrownPosition(0);playing=false;handOffset=79200-seconds;advanced.state.lastClock=79200;timeExperiment=true;handDemoSpeed=900;handDemoLeft=10800;sync();}
},toothShape);

setStep(0);sync();readings();$('loading').remove();requestAnimationFrame(frame);window.insideLab={getState:()=>({step,seconds,beats,charge,playing,view,centerAngle:seconds/3600*TAU,hourAngle:-(seconds+handOffset)/43200*TAU,crownPosition,handOffset,settingLeft})};
window.watchApp={setStep,resetCrown:()=>setCrownPosition(0),focus:i=>document.getElementById('journeySteps').children[i]?.click(),crown:setCrownMode,coax:setCoaxMode};
}catch(e){if($('loading'))$('loading').textContent=e.message;console.error(e);}
})();

