window.createRatchetCutaway=function(parent){
 const el=document.createElement('section');el.className='ratchet-cutaway';parent.insertBefore(el,parent.querySelector('svg'));
 const shape=RatchetContact.points.map(([x,y],i)=>(i?'L':'M')+x.toFixed(3)+' '+(-y).toFixed(3)).join('')+'Z';
 const one=(id,cx)=>`<g transform="translate(${cx} 170)"><g id="ratchetFrame${id}"><circle r="126" fill="#eff7fc" stroke="#268bb0" stroke-width="3" stroke-dasharray="9 5"/><g id="ratchetWheel${id}"><path d="${shape}" fill="#eacb85" stroke="#9b681e" stroke-width="1.5"/><circle r="23" fill="white" stroke="#9b681e" stroke-width="3"/><path d="M-55 0H55M0 -55V55" stroke="#bb8a35" stroke-width="3"/></g><path id="ratchetSpring${id}" fill="none" stroke="#188a73" stroke-width="3"/><path id="ratchetPawl${id}" stroke="#784112" stroke-width="1.5"/><circle cx="116" cy="0" r="7" fill="#248db2" stroke="white" stroke-width="2"/><circle id="ratchetContact${id}" r="3.5" fill="#d04e30"/></g></g><text id="ratchetState${id}" x="${cx}" y="26" text-anchor="middle"></text><text id="ratchetMotion${id}" x="${cx}" y="321" text-anchor="middle"></text>`;
 el.innerHTML=`<h3>래칫 내부를 보세요: 걸리거나, 타고 넘어갑니다.</h3><p>금색은 <b>출력축에 붙은 비대칭 톱니</b>, 주황색은 <b>입력 기어에 달린 걸쇠</b>입니다. 초록 복귀 스프링이 걸쇠를 톱니 쪽으로 누릅니다.</p><div class="ratchet-controls"><button data-ratchet-action="rotorRight">↻ 로터 시계 방향</button><button data-ratchet-action="rotorLeft">↺ 반시계 방향</button><button data-ratchet-action="autoStep">접촉 한 단계</button><button id="ratchetPause" data-ratchet-action="autoPause">일시 정지</button><button id="ratchetReference" aria-pressed="true">걸쇠 기준 · 상대운동</button></div><p id="ratchetReferenceNote">걸쇠의 회전을 따라가는 시점입니다. 잠긴 쪽은 함께 돌기 때문에 상대 위치가 그대로이고, 헛도는 쪽은 톱니가 걸쇠 밑으로 지나갑니다.</p><svg viewBox="0 0 720 350" role="img" aria-label="A와 B 클러치의 비대칭 톱니, 고정 길이 걸쇠, 복귀 스프링 접촉 확대">${one('A',175)}${one('B',545)}</svg><div class="ratchet-reading"><p><b>① 잠김</b> 걸쇠 끝이 톱니의 가파른 면에 걸립니다. 입력과 출력이 붙잡혀 함께 돕니다.</p><p><b>② 공회전</b> 경사면이 걸쇠를 밀어 올립니다. 꼭대기를 넘으면 스프링이 다음 홈으로 돌려보냅니다.</p></div><p class="ratchet-limit">걸쇠식 일방향 클러치를 단순화한 접촉 모형입니다. 걸쇠 길이를 유지하며 톱니 표면과의 접점을 계산합니다. 실제 무브먼트별 내부 구조와 치수는 다르며, 마찰·탄성력을 계산하는 시뮬레이션은 아닙니다.</p>`;
 let relative=true;const $=id=>el.querySelector('#'+id);
 el.querySelectorAll('[data-ratchet-action]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.ratchetAction)?.click());
 $('ratchetReference').onclick=()=>{relative=!relative;$('ratchetReference').setAttribute('aria-pressed',relative);$('ratchetReference').textContent=relative?'걸쇠 기준 · 상대운동':'고정 시점 · 전체 회전';$('ratchetReferenceNote').textContent=relative?'걸쇠의 회전을 따라가는 시점입니다. 잠긴 쪽은 함께 돌기 때문에 상대 위치가 그대로이고, 헛도는 쪽은 톱니가 걸쇠 밑으로 지나갑니다.':'입력 기어에 달린 걸쇠도 함께 회전합니다. 잠긴 쪽은 걸쇠와 금색 출력 휠이 한 덩어리로 돕니다. 이 버튼은 아래 3D 카메라에 영향을 주지 않습니다.';};
 return {update(poses,paused){$('ratchetPause').textContent=paused?'계속 관찰':'일시 정지';poses.forEach((p,i)=>{const id=i?'B':'A',x=p.x,y=-p.y,dx=x-116,dy=y,nx=-dy/RatchetContact.length*5,ny=dx/RatchetContact.length*5;
 $('ratchetFrame'+id).setAttribute('transform',`rotate(${relative?0:-p.input*180/Math.PI})`);$('ratchetWheel'+id).setAttribute('transform',`rotate(${-p.phase*180/Math.PI})`);
 $('ratchetPawl'+id).setAttribute('d',`M${116+nx} ${ny}L${x+dx*-.18+nx*.45} ${y+dy*-.18+ny*.45}L${x} ${y}L${116-nx} ${-ny}Z`);$('ratchetPawl'+id).setAttribute('fill',p.locked?'#df811d':'#e9ac61');
 $('ratchetSpring'+id).setAttribute('d',`M126 -35Q149 -2 126 15Q111 23 ${116+dx*.35} ${dy*.35}`);
 $('ratchetContact'+id).setAttribute('cx',x);$('ratchetContact'+id).setAttribute('cy',y);
 $('ratchetState'+id).textContent=id+' · '+(p.locked?'잠김 — 가파른 면에서 걸림':'공회전 — 경사면을 타고 넘음');$('ratchetMotion'+id).textContent=p.locked?'입력과 출력 함께 회전 · 상대운동 0':'걸쇠는 들렸다 내려옴 · 출력과 따로 회전';
 el.dataset['pawl'+id]=p.angle.toFixed(6);el.dataset['locked'+id]=String(p.locked);
 });}};
};
