const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),A=require('../automatic-mechanics'),D=require('../car-drivetrain');
const near=(a,b,e=1e-7)=>assert(Math.abs(a-b)<e,`${a} != ${b}`);
function willis(v){near(30*v.sun+54*v.front,84*v.output);near(30*v.sun+66*v.output,96*v.rearCarrier);}
for(const g of ['N','1','2','3','R']){const v=A.speeds(g);willis(v);if(g==='1')near(v.rearCarrier,0);if(g==='2')near(v.sun,0);if(g==='3')near(v.sun,v.front);if(g==='R')assert(v.output<0);}
function inside(p,P){let yes=false;for(let i=0,j=P.length-1;i<P.length;j=i++){const a=P[i],b=P[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
const outlines={};for(const n of [12,18,30])outlines[n]=D.gearOutline(n,A.spec.module);const internals={54:A.internalOutline(54),66:A.internalOutline(66)};
function rotate([x,y],a){return [x*Math.cos(a)-y*Math.sin(a),x*Math.sin(a)+y*Math.cos(a)];}
function meshCheck(set){for(const p of set.planets){near(Math.hypot(p.center[0],p.center[1]),(30+p.n)*.03);near(p.center[0],p.pin[0]);near(p.center[1],p.pin[1]);near(p.center[2],set.z);assert.deepEqual(p.scale,[1,1,1]);for(const vertex of outlines[p.n]){let [x,y]=rotate(vertex,p.angle);x+=p.center[0];y+=p.center[1];if(Math.hypot(x,y)<.96)assert(!inside(rotate([x,y],-set.sunAngle),outlines[30]),'planet penetrates sun');if(Math.hypot(x,y)>set.n*.03-.061)assert(inside(rotate([x,y],-set.ringAngle),internals[set.n]),'planet penetrates ring');}}}
function validate(q){q.sets.forEach(meshCheck);for(const set of q.sets)assert(Math.min(q.shaftSpans.sun[1],set.z+.12)-Math.max(q.shaftSpans.sun[0],set.z-.12)>0,'sun shaft misses gear');for(const p of q.packs){assert(p.centers[0]-p.thickness/2>=p.backFace-1e-8,'first plate through backstop');p.scales.forEach(s=>assert.deepEqual(s,[1,1,1]));for(let i=1;i<p.centers.length;i++)assert(p.centers[i]-p.centers[i-1]>=p.thickness-1e-8,'plates overlap');near(p.pistonFace,p.centers[5]+p.thickness/2);}assert(q.lockGap>=-1e-8,'lockup through cover');willis(q.state.angles);willis(q.state.velocity);}
const t=new A.State();t.running=true;t.selector='1';for(const g of ['2','3','1','N','R','N','1']){t.speed=0;t.setSelector(g);for(let i=0;i<220;i++){t.tick(.02);willis(t.velocity);willis(t.angles);}assert.equal(t.gear,g);}
t.speed=30;t.setSelector('R');assert.notEqual(t.selector,'R');t.running=false;const frozen=JSON.stringify(t.snapshot());t.tick(.05);assert.equal(JSON.stringify(t.snapshot()),frozen);
const shift=new A.State();shift.selector='2';shift.running=true;shift.request('2');for(let i=0;i<13;i++){shift.tick(.05);near(shift.velocity.sun, A.speeds('1',shift.inputRate).sun);}for(let i=0;i<50;i++)shift.tick(.05);near(shift.velocity.sun,0);near(shift.apply.B2,1);
if(process.argv[2]){global.window=global;global.AutoMechanics=A;global.CarDrive=D;eval(fs.readFileSync(path.join(__dirname,'../automatic-model.js'),'utf8'));const m=createAutomaticModel(require(path.resolve(process.argv[2])));let count=0;
 for(const g of ['1','2','3','R']){const s=new A.State();s.gear=s.target=g;s.selector=g;s.speed=35;s.running=true;s.apply={C1:0,C2:0,B2:0,B3:0};for(const k of A.devices[g])if(k in s.apply)s.apply[k]=1;for(let i=0;i<180;i++){s.tick(.05);m.update(s.snapshot());validate(m.audit());count++;}}
 const s=new A.State();s.running=true;s.speed=80;for(let i=0;i<320;i++){s.tick(.05);m.update(s.snapshot());validate(m.audit());count++;}assert.equal(s.gear,'3');near(s.lock,1);near(m.audit().lockGap,0);near(s.coupling,1);
 const good=m.audit();for(const fault of [q=>q.sets[0].planets[0].center[0]+=.2,q=>q.sets[0].planets[0].angle+=Math.PI/12,q=>q.packs[0].centers[1]=q.packs[0].centers[0],q=>q.lockGap=-.02]){const bad=structuredClone(good);fault(bad);assert.throws(()=>validate(bad));}console.log(`PASS ${count} rendered gear/shift/lockup poses; 4 injected contact/phase faults rejected`);
}
console.log('PASS Simpson ratios, Willis constraints, forward/reverse interlock, pause and contact-before-synchronization');

const reverseExit=new A.State();reverseExit.gear='R';reverseExit.selector='R';reverseExit.speed=0;reverseExit.setSelector('D');assert.equal(reverseExit.target,'1');assert(reverseExit.transition);

if(process.argv[3]){const all=JSON.parse(fs.readFileSync(process.argv[3],'utf8')),get=n=>all.find(x=>x.name===n);for(const x of all)validate(x.audit);assert.equal(get('fill').state.phase,'틈 메우기');assert(get('fill').state.apply.B2<1);assert.equal(get('friction').state.apply.B2,1);assert(get('friction').state.velocity.sun<0);near(get('second').state.velocity.sun,0);assert.equal(get('third').state.apply.B2,1);assert(get('third').state.velocity.sun>0);assert(get('reverse').state.velocity.output<0);assert.deepEqual(get('reverse').state.angles,get('paused').state.angles);assert.deepEqual(get('reverse').state.camera,get('paused').state.camera);near(get('automaticLock').state.lock,1);near(get('automaticLock').state.coupling,1);console.log('PASS '+all.length+' browser contact/shift/lockup snapshots and chapter camera/pause invariants');}
