const assert=require('node:assert/strict'),M=require('../car-mechanics.js');
const near=(a,b,t=1e-6)=>assert(Math.abs(a-b)<t,`${a} != ${b}`);
for(let d=0;d<=1440;d+=3){const p=M.bank.map(b=>M.pose(d+b.offset));near(p[0].pistonY,p[3].pistonY);near(p[1].pistonY,p[2].pistonY);near(p[0].pin[0],-p[1].pin[0]);near(p[0].pin[1],-p[1].pin[1]);assert.equal(p.filter(c=>c.stroke===2).length,1);}
assert.deepEqual([380,560,740,920].map(d=>M.bank.find(b=>M.pose(d+b.offset).stroke===2).number),[1,3,4,2]);
assert(M.operation(20,100).duration>M.operation(20,0).duration);assert(M.operation(20).injection);assert(!M.operation(250).injection);
assert(M.operation(340,50,20).spark);assert(!M.operation(340,50,8).spark);assert(!M.operation(340,50,20,false).spark);
for(let t=40;t<=105;t++){const s=M.cooling(t);near(s.radiator+s.bypass,1);assert(s.lift>=0&&s.lift<=.22);}
assert.equal(M.cooling(60).radiator,0);assert.equal(M.cooling(95).bypass,0);
function validate(a){const s=a.systems;assert(s);near(s.throttleAngle,M.operation(s.degrees,s.settings.pedal).opening);assert.deepEqual(s.throttleScale,[1,1,1]);near(s.thermostat.discDistance,.453);near(s.thermostat.lift,M.cooling(s.settings.temperature).lift);near(s.thermostat.radiator+s.thermostat.bypass,1);near(s.driveAngle,s.pumpAngle);
 for(const u of s.units){const m=u.measurement;near(m.degrees,s.degrees+u.offset);near(m.rodLength,2.7);near(m.bigEndGap,0);near(m.smallEndGap,0);assert.deepEqual(m.rodScale,[1,1,1]);for(const c of m.contacts){near(c.gap,0,6e-6);assert(c.tangent<c.bucketRadius-.02);assert(c.pistonClearance>.25);}}
 if(s.units.length){for(let i=1;i<s.units.length;i++){const front=s.units[i-1],rear=s.units[i],span=(u,ends)=>ends.map(p=>p[2]+u.z).sort((a,b)=>a-b);for(const [a,b] of [[front.measurement.mainJournals[0],rear.measurement.mainJournals[1]],...front.measurement.camShafts.map((a,j)=>[a,rear.measurement.camShafts[j]])]){near(a[0][0],b[0][0]);near(a[0][1],b[0][1]);const az=span(front,a),bz=span(rear,b);assert(Math.min(az[1],bz[1])-Math.max(az[0],bz[0])>.10,'common shafts must overlap axially');}}}
 const links=s.waterEndpoints,route=id=>links.find(r=>r.id===id);const same=(a,b)=>a.forEach((x,i)=>near(x,b[i]));same(route('pump-jacket').end,route('jacket').start);same(route('jacket').end,route('hot-radiator').start);same(route('jacket').end,route('bypass').start);same(route('hot-radiator').end,route('radiator').start);same(route('radiator').end,route('radiator-inlet').start);same(route('radiator-inlet').end,route('main-valve').start);same(route('bypass').end,route('bypass-valve').start);same(route('main-valve').end,route('mixed-pump').start);same(route('bypass-valve').end,route('mixed-pump').start);
}
if(process.argv[2]){const samples=require(require('node:path').resolve(process.argv[2]));samples.forEach(validate);const bank=samples.filter(s=>s.systems.chapter===3);assert(bank.length>10);assert(Math.max(...bank.map(s=>s.degrees))-Math.min(...bank.map(s=>s.degrees))>=720);for(const fault of [s=>s.systems.units[0].measurement.rodLength+=.2,s=>s.systems.throttleScale[0]=1.3,s=>s.systems.thermostat.discDistance+=.1,s=>s.systems.waterEndpoints.find(r=>r.id==='radiator').end[0]+=.1]){const bad=structuredClone(bank[0]);fault(bad);assert.throws(()=>validate(bad));}console.log(`PASS ${samples.length} rendered system snapshots; 4 injected faults rejected`);}
console.log('PASS firing order, opposed throws, 720-degree phase, injection/ignition, thermostat branches');
