global.CarRoad=require('../car-road');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),M=require('../car-metrics'),K=require('../car-mechanics'),D=require('../car-drivetrain');
const near=(a,b,e=1e-6)=>assert(Math.abs(a-b)<e,`${a} != ${b}`);
for(const pedal of [0,35,100])for(const rpm of [1000,1500,5000])for(const advance of [0,18,40]){const s={pedal,rpm,advance},c=M.cycle(s);let w=0;for(const p of c.points){const g=M.geometry(p.d);assert(p.pressure>0);near(p.force,(p.pressure-M.spec.ambient)*g.area);near(p.torque,p.force*g.lever);w+=p.torque*Math.PI/180;}near(c.mean,w/(4*Math.PI));near(M.bank(412,s).mean,c.mean*4);near(M.bank(412,s,true).mean,c.mean);near(M.bank(412,s).power,c.mean*4*rpm*Math.PI*2/60/1000);}
near(M.geometry(0).lever,0);near(M.geometry(180).lever,0);near(M.geometry(360).lever,0);assert(M.sample(320).torque<0);assert(M.sample(400).torque>0);assert(M.cycle({ignition:false}).mean<0);assert(M.cycle({pedal:100}).mean>M.cycle({pedal:0}).mean);assert(M.cycle({advance:0}).peakAt>M.cycle({advance:18}).peakAt);assert(M.cycle({rpm:3000}).peakAt>M.cycle({rpm:1500}).peakAt);near(M.cycle({rpm:5000}).duration/M.cycle({rpm:1500}).duration,5000/1500);assert(M.cycle({rpm:5000}).mean<M.cycle({rpm:1500}).mean);assert(M.cycle({advance:18}).mean>M.cycle({advance:40}).mean);
near(M.wheel(100,'N').force,0);near(M.wheel(100,'1',1).force,0);near(M.wheel(100,'1').force,100*4*3*.9/.31);assert(M.wheel(100,'R').force<0);
for(let i=0;i<=100;i++){const b=M.brake(i/100);near(b.pistonForce,b.pressure*Math.PI*.048**2/4);near(b.clampForce,b.pistonForce*2);near(b.torque,b.clampForce*.35*.12);if(i<=18)near(b.bar,0);}
for(const split of [-1,-.4,0,.4,1]){const a=M.road(split),b=M.road(split,true);near(a.leftSpeed+a.rightSpeed,2);near(b.leftSpeed,b.rightSpeed);if(split){near(a.outer-a.inner,1.5*Math.PI/2);near((a.leftRadius+a.rightRadius)/2,a.radius);near(b.slip,(a.outer-a.inner)/2);near(a.leftRadius/a.radius,a.leftSpeed);near(a.rightRadius/a.radius,a.rightSpeed);}}
function validate(a){const s=a.systems||a;assert(s.jacket.radius>s.jacket.linerOuterRadius);for(let i=0;i<2;i++){const f=s.oilContacts[i];near(f.center[0],0);near(f.center[1],0);assert(f.radius-f.tube>.16&&f.radius+f.tube<.175);}for(const f of s.oilContacts.slice(2))assert(f.radius-f.tube>=.08&&f.radius+f.tube<=.086);}
if(process.argv[2]){const T=require(path.resolve(process.argv[2]));global.window=global;global.CarMechanics=K;global.CarMetrics=M;global.CarDrive=D;global.document={createElement:()=>({width:96,height:96,getContext:()=>({beginPath(){},arc(){},fill(){},fillText(){}})})};for(const f of ['car-model.js','car-systems.js','car-vehicle.js'])eval(fs.readFileSync(path.join(__dirname,'..',f),'utf8'));const engine=createCarModel(T),systems=createCarSystems(T,engine),vehicle=createCarVehicle(T);systems.setChapter(1);systems.setSettings({});systems.update(20);assert(systems.audit().airVisible);
 for(const mode of [1,2,3,4,5]){engine.setChapter(mode);systems.setChapter(mode);for(let d=0;d<=720;d+=30){engine.update(d);systems.update(d);const a=engine.audit();near(a.rodLength,2.7);near(a.bigEndGap,0);near(a.smallEndGap,0);if(a.forceAnnotation.visible&&M.sample(d).force>0){near(a.forceAnnotation.direction[1],-1);near(a.forceAnnotation.origin[1]-a.forceAnnotation.length,a.forceAnnotation.pistonTop,1e-5);}validate(systems.audit());}}
 vehicle.setMode(7);vehicle.setSettings({split:.4});vehicle.tick(.1,.1);const a=vehicle.audit();vehicle.setSettings({locked:true});vehicle.tick(.1,.1);const b=vehicle.audit();near(b.diffAngles[0]-a.diffAngles[0],b.diffAngles[1]-a.diffAngles[1]);near(b.bevelAngles.relative,a.bevelAngles.relative);vehicle.setSettings({locked:false});vehicle.tick(.1,.1);const c=vehicle.audit();assert(c.diffAngles[0]-b.diffAngles[0]<c.diffAngles[1]-b.diffAngles[1]);
 const good=systems.audit();for(const fault of [s=>s.jacket.radius=.7,s=>s.oilContacts[0].radius=.3]){const bad=structuredClone(good);fault(bad);assert.throws(()=>validate(bad));}console.log('PASS 125 rendered engine/system poses, force annotation contact, oil/jacket locations, axle locking; 2 faults rejected');
}
console.log('PASS 27 pressure cycles, work/force/torque units, timing/RPM response, cylinder displacement, drive/hydraulic/road constraints');

if(process.argv[3]){const samples=JSON.parse(fs.readFileSync(process.argv[3],'utf8')),get=n=>samples.find(s=>s.name===n),m=n=>get(n).metrics;
 assert(m('timing18').mean>m('timing0').mean);assert(m('timing18').mean>m('timing40').mean);assert(m('timing0').peakAt>m('timing18').peakAt);assert.deepEqual(get('timing18').state.camera,get('timing40').state.camera);
 near(m('fourSameCylinder').bank,m('fourSameCylinder').mean*4);near(m('fourSameTotal').bank,m('fourSameTotal').mean);assert(m('powerStroke').torque>0);assert(get('powerStroke').audit.systems.airVisible);
 validate(get('oil').audit);assert(!get('oil').audit.systems.jacket.visible);assert(get('coolantHot').audit.systems.jacket.visible);near(get('coolantHot').audit.systems.thermostat.radiator,1);
 assert(m('diffOpen').road.leftSpeed<m('diffOpen').road.rightSpeed);near(m('diffLocked').road.leftSpeed,m('diffLocked').road.rightSpeed);assert(m('diffLocked').road.slip>0);assert.deepEqual(get('diffOpen').state.camera,get('diffLocked').state.camera);near(m('diffPausedA').road.angle,m('diffPausedB').road.angle);
 near(m('brakeFull').brake.foot,300);near(m('brakeFull').brake.clampForce,13824);console.log('PASS '+samples.length+' browser samples: ignition, displacement, contact layers, road lock, pause, hydraulics, camera stability');
}
