const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),T=require(path.resolve(__dirname,'../../three-0.160.1.cjs')),D=require('../ev-data'),M=require('../ev-model');
assert.equal(D.titles.length,12);assert.equal(D.lessons.length,3);
const s={phase:0,running:false,rate:1,pedal:100,rpm:1800,series:96,parallel:2};
const m=D.calculate(s);assert.equal(m.voltage,355.20000000000005);assert.ok(Math.abs(m.capacity-35.52)<1e-9);assert.equal(m.torque,180);assert.equal(m.wheelRPM,200);assert.equal(m.wheelTorque,1555.2);assert.ok(D.calculate({...s,rpm:6000}).power<60.01);assert.equal(D.calculate({...s,pedal:0}).torque,0);assert.ok(D.calculate({...s,parallel:3}).capacity>m.capacity);assert.ok(D.calculate({...s,series:108}).current<m.current);
D.advance(s,.05);assert.equal(s.phase,0);s.running=true;D.advance(s,.05);const once=s.phase;s.rate=2;D.advance(s,.05);assert.ok(Math.abs(s.phase-3*once)<1e-10);s.running=false;D.advance(s,.05);assert.equal(s.phase,3*once);
const model=M.create(T);model.highlight('motor');
function validate(){const d=model.diagnostics();for(const [a,b] of [[0,1],[2,3]]){const p=d[a],q=d[b];assert.ok(Math.abs(Math.hypot(p.center[0]-q.center[0],p.center[1]-q.center[1])-p.pitchRadius-q.pitchRadius)<1e-8,'pitch contact');assert.ok(Math.abs(p.center[2]-q.center[2])<.001,'face overlap');assert.ok(Math.abs(p.omega*p.pitchRadius+q.omega*q.pitchRadius)<1e-9,'signed velocity');}assert.equal(model.gears[1].rotation.z,model.gears[2].rotation.z);assert.equal(model.rotor.rotation.z,model.gears[0].rotation.z);model.wheels.forEach(w=>assert.equal(w.rotation.z,model.gears[3].rotation.z));}
const samples=[];for(let i=0;i<=120;i++){model.update(i*Math.PI/60,45);validate();model.group.traverse(o=>{if(o.isMesh&&o.parent.type!=='ArrowHelper'){assert.deepEqual(o.scale.toArray(),[1,1,1]);for(const x of o.geometry.attributes.position.array)assert.ok(Number.isFinite(x));}});samples.push({label:'EV input '+i,parts:model.diagnostics(),meshes:[{a:'g0',b:'g1',type:'external',distanceTolerance:1e-8,velocityTolerance:1e-8,moduleTolerance:1e-8,minimumFaceOverlap:.29},{a:'g2',b:'g3',type:'external',distanceTolerance:1e-8,velocityTolerance:1e-8,moduleTolerance:1e-8,minimumFaceOverlap:.29}],rigidBodies:model.shafts.map((o,j)=>({id:'shaft'+j,tolerance:1e-8,landmarks:[new T.Vector3(0,0,-.5),new T.Vector3(0,0,.5)].map(v=>o.localToWorld(v).toArray())}))});}
model.gears[1].position.x+=.2;assert.throws(validate,/pitch contact/);model.gears[1].position.x-=.2;model.gears[1].position.z+=1;assert.throws(validate,/face overlap/);model.gears[1].position.z-=1;validate();
// Actual render geometry bounds: attached arbors overlap their gears; separated working layers clear.
model.update(0,45);for(const [si,gis] of [[0,[0]],[1,[1,2]],[2,[3]]]){const shaft=new T.Box3().setFromObject(model.shafts[si]);for(const gi of gis){const gear=new T.Box3().setFromObject(model.gears[gi]);assert.ok(Math.min(shaft.max.z,gear.max.z)-Math.max(shaft.min.z,gear.min.z)>.1);}}
const a=new T.Box3().setFromObject(model.gears[1]),b=new T.Box3().setFromObject(model.gears[2]);assert.ok(b.min.z-a.max.z>.5);
// Transform tessellated tooth boundaries through the actual mesh world matrices.
function polygon(o){return o.userData.outline.map(([x,y])=>{const v=o.localToWorld(new T.Vector3(x,y,0));return [v.x,v.y];});}
function inside(p,poly){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
for(let i=0;i<=90;i++){model.update(i*Math.PI/450,45);for(const [ai,bi] of [[0,1],[2,3]]){const a=polygon(model.gears[ai]),b=polygon(model.gears[bi]);const center=model.gears[bi].position,r=model.gears[bi].userData.pitchRadius+.091;for(const p of a)if(Math.hypot(p[0]-center.x,p[1]-center.y)<r)assert.ok(!inside(p,b),'tooth vertex intrusion');}}
if(process.argv[2])fs.writeFileSync(process.argv[2],JSON.stringify({samples}));
const html=fs.readFileSync(path.resolve(__dirname,'../ev.html'),'utf8');for(const a of ['ev.css','ev-data.js','ev-model.js','ev-app.js'])assert.ok(html.includes(a));
console.log('PASS curriculum, power limits, electrical sizing, clock pause/rate, 121 rendered mesh/rigidity samples, 91 tooth-phase samples, shaft overlaps and injected gap/layer faults. Not a full CAD collision audit.');
